
local addonName, addon = ...
local _G = _G

-- GLOBALS: UIDropDownMenu_AddButton

addon.hiddenOptions = {
	["UnitNameOwn"] = { prettyName = UNIT_NAME_OWN, description = OPTION_TOOLTIP_UNIT_NAME_OWN, type = "boolean" },
	["UnitNameNPC"] = { prettyName = UNIT_NAME_NPC, description = OPTION_TOOLTIP_UNIT_NAME_NPC, type = "boolean" },
	["UnitNameNonCombatCreatureName"] = { prettyName = UNIT_NAME_NONCOMBAT_CREATURE, description = OPTION_TOOLTIP_UNIT_NAME_NONCOMBAT_CREATURE, type = "boolean" },
	["UnitNamePlayerGuild"] = { prettyName = UNIT_NAME_GUILD, description = OPTION_TOOLTIP_UNIT_NAME_GUILD, type = "boolean" },
	["UnitNameGuildTitle"] = { prettyName = UNIT_NAME_GUILD_TITLE, description = OPTION_TOOLTIP_UNIT_NAME_GUILD_TITLE , type = "boolean" },
	["UnitNamePlayerPVPTitle"] = { prettyName = UNIT_NAME_PLAYER_TITLE, description = OPTION_TOOLTIP_UNIT_NAME_PLAYER_TITLE, type = "boolean" },

	["UnitNameFriendlyPlayerName"] = { prettyName = UNIT_NAME_FRIENDLY, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY, type = "boolean" },
	["UnitNameFriendlyPetName"] = { prettyName = UNIT_NAME_FRIENDLY_PETS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_PETS, type = "boolean" },
	["UnitNameFriendlyGuardianName"] = { prettyName = UNIT_NAME_FRIENDLY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_GUARDIANS, type = "boolean" },
	["UnitNameFriendlyTotemName"] = { prettyName = UNIT_NAME_FRIENDLY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_TOTEMS, type = "boolean" },

	["UnitNameEnemyPlayerName"] = { prettyName = UNIT_NAME_ENEMY, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY, type = "boolean" },
	["UnitNameEnemyPetName"] = { prettyName = UNIT_NAME_ENEMY_PETS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_PETS, type = "boolean" },
	["UnitNameEnemyGuardianName"] = { prettyName = UNIT_NAME_ENEMY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_GUARDIANS, type = "boolean" },
	["UnitNameEnemyTotemName"] = { prettyName = UNIT_NAME_ENEMY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_TOTEMS, type = "boolean" },
	["UnitNameForceHideMinus"] = { prettyName = UNIT_NAME_HIDE_MINUS, description = OPTION_TOOLTIP_UNIT_NAME_HIDE_MINUS, type = "boolean" },

	["nameplateShowFriends"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDS, type = "boolean" },
	["nameplateShowFriendlyPets"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_PETS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_PETS, type = "boolean" },
	["nameplateShowFriendlyGuardians"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_GUARDIANS, type = "boolean" },
	["nameplateShowFriendlyTotems"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_TOTEMS, type = "boolean" },
	["nameplateShowEnemies"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMIES, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMIES, type = "boolean" },
	["nameplateShowEnemyPets"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_PETS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_PETS, type = "boolean" },
	["nameplateShowEnemyGuardians"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_GUARDIANS, type = "boolean" },
	["nameplateShowEnemyTotems"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_TOTEMS, type = "boolean" },
	["nameplateShowEnemyMinus"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_MINUS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_MINUS, type = "boolean" },
	["ShowClassColorInNameplate"] = { prettyName = SHOW_CLASS_COLOR_IN_V_KEY, description = OPTION_TOOLTIP_SHOW_CLASS_COLOR_IN_V_KEY, type = "boolean" },
	["nameplateOtherAtBase"] = { prettyName = "血條在下方", description = "將其他血條顯示在下方，而不是頭頂上。 2=單位下方, 0=單位上方", type = "boolean" },
	["nameplateOverlapH"] = { prettyName = "血條重疊(水平)", description = "血條的水平重疊百分比", type = "number" },
	["nameplateOverlapV"] = { prettyName = "血條重疊(垂直)", description = "血條的垂直重疊百分比", type = "number" },
	["nameplateMaxDistance"] = { prettyName = "血條距離", description = "顯示血條的最遠距離。", type = "number" },
	
	["nameplateTargetBehindMaxDistance"] = { prettyName = "Nameplate Target Behind Distance", description = "當目標在鏡頭之後目標血條顯示的最遠距離。", type = "number" },
	["nameplateGlobalScale"] = { prettyName = "血條通用縮放", description = "Applies global scaling to non-self nameplates, this is applied AFTER selected, min, and max scale.", type = "number" },
	["nameplateMinScale"] = { prettyName = "血條最小縮放", description = "血條最小縮放值。", type = "number" },
	["nameplateMaxScale"] = { prettyName = "血條最大縮放", description = "血條最大縮放值。", type = "number" },
	["nameplateLargerScale"] = { prettyName = "血條更大縮放", description = "一個額外的縮放變更在重要的怪物。", type = "number" },
	["nameplateMinScaleDistance"] = { prettyName = "血條最小縮放距離", description = "The distance from the max distance that nameplates will reach their minimum scale.", type = "number" },
	["nameplateMaxScaleDistance"] = { prettyName = "血條最大縮放距離", description = "The distance from the camera that nameplates will reach their maximum scale", type = "number" },
	["nameplateMinAlpha"] = { prettyName = "血條最低透明度", description = "The minimum alpha of nameplates.", type = "number" },
	["nameplateMaxAlpha"] = { prettyName = "血條最高透明度", description = "The max alpha of nameplates.", type = "number" },
	["nameplateMinAlphaDistance"] = { prettyName = "血條最低透明度距離", description = "The distance from the max distance that nameplates will reach their minimum alpha.", type = "number" },
	["nameplateMaxAlphaDistance"] = { prettyName = "血條最高透明度距離", description = "The distance from the camera that nameplates will reach their maximum alpha.", type = "number" },
	["nameplateSelectedScale"] = { prettyName = "選擇的血條縮放", description = "The scale of the selected nameplate.", type = "number" },
	["nameplateSelectedAlpha"] = { prettyName = "選擇的血條透明度", description = "The alpha of the selected nameplate.", type = "number" },
	["nameplateSelfScale"] = { prettyName = "自我血條縮放", description = "The scale of the self nameplate.", type = "number" },
	["nameplateSelfAlpha"] = { prettyName = "自我血條透明度", description = "The alpha of the self nameplate.", type = "number" },
	["nameplateSelfBottomInset"] = { prettyName = "自我血條置底", description = "嵌置在螢幕底部 (螢幕百分比) 。", type = "number" },
	["nameplateSelfTopInset"] = { prettyName = "自我血條置頂", description = "嵌置在螢幕頂部 (螢幕百分比) 。", type = "number" },
	["nameplateOtherBottomInset"] = { prettyName = "其他血條置底", description = "其他血條嵌置在螢幕底部 (螢幕百分比) 。", type = "number" },
	["nameplateOtherTopInset"] = { prettyName = "其他血條置頂", description = "其他血條嵌置在螢幕頂部 (螢幕百分比) 。", type = "number" },
	["nameplateLargeBottomInset"] = { prettyName = "大血條置底", description = "大血條嵌置在螢幕底部 (螢幕百分比) 。", type = "number" },
	["nameplateLargeTopInset"] = { prettyName = "大血條置頂", description = "大血條嵌置在螢幕頂部 (螢幕百分比) 。", type = "number" },
	["nameplateClassResourceTopInset"] = { prettyName = "血條職業資源置頂", description = "當職業資源顯示時嵌置在螢幕頂部 (螢幕百分比) 。", type = "number" },
	["NamePlateHorizontalScale"] = { prettyName = "血條水平縮放", description = "套用在所有血條的水平大小。", type = "number" },
	["NamePlateVerticalScale"] = { prettyName = "血條垂直縮放", description = "套用在所有血條的垂直大小。", type = "number" },
	["nameplateResourceOnTarget"] = { prettyName = "目標血條資源", description = "血條職業資源覆蓋模式。 0=自己, 1=目標", type = "number" },
	["nameplateShowSelf"] = { prettyName = "顯示血條資源條", description = "顯示職業資源條 0=off 1=on", type = "number" },
	["nameplateShowAll"] = { prettyName = "永遠顯示血條", description = "不管何時永遠顯示血條。", type = "number" },

	["reverseCleanupBags"] = { prettyName = "反向整理背包", description = OPTION_TOOLTIP_REVERSE_CLEAN_UP_BAGS, type = "boolean" },
	["lootLeftmostBag"] = { prettyName = REVERSE_NEW_LOOT_TEXT, description = OPTION_TOOLTIP_REVERSE_NEW_LOOT, type = "boolean" },
	["stopAutoAttackOnTargetChange"] = { prettyName = STOP_AUTO_ATTACK, description = OPTION_TOOLTIP_STOP_AUTO_ATTACK, type = "boolean" },
	["assistAttack"] = { prettyName = ASSIST_ATTACK, description = OPTION_TOOLTIP_ASSIST_ATTACK, type = "boolean" },
	["autoSelfCast"] = { prettyName = AUTO_SELF_CAST_TEXT, description = OPTION_TOOLTIP_SELF_CAST_TEXT, type = "boolean" },
	["ActionButtonUseKeyDown"] = { prettyName = ACTION_BUTTON_USE_KEY_DOWN, description = OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN, type = "boolean" },
	["mapFade"] = { prettyName = MAP_FADE_TEXT, description = OPTION_TOOLTIP_MAP_FADE, type = "boolean" },
	["trackQuestSorting"] = { type = "table", options = {"proximity", "top" } },
	["removeChatDelay"] = { prettyName = REMOVE_CHAT_DELAY_TEXT, description = OPTION_TOOLTIP_REMOVE_CHAT_DELAY_TEXT, type = "boolean" },
	["secureAbilityToggle"] = { prettyName = SECURE_ABILITY_TOGGLE, description = OPTION_TOOLTIP_SECURE_ABILITY_TOGGLE, type = "boolean" },
	["scriptErrors"] = { prettyName = SHOW_LUA_ERRORS, description = OPTION_TOOLTIP_SHOW_LUA_ERRORS, type = "boolean" },
	["lootUnderMouse"] = { prettyName = LOOT_UNDER_MOUSE_TEXT, description = OPTION_TOOLTIP_LOOT_UNDER_MOUSE_TEXT, type = "boolean" },

	["autoLootDefault"] = { prettyName = AUTO_LOOT_DEFAULT_TEXT, description = OPTION_TOOLTIP_AUTO_LOOT_DEFAULT, type = "boolean" },
	["threatShowNumeric"] = { prettyName = SHOW_NUMERIC_THREAT, description = OPTION_TOOLTIP_SHOW_NUMERIC_THREAT, type = "boolean" },
	["showLootSpam"] = { prettyName = SHOW_LOOT_SPAM, description = OPTION_TOOLTIP_SHOW_LOOT_SPAM, type = "boolean" },
	["advancedWatchFrame"] = { prettyName = ADVANCED_OBJECTIVES_TEXT, description = OPTION_TOOLTIP_ADVANCED_OBJECTIVES_TEXT, type = "" },
	["watchFrameIgnoreCursor"] = { prettyName = OBJECTIVES_IGNORE_CURSOR_TEXT, description = OPTION_TOOLTIP_OBJECTIVES_IGNORE_CURSOR, type = "boolean" },
	["guildMemberNotify"] = { prettyName = GUILDMEMBER_ALERT, description = OPTION_TOOLTIP_GUILDMEMBER_ALERT, type = "boolean" },
	["showArenaEnemyFrames"] = { prettyName = SHOW_ARENA_ENEMY_FRAMES_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_FRAMES, type = "boolean" },

	["autoClearAFK"] = { prettyName = nil, description = OPTION_TOOLTIP_CLEAR_AFK, type = "boolean" },
	["colorblindWeaknessFactor"] = { prettyName = nil, description = OPTION_TOOLTIP_ADJUST_COLORBLIND_STRENGTH, type = "boolean" },
	["autoLootDefault"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_LOOT_DEFAULT, type = "boolean" },
	["autoLootRate"] = { prettyName = "自動拾取速度", description = "自動拾取的速度 (毫秒)", type = "number" },
	["ChatAmbienceVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_, type = "boolean" },
	["threatShowNumeric"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_NUMERIC_THREAT, type = "boolean" },
	["rightActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR3, type = "boolean" },
	["emphasizeMySpellEffects"] = { prettyName = nil, description = OPTION_TOOLTIP_EMPHASIZE_MY_SPELLS, type = "boolean" },
	["chatBubblesParty"] = { prettyName = nil, description = OPTION_TOOLTIP_PARTY_CHAT_BUBBLES, type = "boolean" },
	["enableTwitter"] = { prettyName = nil, description = OPTION_TOOLTIP_SOCIAL_ENABLE_TWITTER_FUNCTIONALITY, type = "boolean" },
	["threatPlaySounds"] = { prettyName = nil, description = OPTION_TOOLTIP_PLAY_AGGRO_SOUNDS, type = "boolean" },

	["showToastOnline"] = { prettyName = SHOW_TOAST_ONLINE_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_ONLINE, type = "boolean" },
	["showToastOffline"] = { prettyName = SHOW_TOAST_OFFLINE_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_OFFLINE, type = "boolean" },
	["showToastBroadcast"] = { prettyName = SHOW_TOAST_BROADCAST_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_BROADCAST, type = "boolean" },
	["showToastFriendRequest"] = { prettyName = SHOW_TOAST_FRIEND_REQUEST_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_FRIEND_REQUEST, type = "boolean" },
	["showToastConversation"] = { prettyName = SHOW_TOAST_CONVERSATION_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_CONVERSATION, type = "boolean" },
	["showToastWindow"] = { prettyName = SHOW_TOAST_WINDOW_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_WINDOW, type = "boolean" },
	["toastDuration"] = { prettyName = nil, description = OPTION_TOOLTIP_TOAST_DURATION, type = "number" },

	["enableMouseSpeed"] = { prettyName = ENABLE_MOUSE_SPEED, description = OPTION_TOOLTIP_ENABLE_MOUSE_SPEED, type = "boolean" },
	["mouseInvertPitch"] = { prettyName = INVERT_MOUSE, description = OPTION_TOOLTIP_INVERT_MOUSE, type = "boolean" },
	["enableWoWMouse"] = { prettyName = WOW_MOUSE, description = OPTION_TOOLTIP_WOW_MOUSE, type = "boolean" },
	["autointeract"] = { prettyName = CLICK_TO_MOVE, description = OPTION_TOOLTIP_CLICK_TO_MOVE, type = "boolean" },
	["mouseSpeed"] = { prettyName = MOUSE_SENSITIVITY, description = OPTION_TOOLTIP_MOUSE_SENSITIVITY, type = "number" },

	["wholeChatWindowClickable"] = { prettyName = nil, description = OPTION_TOOLTIP_CHAT_WHOLE_WINDOW_CLICKABLE, type = "boolean" },
	["useEnglishAudio"] = { prettyName = nil, description = OPTION_TOOLTIP_USE_ENGLISH_AUDIO, type = "boolean" },
	["ChatSoundVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_, type = "number" },
	["reducedLagTolerance"] = { prettyName = nil, description = OPTION_TOOLTIP_REDUCED_LAG_TOLERANCE, type = "boolean" },
	["EnableMicrophone"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_MICROPHONE, type = "boolean" },
	["autoOpenLootHistory"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_OPEN_LOOT_HISTORY, type = "boolean" },
	["showVKeyCastbarOnlyOnTarget"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY_ONLY_ON_TARGET, type = "boolean" },
	["displaySpellActivationOverlays"] = { prettyName = nil, description = OPTION_TOOLTIP_DISPLAY_SPELL_ALERTS, type = "boolean" },
	["hdPlayerModels"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_HD_MODELS, type = "boolean" },
	["autoLootKey"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_LOOT_KEY, type = "boolean" }, -- TODO TYPE
	["MaxSpellStartRecoveryOffset"] = { prettyName = nil, description = OPTION_TOOLTIP_LAG_TOLERANCE, type = "number" },
	["advancedCombatLogging"] = { prettyName = nil, description = OPTION_TOOLTIP_ADVANCED_COMBAT_LOGGING, type = "boolean" },
	["disableServerNagle"] = { prettyName = nil, description = OPTION_TOOLTIP_OPTIMIZE_NETWORK_SPEED, type = "boolean" },
	["cameraYawSmoothSpeed"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_FOLLOW_SPEED, type = "number" },
	["cameraWaterCollision"] = { prettyName = nil, description = OPTION_TOOLTIP_WATER_COLLISION, type = "boolean" },
	["cameraBobbing"] = { prettyName = nil, description = OPTION_TOOLTIP_HEAD_BOB, type = "boolean" },
	["cameraPivot"] = { prettyName = nil, description = OPTION_TOOLTIP_SMART_PIVOT, type = "boolean" },
	["cameraDistanceMaxFactor"] = { prettyName = nil, description = OPTION_TOOLTIP_MAX_FOLLOW_DIST, type = "number" },
	["cameraYawMoveSpeed"] = { prettyName = MOUSE_LOOK_SPEED, description = OPTION_TOOLTIP_MOUSE_LOOK_SPEED, type = "number" },
	["cameraTerrainTilt"] = { prettyName = nil, description = OPTION_TOOLTIP_FOLLOW_TERRAIN, type = "boolean" },
	["cameraHeadMovementStrength"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementWhileStanding"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementRange"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementSmoothRate"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitch"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitchBaseFovPad"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitchBaseFovPadFlying"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitchSmartPivotCutoffDist"] = { prettyName = nil, description = nil, type = "number" },
	["cameraOverShoulder"] = { prettyName = nil, description = nil, type = "number" },
	["cameraLockedTargetFocusing"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDistanceMoveSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraPitchMoveSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraBobbingSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraFoVSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDistanceSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraGroundSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeightSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraPitchSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraTargetSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraFlyingMountHeightSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraViewBlendStyle"] = { prettyName = nil, description = nil, type = "number" },
	["camerasmooth"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothPitch"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothYaw"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothStyle"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothTrackingStyle"] = { prettyName = nil, description = nil, type = "number" },

	["chatBubbles"] = { prettyName = nil, description = OPTION_TOOLTIP_CHAT_BUBBLES, type = "boolean" },
	["autoDismountFlying"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_DISMOUNT_FLYING, type = "boolean" },
	["bottomRightActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR2, type = "boolean" },

	["showPartyBackground"] = { prettyName = SHOW_PARTY_BACKGROUND_TEXT, description = OPTION_TOOLTIP_SHOW_PARTY_BACKGROUND, type = "boolean" },
	["showPartyPets"] = { prettyName = SHOW_PARTY_PETS_TEXT, description = OPTION_TOOLTIP_SHOW_PARTY_PETS, type = "boolean" },
	["showArenaEnemyFrames"] = { prettyName = SHOW_ARENA_ENEMY_FRAMES_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_FRAMES, type = "boolean" },
	["showArenaEnemyCastbar"] = { prettyName = SHOW_ARENA_ENEMY_CASTBAR_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_CASTBAR, type = "boolean" },
	["showArenaEnemyPets"] = { prettyName = SHOW_ARENA_ENEMY_PETS_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_PETS, type = "boolean" },
	["fullSizeFocusFrame"] = { prettyName = FULL_SIZE_FOCUS_FRAME_TEXT, description = OPTION_TOOLTIP_FULL_SIZE_FOCUS_FRAME, type = "boolean" },

	["showChatIcons"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_CHAT_ICONS, type = "boolean" },
	["spamFilter"] = { prettyName = nil, description = OPTION_TOOLTIP_SPAM_FILTER, type = "boolean" },
	["profanityFilter"] = { prettyName = nil, description = OPTION_TOOLTIP_PROFANITY_FILTER, type = "boolean" },
	["EnableVoiceChat"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_VOICECHAT, type = "boolean" },
	["rightTwoActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR4, type = "boolean" },
	["rotateMinimap"] = { prettyName = nil, description = OPTION_TOOLTIP_ROTATE_MINIMAP, type = "boolean" },
	["blockTrades"] = { prettyName = nil, description = OPTION_TOOLTIP_BLOCK_TRADES, type = "boolean" },
	["movieSubtitle"] = { prettyName = nil, description = OPTION_TOOLTIP_CINEMATIC_SUBTITLES, type = "boolean" },
	["displayFreeBagSlots"] = { prettyName = nil, description = OPTION_TOOLTIP_DISPLAY_FREE_BAG_SLOTS, type = "boolean" },
	["lockActionBars"] = { prettyName = nil, description = OPTION_TOOLTIP_LOCK_ACTIONBAR, type = "boolean" },
	["screenEdgeFlash"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_FULLSCREEN_STATUS, type = "boolean" },
	["showVKeyCastbar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY, type = "boolean" },
	["chatMouseScroll"] = { prettyName = "使用滑鼠滾輪捲動", description = OPTION_TOOLTIP_CHAT_MOUSE_WHEEL_SCROLL, type = "boolean" },
	["showGameTips"] = { prettyName = SHOW_TIPOFTHEDAY_TEXT, description = OPTION_TOOLTIP_SHOW_TIPOFTHEDAY, type = "boolean" },
	["InboundChatVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_OUTPUT_VOLUME, type = "number" },
	["spellActivationOverlayOpacity"] = { prettyName = nil, description = OPTION_TOOLTIP_SPELL_ALERT_OPACITY, type = "number" },
	["PushToTalkSound"] = { prettyName = nil, description = OPTION_TOOLTIP_PUSHTOTALK_SOUND, type = "boolean" },
	["countdownForCooldowns"] = { prettyName = nil, description = OPTION_TOOLTIP_COUNTDOWN_FOR_COOLDOWNS, type = "boolean" },
	["VoiceActivationSensitivity"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_ACTIVATION_SENSITIVITY, type = "number" },
	["alwaysShowActionBars"] = { prettyName = nil, description = OPTION_TOOLTIP_ALWAYS_SHOW_MULTIBARS, type = "boolean" },
	["OutboundChatVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_INPUT_VOLUME, type = "number" },
	["autoQuestWatch"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_QUEST_WATCH, type = "boolean" },
	["SpellTooltip_DisplayAvgValues"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_POINTS_AS_AVG, type = "boolean" },

	["xpBarText"] = { prettyName = XP_BAR_TEXT, description = OPTION_TOOLTIP_XP_BAR, type = "boolean" },

	["bottomLeftActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR1, type = "boolean" },
	["showVKeyCastbarSpellName"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY_SPELL_NAME, type = "boolean" },
	["buffDurations"] = { prettyName = SHOW_BUFF_DURATION_TEXT, description = OPTION_TOOLTIP_SHOW_BUFF_DURATION, type = "boolean" },
	["showDispelDebuffs"] = { prettyName = SHOW_DISPELLABLE_DEBUFFS_TEXT, description = OPTION_TOOLTIP_SHOW_DISPELLABLE_DEBUFFS, type = "boolean" },
	["showCastableBuffs"] = { prettyName = SHOW_CASTABLE_BUFFS_TEXT, description = OPTION_TOOLTIP_SHOW_CASTABLE_BUFFS, type = "boolean" },
	["deselectOnClick"] = { prettyName = nil, description = OPTION_TOOLTIP_GAMEFIELD_DESELECT, type = "boolean" },
	["autoQuestProgress"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_QUEST_PROGRESS, type = "boolean" },
	["UberTooltips"] = { prettyName = USE_UBERTOOLTIPS, description = OPTION_TOOLTIP_USE_UBERTOOLTIPS, type = "boolean" },
	["Sound_EnableAllSound"] = { prettyName = ENABLE_SOUND, description = OPTION_TOOLTIP_ENABLE_SOUND, type = "boolean" },
	["Sound_EnableDSPEffects"] = { prettyName = ENABLE_DSP_EFFECTS, description = OPTION_TOOLTIP_ENABLE_DSP_EFFECTS, type = "boolean" },
	["Sound_SFXVolume"] = { prettyName = SOUND_VOLUME, description = OPTION_TOOLTIP_SOUND_VOLUME, type = "number" },
	["Sound_ZoneMusicNoDelay"] = { prettyName = ENABLE_MUSIC_LOOPING, description = OPTION_TOOLTIP_ENABLE_MUSIC_LOOPING, type = "boolean" },
	["Sound_EnableDialog"] = { prettyName = ENABLE_DIALOG, description = OPTION_TOOLTIP_ENABLE_DIALOG, type = "boolean" },
	["Sound_EnableSoundWhenGameIsInBG"] = { prettyName = ENABLE_BGSOUND, description = OPTION_TOOLTIP_ENABLE_BGSOUND, type = "boolean" },
	["Sound_EnableEmoteSounds"] = { prettyName = ENABLE_EMOTE_SOUNDS, description = OPTION_TOOLTIP_ENABLE_EMOTE_SOUNDS, type = "boolean" },
	["Sound_EnableAmbience"] = { prettyName = ENABLE_AMBIENCE, description = OPTION_TOOLTIP_ENABLE_AMBIENCE, type = "boolean" },
	["Sound_DialogVolume"] = { prettyName = DIALOG_VOLUME, description = OPTION_TOOLTIP_DIALOG_VOLUME, type = "number" },
	["Sound_EnablePetBattleMusic"] = { prettyName = ENABLE_PET_BATTLE_MUSIC, description = OPTION_TOOLTIP_ENABLE_PET_BATTLE_MUSIC, type = "boolean" },
	["Sound_MusicVolume"] = { prettyName = MUSIC_VOLUME, description = OPTION_TOOLTIP_MUSIC_VOLUME, type = "number" },
	["Sound_EnableReverb"] = { prettyName = ENABLE_REVERB, description = OPTION_TOOLTIP_ENABLE_REVERB, type = "boolean" },
	["Sound_MasterVolume"] = { prettyName = MASTER_VOLUME, description = OPTION_TOOLTIP_MASTER_VOLUME, type = "number" },
	["Sound_EnableMusic"] = { prettyName = ENABLE_MUSIC, description = OPTION_TOOLTIP_ENABLE_MUSIC, type = "boolean" },
	["Sound_AmbienceVolume"] = { prettyName = AMBIENCE_VOLUME, description = OPTION_TOOLTIP_AMBIENCE_VOLUME, type = "number" },
	["Sound_EnableErrorSpeech"] = { prettyName = ENABLE_ERROR_SPEECH, description = OPTION_TOOLTIP_ENABLE_ERROR_SPEECH, type = "boolean" },
	["Sound_EnableSFX"] = { prettyName = ENABLE_SOUNDFX, description = OPTION_TOOLTIP_ENABLE_SOUNDFX, type = "boolean" },
	["Sound_ListenerAtCharacter"] = { prettyName = ENABLE_SOUND_AT_CHARACTER, description = OPTION_TOOLTIP_ENABLE_SOUND_AT_CHARACTER, type = "boolean" },
	["Sound_EnablePetSounds"] = { prettyName = ENABLE_PET_SOUNDS, description = OPTION_TOOLTIP_ENABLE_PET_SOUNDS, type = "boolean" },

	["showTargetOfTarget"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_OF_TARGET, type = "boolean" },
	["guildMemberNotify"] = { prettyName = nil, description = OPTION_TOOLTIP_GUILDMEMBER_ALERT, type = "boolean" },
	["Sound_EnableSoftwareHRTF"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_SOFTWARE_HRTF, type = "boolean" },
	["advancedWorldMap"] = { prettyName = nil, description = OPTION_TOOLTIP_ADVANCED_WORLD_MAP, type = "boolean" },
	["showTutorials"] = { prettyName = SHOW_TUTORIALS, description = OPTION_TOOLTIP_SHOW_TUTORIALS, type = "boolean" },
	["lossOfControl"] = { prettyName = nil, description = OPTION_TOOLTIP_LOSS_OF_CONTROL, type = "boolean" },
	["blockChannelInvites"] = { prettyName = nil, description = OPTION_TOOLTIP_BLOCK_CHAT_CHANNEL_INVITE, type = "boolean" },
	["showTargetCastbar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR, type = "boolean" },
	["enablePetBattleCombatText"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_PETBATTLE_COMBAT, type = "boolean" },
	["colorblindMode"] = { prettyName = nil, description = OPTION_TOOLTIP_USE_COLORBLIND_MODE, type = "boolean" },
	["useIPv6"] = { prettyName = USEIPV6, description = OPTION_TOOLTIP_USEIPV6, type = "boolean" },
	["interactOnLeftClick"] = { prettyName = INTERACT_ON_LEFT_CLICK_TEXT, description = OPTION_TOOLTIP_INTERACT_ON_LEFT_CLICK, type = "boolean" },
	["enableMovePad"] = { prettyName = MOVE_PAD, description = OPTION_TOOLTIP_MOVE_PAD, type = "boolean" },
	["colorblindSimulator"] = { prettyName = nil, description = OPTION_TOOLTIP_COLORBLIND_FILTER, type = "boolean" },

	["noBuffDebuffFilterOnTarget"] = { prettyName = "不要過濾目標的光環", description = "不要過濾所有目標身上的增益和減益效果", type = "boolean"},
	["showHonorAsExperience"] = { prettyName = nil, description = "將榮譽條顯示為一般的經驗條，顯示在聲望條的位置。", type = "boolean"},
	["ShowNamePlateLoseAggroFlash"] = { prettyName = nil, description = "啟用時，當你的角色是坦克並且失去仇恨時，血條會輕微閃爍。", type = "boolean"},
	["Sound_EnablePositionalLowPassFilter"] = { prettyName = ENABLE_SOFTWARE_HRTF, description = "", type = "boolean"},
	["TargetPriorityAllowAnyOnScreen"] = { prettyName = nil, description = "啟用時，若無法100%選取正確的目標，將允許選取有效範圍內的任何目標 (2 = 也允許超出範圍的目標)。", type = "boolean"},
	["TargetNearestUseOld"] = { prettyName = nil, description = "使用 7.0 版以前的 '最接近目標' 功能", type = "boolean"},
	["TargetPriorityCombatLock"] = { prettyName = nil, description = "1=Lock to in-combat targets when starting from an in-combat target. 2=Further restrict to in-combat with player.", type = "boolean"},
	["TargetPriorityCombatLockHighlight"] = { prettyName = nil, description = "1=Lock to in-combat targets when starting from an in-combat target. 2=Further restrict to in-combat with player. (while doing hold-to-target)", type = "boolean"},
	["TargetPriorityHoldHighlightDelay"] = { prettyName = nil, description = "按下按鈕後，顯著標示首要目標前的延遲時間 (毫秒)", type = "number"},
	["TargetPriorityIncludeBehind"] = { prettyName = nil, description = "啟用時，選取首要目標也會包含玩家身後的目標", type = "boolean"},
	["TargetPriorityPvp"] = { prettyName = nil, description = "PvP時，會優先選擇玩家和重要的PvP目標  (2 = 所有PvP目標, 3 = 只有玩家)", type = "boolean"},
	["TargetPriorityPvpLock"] = { prettyName = nil, description = "開始時是PvP目標，則鎖定至重要的PvP目標。", type = "boolean"},
	["TargetPriorityPvpLockHighlight"] = { prettyName = nil, description = "在PvP中開始時是玩家，則鎖定至玩家。(同時執行 hold-to-target)", type = "boolean"},
	["TargetPriorityValueBank"] = { prettyName = nil, description = "依據積分計算目標的優先順序", type = "boolean"},
	["unitClutter"] = { prettyName = nil, description = "啟用/停用 單位clutter", type = "boolean"},
	["unitClutterInstancesOnly"] = { prettyName = nil, description = "是否使用單位clutter 只在副本中 (0 or 1)", type = "boolean"},
	["unitClutterPlayerThreshold"] = { prettyName = nil, description = "在附近觸發單位clutter的玩家數量", type = "boolean"},
	["UnitNameEnemyMinionName"] = { prettyName = UNIT_NAME_ENEMY_MINIONS, description = "", type = "boolean"},
	["UnitNameFriendlyMinionName"] = { prettyName = UNIT_NAME_FRIENDLY_MINIONS, description = "", type = "boolean"},
	["comboPointLocation"] = { prettyName = nil, description = "連擊點數在UI中的位置。 1 = 目標, 2 = 自己", type = "number"},
	["doNotFlashLowHealthWarning"] = { prettyName = nil, description = "低生命力時不要在整個畫面上閃爍紅色。", type = "boolean"},
	["enableFloatingCombatText"] = { prettyName = nil, description = "是否要顯示浮動戰鬥文字", type = "boolean"},
	["findYourselfAnywhere"] = { prettyName = nil, description = "總是保持顯著標示你的角色", type = "boolean"},
	["findYourselfAnywhereOnlyInCombat"] = { prettyName = nil, description = "只在戰鬥中顯著標示你的角色", type = "boolean"},
	["findYourselfInBG"] = { prettyName = nil, description = "在戰場時總是保持顯著標示你的角色", type = "boolean"},
	["findYourselfInBGOnlyInCombat"] = { prettyName = "在戰場時只在戰鬥中顯著標示你的角色", description = "", type = "boolean"},
	["findYourselfInRaid"] = { prettyName = nil, description = "在團隊時總是保持顯著標示你的角色", type = "boolean"},
	["findYourselfInRaidOnlyInCombat"] = { prettyName = nil, description = "在團隊時只在戰鬥中顯著標示你的角色", type = "boolean"},
	["findYourselfMode"] = { prettyName = nil, description = "顯示標示你的角色。 0 = 圓圈, 1 = 圓圈和外框", type = "boolean"},
	["flashErrorMessageRepeats"] = { prettyName = nil, description = "再次出現相同的訊息時，閃爍畫面中央的紅色錯誤文字。", type = "boolean"},
	["floatingCombatTextAllSpellMechanics"] = { prettyName = nil, description = "", type = "boolean"},
	["floatingCombatTextAuras"] = { prettyName = "FCT: 獲得/失去光環", description = "", type = "boolean"},
	["floatingCombatTextCombatDamage"] = { prettyName = nil, description = "造成傷害時在敵對生物上顯示傷害數字", type = "boolean"},
	["floatingCombatTextCombatDamageAllAutos"] = { prettyName = nil, description = "顯示所有自動攻擊的數字，不要隱藏非玩家按下技能的數字。", type = "boolean"},
	["floatingCombatTextCombatDamageDirectionalOffset"] = { prettyName = nil, description = "多方向傷害數字出現時偏移的數量", type = "boolean"},
	["floatingCombatTextCombatDamageDirectionalScale"] = { prettyName = "FCT: 多方向顯示數字", description = "不同大小的傷害數字會往不同的方向顯示 (0 = 不要使用多方向顯示數字)", type = "boolean"},
	["floatingCombatTextCombatHealing"] = { prettyName = "FCT: 治療", description = "顯示你對目標恢復的生命量", type = "boolean"},
	["floatingCombatTextCombatHealingAbsorbSelf"] = { prettyName = "FCT: 吸收傷害 (自己)", description = "顯示自己獲得盾的訊息。", type = "boolean"},
	["floatingCombatTextCombatHealingAbsorbTarget"] = { prettyName = "FCT: 吸收傷害 (目標)", description = "顯示套用在目標身上的盾所吸收的傷害量。", type = "boolean"},
	["floatingCombatTextCombatLogPeriodicSpells"] = { prettyName = "FCT: 週期性法術傷害", description = "顯示週期性效果造成的傷害", type = "boolean"},
	["floatingCombatTextCombatState"] = { prettyName = "FCT: 進入/離開戰鬥", description = "", type = "boolean"},
	["floatingCombatTextComboPoints"] = { prettyName = "FCT: 連擊點數", description = "", type = "boolean"},
	["floatingCombatTextDamageReduction"] = { prettyName = "FCT: 傷害減免", description = "", type = "boolean"},
	["floatingCombatTextDodgeParryMiss"] = { prettyName = "FCT: 閃躲/架招/未擊中", description = "", type = "boolean"},
	["floatingCombatTextEnergyGains"] = { prettyName = "FCT: 能量獲得", description = "", type = "boolean"},
	["floatingCombatTextFloatMode"] = { prettyName = "FCT: 浮動方式", description = "戰鬥文字的浮動方式", type = "number"},
	["floatingCombatTextFriendlyHealers"] = { prettyName = "FCT: 友方治療者名稱", description = "", type = "boolean"},
	["floatingCombatTextHonorGains"] = { prettyName = "FCT: 榮譽擊殺", description = "", type = "boolean"},
	["floatingCombatTextLowManaHealth"] = { prettyName = "FCT: 低法力和生命力", description = "", type = "boolean"},
	["floatingCombatTextPeriodicEnergyGains"] = { prettyName = "FCT: 週期性獲得能量", description = "", type = "boolean"},
	["floatingCombatTextPetMeleeDamage"] = { prettyName = "FCT: 寵物近戰傷害", description = "在遊戲畫面中顯示寵物近戰傷害", type = "boolean"},
	["floatingCombatTextPetSpellDamage"] = { prettyName = "FCT: 寵物技能傷害", description = "在遊戲畫面中顯示寵物法術技能傷害", type = "boolean"},
	["floatingCombatTextReactives"] = { prettyName = "FCT: Reactives", description = "", type = "boolean"},
	["floatingCombatTextRepChanges"] = { prettyName = "FCT: 聲望值變化", description = "", type = "boolean"},
	["floatingCombatTextSpellMechanics"] = { prettyName = "FCT: 法術效果", description = "", type = "boolean"},
	["floatingCombatTextSpellMechanicsOther"] = { prettyName = "FCT: 法術效果 (其他)", description = "", type = "boolean"},
	["statusText"] = { prettyName = "狀態文字", description = "是否要在狀態欄顯示生命力和法力數值", type = "boolean"},
	["violenceLevel"] = { prettyName = "暴力程度", description = "設定遊戲的暴力程度", type = "number"},
	["ffxGlow"] = { prettyName = "FFX 渲染", description = "全螢幕渲染特效", type = "boolean"},
	["releaseUITextures"] = { prettyName = "釋放 UI 材質", description = "預設釋放隱藏的 UI 材質", type = "boolean"},
	["alwaysCompareItems"] = { prettyName = "總是對比物品", description = "永遠顯示物品對比提示", type = "boolean"},
	["showSpenderFeedback"] = { prettyName= "顯示消耗反饋", description = "當在資源條消耗怒氣/法力/等等，顯示/隱藏閃光。", type = "boolean"},
	
	["lossOfControlFull"] = { prettyName = "失去控制: 全部", description = "設置失控警報的類型。 (0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["lossOfControlSilence"] = { prettyName = "失去控制: 沉默", description = "設置失控警報的類型。(0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["lossOfControlInterrupt"] = { prettyName = "失去控制: 中斷", description = "設置失控警報的類型。(0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["lossOfControlDisarm"] = { prettyName = "失去控制: 繳械", description = "設置失控警報的類型。(0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["lossOfControlRoot"] = { prettyName = "失去控制: 無法行動", description = "設置失控警報的類型。(0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
}
