local addonName, addon = ...
local _G = _G

-- luacheck: globals UIDropDownMenu_AddButton

addon.combatProtected = {
	-- List of cvars that can't be modified in combat
	["alwaysShowActionBars"] = true,
	["colorblindSimulator"] = true,
	["colorblindWeaknessFactor"] = true,
	["daltonize"] = true,
	["fullSizeFocusFrame"] = true,
	["garrisonCompleteTalent"] = true,
	["garrisonCompleteTalentType"] = true,
	["nameplateClassResourceTopInset"] = true,
	["nameplateGlobalScale"] = true,
	["NamePlateHorizontalScale"] = true,
	["nameplateLargeBottomInset"] = true,
	["nameplateLargerScale"] = true,
	["nameplateLargeTopInset"] = true,
	["nameplateMaxAlpha"] = true,
	["nameplateMaxAlphaDistance"] = true,
	["nameplateMaxDistance"] = true,
	["nameplateMaxScale"] = true,
	["nameplateMaxScaleDistance"] = true,
	["nameplateMinAlpha"] = true,
	["nameplateMinAlphaDistance"] = true,
	["nameplateMinScale"] = true,
	["nameplateMinScaleDistance"] = true,
	["nameplateMotion"] = true,
	["nameplateMotionSpeed"] = true,
	["nameplateOtherAtBase"] = true,
	["nameplateOtherBottomInset"] = true,
	["nameplateOtherTopInset"] = true,
	["nameplateOverlapH"] = true,
	["nameplateOverlapV"] = true,
	["NameplatePersonalHideDelayAlpha"] = true,
	["nameplatePersonalHideDelaySeconds"] = true,
	["nameplatePersonalShowAlways"] = true,
	["nameplatePersonalShowInCombat"] = true,
	["nameplatePersonalShowWithTarget"] = true,
	["nameplateResourceOnTarget"] = true,
	["nameplateSelectedAlpha"] = true,
	["nameplateSelectedScale"] = true,
	["nameplateSelfAlpha"] = true,
	["nameplateSelfBottomInset"] = true,
	["nameplateSelfScale"] = true,
	["nameplateSelfTopInset"] = true,
	["nameplateShowAll"] = true,
	["nameplateShowEnemies"] = true,
	["nameplateShowEnemyGuardians"] = true,
	["nameplateShowEnemyMinions"] = true,
	["nameplateShowEnemyMinus"] = true,
	["nameplateShowEnemyPets"] = true,
	["nameplateShowEnemyTotems"] = true,
	["nameplateShowFriendlyGuardians"] = true,
	["nameplateShowFriendlyMinions"] = true,
	["nameplateShowFriendlyNPCs"] = true,
	["nameplateShowFriendlyPets"] = true,
	["nameplateShowFriendlyTotems"] = true,
	["nameplateShowFriends"] = true,
	["nameplateShowSelf"] = true,
	["nameplateTargetBehindMaxDistance"] = true,
	["NamePlateVerticalScale"] = true,
	["showArenaEnemyFrames"] = true,
	["showArenaEnemyPets"] = true,
	["showPartyPets"] = true,
	["showTargetOfTarget"] = true,
	["splashScreenBoost"] = true,
	["splashScreenNormal"] = true,
	["targetOfTargetMode"] = true,
	["uiScale"] = true,
	["uiScaleMultiplier"] = true,
	["UnitNameGuildTitle"] = true,
	["useCompactPartyFrames"] = true,
	["useUiScale"] = true,
}

addon.hiddenOptions = {
	-- Names
	["UnitNameOwn"] = { prettyName = UNIT_NAME_OWN, description = OPTION_TOOLTIP_UNIT_NAME_OWN, type = "boolean" },
	["UnitNameNPC"] = { prettyName = UNIT_NAME_NPC, description = OPTION_TOOLTIP_UNIT_NAME_NPC, type = "boolean" },
	["UnitNameNonCombatCreatureName"] = { prettyName = UNIT_NAME_NONCOMBAT_CREATURE, description = OPTION_TOOLTIP_UNIT_NAME_NONCOMBAT_CREATURE, type = "boolean" },
	["UnitNamePlayerGuild"] = { prettyName = UNIT_NAME_GUILD, description = OPTION_TOOLTIP_UNIT_NAME_GUILD, type = "boolean" },
	["UnitNameGuildTitle"] = { prettyName = UNIT_NAME_GUILD_TITLE, description = OPTION_TOOLTIP_UNIT_NAME_GUILD_TITLE , type = "boolean" },
	["UnitNamePlayerPVPTitle"] = { prettyName = UNIT_NAME_PLAYER_TITLE, description = OPTION_TOOLTIP_UNIT_NAME_PLAYER_TITLE, type = "boolean" },
	["UnitNameFriendlyPlayerName"] = { prettyName = UNIT_NAME_FRIENDLY, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY, type = "boolean" },
	["UnitNameFriendlyPetName"] = { prettyName = UNIT_NAME_FRIENDLY_PETS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_PETS, type = "boolean" },
	["UnitNameFriendlyGuardianName"] = { prettyName = UNIT_NAME_FRIENDLY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_GUARDIANS, type = "boolean" },
	["UnitNameFriendlyTotemName"] = { prettyName = UNIT_NAME_FRIENDLY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_TOTEMS, type = "boolean" },
	["UnitNameFriendlyMinionName"] = { prettyName = UNIT_NAME_FRIENDLY_MINIONS, description = "", type = "boolean" },
	["UnitNameEnemyPlayerName"] = { prettyName = UNIT_NAME_ENEMY, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY, type = "boolean" },
	["UnitNameEnemyPetName"] = { prettyName = UNIT_NAME_ENEMY_PETS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_PETS, type = "boolean" },
	["UnitNameEnemyGuardianName"] = { prettyName = UNIT_NAME_ENEMY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_GUARDIANS, type = "boolean" },
	["UnitNameEnemyTotemName"] = { prettyName = UNIT_NAME_ENEMY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_TOTEMS, type = "boolean" },
	["UnitNameEnemyMinionName"] = { prettyName = UNIT_NAME_ENEMY_MINIONS, description = "", type = "boolean" },
	["UnitNameForceHideMinus"] = { prettyName = UNIT_NAME_HIDE_MINUS, description = OPTION_TOOLTIP_UNIT_NAME_HIDE_MINUS, type = "boolean" },
	["UnitNameFriendlySpecialNPCName"] = { prettyName = NPC_NAMES_DROPDOWN_TRACKED, description = NPC_NAMES_DROPDOWN_TRACKED_TOOLTIP, type = "boolean" },
	["UnitNameHostleNPC"] = { prettyName = "敵對 NPCs", description = "顯示敵對NPC的名稱", type = "boolean"},
	["UnitNameInteractiveNPC"] = { prettyName = "互動 NPCs", description = "顯示互動NPC的名稱", type = "boolean"},
	-- Nameplates
	["nameplateShowFriends"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDS, type = "boolean" },
	["nameplateShowFriendlyPets"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_PETS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_PETS, type = "boolean" },
	["nameplateShowFriendlyGuardians"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_GUARDIANS, type = "boolean" },
	["nameplateShowFriendlyTotems"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_TOTEMS, type = "boolean" },
	["nameplateShowFriendlyNPCs"] = { prettyName = "友方 NPCs", description = "總是顯示友方NPC的姓名版", type = "boolean" },
	["nameplateShowEnemies"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMIES, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMIES, type = "boolean" },
	["nameplateShowEnemyPets"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_PETS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_PETS, type = "boolean" },
	["nameplateShowEnemyGuardians"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_GUARDIANS, type = "boolean" },
	["nameplateShowEnemyTotems"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_TOTEMS, type = "boolean" },
	["nameplateShowEnemyMinus"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_MINUS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_MINUS, type = "boolean" },
	["nameplateOtherAtBase"] = { prettyName = "血條在下方", description = "將其他血條顯示在下方，而不是頭頂上。 2=單位下方, 0=單位上方", type = "boolean" },
	["nameplateOverlapH"] = { prettyName = "血條重疊(水平)", description = "血條的水平重疊百分比", type = "number" },
	["nameplateOverlapV"] = { prettyName = "血條重疊(垂直)", description = "血條的垂直重疊百分比", type = "number" },
	["nameplateMaxDistance"] = { prettyName = "血條距離", description = "顯示血條的最遠距離。", type = "number" },
	["nameplateTargetBehindMaxDistance"] = { prettyName = "Nameplate Target Behind Distance", description = "當目標在鏡頭之後目標血條顯示的最遠距離。", type = "number" },
	["nameplateGlobalScale"] = { prettyName = "血條通用縮放", description = "Applies global scaling to non-self nameplates, this is applied AFTER selected, min, and max scale.", type = "number" },
	["nameplateMinScale"] = { prettyName = "血條最小縮放", description = "血條最小縮放值。", type = "number" },
	["nameplateMaxScale"] = { prettyName = "血條最大縮放", description = "血條最大縮放值。", type = "number" },
	["nameplateLargerScale"] = { prettyName = "血條更大縮放", description = "一個額外的縮放變更在重要的怪物。", type = "number" },
	["nameplateMinScaleDistance"] = { prettyName = "血條最小縮放距離", description = "The distance from the max distance that nameplates will reach their minimum scale.", type = "number" },
	["nameplateMaxScaleDistance"] = { prettyName = "血條最大縮放距離", description = "The distance from the camera that nameplates will reach their maximum scale", type = "number" },
	["nameplateMinAlpha"] = { prettyName = "血條最低透明度", description = "The minimum alpha of nameplates.", type = "number" },
	["nameplateMaxAlpha"] = { prettyName = "血條最高透明度", description = "The max alpha of nameplates.", type = "number" },
	["nameplateMinAlphaDistance"] = { prettyName = "血條最低透明度距離", description = "The distance from the max distance that nameplates will reach their minimum alpha.", type = "number" },
	["nameplateMaxAlphaDistance"] = { prettyName = "血條最高透明度距離", description = "The distance from the camera that nameplates will reach their maximum alpha.", type = "number" },
	["nameplateSelectedScale"] = { prettyName = "選擇的血條縮放", description = "The scale of the selected nameplate.", type = "number" },
	["nameplateSelectedAlpha"] = { prettyName = "選擇的血條透明度", description = "The alpha of the selected nameplate.", type = "number" },
	["nameplateSelfScale"] = { prettyName = "自我血條縮放", description = "The scale of the self nameplate.", type = "number" },
	["nameplateSelfAlpha"] = { prettyName = "自我血條透明度", description = "The alpha of the self nameplate.", type = "number" },
	["nameplateSelfBottomInset"] = { prettyName = "自我血條置底", description = "嵌置在螢幕底部 (螢幕百分比) 。", type = "number" },
	["nameplateSelfTopInset"] = { prettyName = "自我血條置頂", description = "嵌置在螢幕頂部 (螢幕百分比) 。", type = "number" },
	["nameplateOtherBottomInset"] = { prettyName = "其他血條置底", description = "其他血條嵌置在螢幕底部 (螢幕百分比) 。", type = "number" },
	["nameplateOtherTopInset"] = { prettyName = "其他血條置頂", description = "其他血條嵌置在螢幕頂部 (螢幕百分比) 。", type = "number" },
	["nameplateLargeBottomInset"] = { prettyName = "大血條置底", description = "大血條嵌置在螢幕底部 (螢幕百分比) 。", type = "number" },
	["nameplateLargeTopInset"] = { prettyName = "大血條置頂", description = "大血條嵌置在螢幕頂部 (螢幕百分比) 。", type = "number" },
	["nameplateClassResourceTopInset"] = { prettyName = "血條職業資源置頂", description = "當職業資源顯示時嵌置在螢幕頂部 (螢幕百分比) 。", type = "number" },
	["NamePlateHorizontalScale"] = { prettyName = "血條水平縮放", description = "套用在所有血條的水平大小。", type = "number" },
	["NamePlateVerticalScale"] = { prettyName = "血條垂直縮放", description = "套用在所有血條的垂直大小。", type = "number" },
	["nameplateResourceOnTarget"] = { prettyName = "目標血條資源", description = "血條職業資源覆蓋模式。 0=自己, 1=目標", type = "number" },
	["nameplateShowSelf"] = { prettyName = "顯示血條資源條", description = "顯示職業資源條 0=off 1=on", type = "number" },
	["nameplateShowAll"] = { prettyName = "永遠顯示血條", description = "不管何時永遠顯示血條。", type = "number" },
	["nameplateMotion"] = { prettyName = "血條動態類型", description = "0 = 重疊 - 1 = 堆疊 - 2 = 分散", type = "number" },
	["namePlateFriendlySize"] = { prettyName = "", description = "", type = "number"},
	["namePlateEnemySize"] = { prettyName = "", description = "", type = "number"},
	["namePlateSelfClickThrough"] = { prettyName = "", description = "", type = "number"},
	["namePlateFriendlyClickThrough"] = { prettyName = "", description = "", type = "number"},
	["namePlateEnemyClickThrough"] = { prettyName = "", description = "", type = "number"},
	["nameplatePersonalShowAlways"] = { prettyName = "", description = "總是顯示個人姓名版", type = "boolean" },
	["nameplatePersonalShowInCombat"] = { prettyName = "", description = "在戰鬥中總是顯示個人姓名版", type = "boolean" },
	["nameplatePersonalShowWithTarget"] = { prettyName = "", description = "有敵對目標時總是顯示個人姓名版", type = "boolean" },
	["nameplatePersonalHideDelaySeconds"] = { prettyName = "", description = "在隱藏個人姓名版前等待的延遲", type = "boolean" },
	["ShowNamePlateLoseAggroFlash"] = { prettyName = nil, description = "啟用後，如果你是坦克並且失去仇恨，姓名版會短暫閃爍。", type = "boolean"},
	["ShowClassColorInNameplate"] = { prettyName = SHOW_CLASS_COLOR_IN_V_KEY, description = OPTION_TOOLTIP_SHOW_CLASS_COLOR_IN_V_KEY, type = "boolean" },
	["ShowClassColorInFriendlyNameplate"] = { prettyName = "職業著色友方名條", description = "Class color for friendly nameplates", type = "boolean" },
	["nameplateTargetRadialPosition"] = { prettyName = nil, description = "當目標超出螢幕，將其姓名版逕自放在側面或底部", type = "number"},
	["nameplateOccludedAlphaMult"] = { prettyName = nil, description = "用於閉塞目標的姓名版的透明度乘數", type = "number"},


	["reverseCleanupBags"] = { prettyName = REVERSE_CLEAN_UP_BAGS_TEXT, description = OPTION_TOOLTIP_REVERSE_CLEAN_UP_BAGS, type = "boolean" },
	["lootLeftmostBag"] = { prettyName = REVERSE_NEW_LOOT_TEXT, description = OPTION_TOOLTIP_REVERSE_NEW_LOOT, type = "boolean" },
	["stopAutoAttackOnTargetChange"] = { prettyName = STOP_AUTO_ATTACK, description = OPTION_TOOLTIP_STOP_AUTO_ATTACK, type = "boolean" },
	["assistAttack"] = { prettyName = ASSIST_ATTACK, description = OPTION_TOOLTIP_ASSIST_ATTACK, type = "boolean" },
	["autoSelfCast"] = { prettyName = AUTO_SELF_CAST_TEXT, description = OPTION_TOOLTIP_SELF_CAST_TEXT, type = "boolean" },
	["ActionButtonUseKeyDown"] = { prettyName = ACTION_BUTTON_USE_KEY_DOWN, description = OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN, type = "boolean" },
	["mapFade"] = { prettyName = MAP_FADE_TEXT, description = OPTION_TOOLTIP_MAP_FADE, type = "boolean" },
	["trackQuestSorting"] = { type = "table", options = {"proximity", "top" } },
	["removeChatDelay"] = { prettyName = REMOVE_CHAT_DELAY_TEXT, description = OPTION_TOOLTIP_REMOVE_CHAT_DELAY_TEXT, type = "boolean" },
	["secureAbilityToggle"] = { prettyName = SECURE_ABILITY_TOGGLE, description = OPTION_TOOLTIP_SECURE_ABILITY_TOGGLE, type = "boolean" },
	["scriptErrors"] = { prettyName = SHOW_LUA_ERRORS, description = OPTION_TOOLTIP_SHOW_LUA_ERRORS, type = "boolean" },
	["lootUnderMouse"] = { prettyName = LOOT_UNDER_MOUSE_TEXT, description = OPTION_TOOLTIP_LOOT_UNDER_MOUSE_TEXT, type = "boolean" },
	["ShowQuestUnitCircles"] = { prettyName = "任務單位圓圈", description = "確定與任務相關的單位是否在地面上顯示指標", type = "boolean"},
	["autoLootDefault"] = { prettyName = AUTO_LOOT_DEFAULT_TEXT, description = OPTION_TOOLTIP_AUTO_LOOT_DEFAULT, type = "boolean" },
	["threatShowNumeric"] = { prettyName = SHOW_NUMERIC_THREAT, description = OPTION_TOOLTIP_SHOW_NUMERIC_THREAT, type = "boolean" },
	["showLootSpam"] = { prettyName = SHOW_LOOT_SPAM, description = OPTION_TOOLTIP_SHOW_LOOT_SPAM, type = "boolean" },
	["advancedWatchFrame"] = { prettyName = ADVANCED_OBJECTIVES_TEXT, description = OPTION_TOOLTIP_ADVANCED_OBJECTIVES_TEXT, type = "" },
	["watchFrameIgnoreCursor"] = { prettyName = OBJECTIVES_IGNORE_CURSOR_TEXT, description = OPTION_TOOLTIP_OBJECTIVES_IGNORE_CURSOR, type = "boolean" },
	["guildMemberNotify"] = { prettyName = GUILDMEMBER_ALERT, description = OPTION_TOOLTIP_GUILDMEMBER_ALERT, type = "boolean" },
	["showArenaEnemyFrames"] = { prettyName = SHOW_ARENA_ENEMY_FRAMES_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_FRAMES, type = "boolean" },
	["autoClearAFK"] = { prettyName = nil, description = OPTION_TOOLTIP_CLEAR_AFK, type = "boolean" },
	["colorblindWeaknessFactor"] = { prettyName = nil, description = OPTION_TOOLTIP_ADJUST_COLORBLIND_STRENGTH, type = "boolean" },
	["autoLootDefault"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_LOOT_DEFAULT, type = "boolean" },
	["autoLootRate"] = { prettyName = "自動拾取速度", description = "自動拾取的速度 (毫秒)", type = "number" },
	["ChatAmbienceVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_, type = "boolean" },
	["threatShowNumeric"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_NUMERIC_THREAT, type = "boolean" },
	["rightActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR3, type = "boolean" },
	["emphasizeMySpellEffects"] = { prettyName = nil, description = OPTION_TOOLTIP_EMPHASIZE_MY_SPELLS, type = "boolean" },
	["chatBubblesParty"] = { prettyName = nil, description = OPTION_TOOLTIP_PARTY_CHAT_BUBBLES, type = "boolean" },
	["enableTwitter"] = { prettyName = nil, description = OPTION_TOOLTIP_SOCIAL_ENABLE_TWITTER_FUNCTIONALITY, type = "boolean" },
	["threatPlaySounds"] = { prettyName = nil, description = OPTION_TOOLTIP_PLAY_AGGRO_SOUNDS, type = "boolean" },
	-- Toasts mmhhh...Toast.
	["showToastOnline"] = { prettyName = SHOW_TOAST_ONLINE_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_ONLINE, type = "boolean" },
	["showToastOffline"] = { prettyName = SHOW_TOAST_OFFLINE_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_OFFLINE, type = "boolean" },
	["showToastBroadcast"] = { prettyName = SHOW_TOAST_BROADCAST_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_BROADCAST, type = "boolean" },
	["showToastFriendRequest"] = { prettyName = SHOW_TOAST_FRIEND_REQUEST_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_FRIEND_REQUEST, type = "boolean" },
	["showToastConversation"] = { prettyName = SHOW_TOAST_CONVERSATION_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_CONVERSATION, type = "boolean" },
	["showToastWindow"] = { prettyName = SHOW_TOAST_WINDOW_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_WINDOW, type = "boolean" },
	["toastDuration"] = { prettyName = nil, description = OPTION_TOOLTIP_TOAST_DURATION, type = "number" },

	["enableMouseSpeed"] = { prettyName = ENABLE_MOUSE_SPEED, description = OPTION_TOOLTIP_ENABLE_MOUSE_SPEED, type = "boolean" },
	["mouseInvertPitch"] = { prettyName = INVERT_MOUSE, description = OPTION_TOOLTIP_INVERT_MOUSE, type = "boolean" },
	["enableWoWMouse"] = { prettyName = WOW_MOUSE, description = OPTION_TOOLTIP_WOW_MOUSE, type = "boolean" },
	["autointeract"] = { prettyName = CLICK_TO_MOVE, description = OPTION_TOOLTIP_CLICK_TO_MOVE, type = "boolean" },
	["mouseSpeed"] = { prettyName = MOUSE_SENSITIVITY, description = OPTION_TOOLTIP_MOUSE_SENSITIVITY, type = "number" },

	["wholeChatWindowClickable"] = { prettyName = nil, description = OPTION_TOOLTIP_CHAT_WHOLE_WINDOW_CLICKABLE, type = "boolean" },
	["useEnglishAudio"] = { prettyName = nil, description = OPTION_TOOLTIP_USE_ENGLISH_AUDIO, type = "boolean" },
	["ChatSoundVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_, type = "number" },
	--["reducedLagTolerance"] = { prettyName = "Custom Lag Tolerance", description = OPTION_TOOLTIP_REDUCED_LAG_TOLERANCE, type = "boolean" },
	["EnableMicrophone"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_MICROPHONE, type = "boolean" },
	["autoOpenLootHistory"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_OPEN_LOOT_HISTORY, type = "boolean" },
	["showVKeyCastbarOnlyOnTarget"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY_ONLY_ON_TARGET, type = "boolean" },
	["displaySpellActivationOverlays"] = { prettyName = nil, description = OPTION_TOOLTIP_DISPLAY_SPELL_ALERTS, type = "boolean" },
	["hdPlayerModels"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_HD_MODELS, type = "boolean" },
	["autoLootKey"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_LOOT_KEY, type = "boolean" }, -- TODO TYPE
	["SpellQueueWindow"] = { prettyName = LAG_TOLERANCE, description = "Determines how far ahead of the \'end of a spell\' start-recovery spell system can be, before allowing spell request to be sent to the server. Ie this controls the built-in lag for the ability queuing system. Ideally, you\'ll want to set this to your in-game latency.", type = "number" },
	["advancedCombatLogging"] = { prettyName = nil, description = OPTION_TOOLTIP_ADVANCED_COMBAT_LOGGING, type = "boolean" },
	["disableServerNagle"] = { prettyName = nil, description = OPTION_TOOLTIP_OPTIMIZE_NETWORK_SPEED, type = "boolean" },
	-- Camera
	["cameraYawSmoothSpeed"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_FOLLOW_SPEED, type = "number" },
	["cameraWaterCollision"] = { prettyName = nil, description = OPTION_TOOLTIP_WATER_COLLISION, type = "boolean" },
	["cameraBobbing"] = { prettyName = nil, description = OPTION_TOOLTIP_HEAD_BOB, type = "boolean" },
	["cameraPivot"] = { prettyName = nil, description = OPTION_TOOLTIP_SMART_PIVOT, type = "boolean" },
	["cameraDistanceMaxZoomFactor"] = { prettyName = MAX_FOLLOW_DIST, description = OPTION_TOOLTIP_MAX_FOLLOW_DIST, type = "number" },
	["cameraYawMoveSpeed"] = { prettyName = MOUSE_LOOK_SPEED, description = OPTION_TOOLTIP_MOUSE_LOOK_SPEED, type = "number" },
	["cameraTerrainTilt"] = { prettyName = nil, description = OPTION_TOOLTIP_FOLLOW_TERRAIN, type = "boolean" },
	["cameraHeadMovementStrength"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementWhileStanding"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementRange"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementSmoothRate"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitch"] = { prettyName = nil, description = nil, type = "number" },
	-- ["cameraDynamicPitchBaseFovPad"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitchBaseFovPadFlying"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitchSmartPivotCutoffDist"] = { prettyName = nil, description = nil, type = "number" },
	["cameraOverShoulder"] = { prettyName = nil, description = nil, type = "number" },
	["cameraLockedTargetFocusing"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDistanceMoveSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraPitchMoveSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraBobbingSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraFoVSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDistanceSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraGroundSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeightSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraPitchSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraTargetSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	-- ["cameraFlyingMountHeightSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraViewBlendStyle"] = { prettyName = nil, description = nil, type = "number" },
	["camerasmooth"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothPitch"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothYaw"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothStyle"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothTrackingStyle"] = { prettyName = nil, description = nil, type = "number" },

	["chatBubbles"] = { prettyName = nil, description = OPTION_TOOLTIP_CHAT_BUBBLES, type = "boolean" },
	["autoDismountFlying"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_DISMOUNT_FLYING, type = "boolean" },
	["bottomRightActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR2, type = "boolean" },
	["showPartyBackground"] = { prettyName = SHOW_PARTY_BACKGROUND_TEXT, description = OPTION_TOOLTIP_SHOW_PARTY_BACKGROUND, type = "boolean" },
	["showPartyPets"] = { prettyName = SHOW_PARTY_PETS_TEXT, description = OPTION_TOOLTIP_SHOW_PARTY_PETS, type = "boolean" },
	["showArenaEnemyFrames"] = { prettyName = SHOW_ARENA_ENEMY_FRAMES_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_FRAMES, type = "boolean" },
	["showArenaEnemyCastbar"] = { prettyName = SHOW_ARENA_ENEMY_CASTBAR_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_CASTBAR, type = "boolean" },
	["showArenaEnemyPets"] = { prettyName = SHOW_ARENA_ENEMY_PETS_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_PETS, type = "boolean" },
	["fullSizeFocusFrame"] = { prettyName = FULL_SIZE_FOCUS_FRAME_TEXT, description = OPTION_TOOLTIP_FULL_SIZE_FOCUS_FRAME, type = "boolean" },
	["spamFilter"] = { prettyName = nil, description = OPTION_TOOLTIP_SPAM_FILTER, type = "boolean" },
	["profanityFilter"] = { prettyName = nil, description = OPTION_TOOLTIP_PROFANITY_FILTER, type = "boolean" },
	["EnableVoiceChat"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_VOICECHAT, type = "boolean" },
	["rightTwoActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR4, type = "boolean" },
	["rotateMinimap"] = { prettyName = nil, description = OPTION_TOOLTIP_ROTATE_MINIMAP, type = "boolean" },
	["blockTrades"] = { prettyName = nil, description = OPTION_TOOLTIP_BLOCK_TRADES, type = "boolean" },
	["movieSubtitle"] = { prettyName = nil, description = OPTION_TOOLTIP_CINEMATIC_SUBTITLES, type = "boolean" },
	["displayFreeBagSlots"] = { prettyName = nil, description = OPTION_TOOLTIP_DISPLAY_FREE_BAG_SLOTS, type = "boolean" },
	["lockActionBars"] = { prettyName = nil, description = OPTION_TOOLTIP_LOCK_ACTIONBAR, type = "boolean" },
	["screenEdgeFlash"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_FULLSCREEN_STATUS, type = "boolean" },
	["showVKeyCastbar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY, type = "boolean" },
	["chatMouseScroll"] = { prettyName = CHAT_MOUSE_WHEEL_SCROLL, description = OPTION_TOOLTIP_CHAT_MOUSE_WHEEL_SCROLL, type = "boolean" },
	["InboundChatVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_OUTPUT_VOLUME, type = "number" },
	["spellActivationOverlayOpacity"] = { prettyName = nil, description = OPTION_TOOLTIP_SPELL_ALERT_OPACITY, type = "number" },
	["PushToTalkSound"] = { prettyName = nil, description = OPTION_TOOLTIP_PUSHTOTALK_SOUND, type = "boolean" },
	["countdownForCooldowns"] = { prettyName = nil, description = OPTION_TOOLTIP_COUNTDOWN_FOR_COOLDOWNS, type = "boolean" },
	["VoiceActivationSensitivity"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_ACTIVATION_SENSITIVITY, type = "number" },
	["alwaysShowActionBars"] = { prettyName = nil, description = OPTION_TOOLTIP_ALWAYS_SHOW_MULTIBARS, type = "boolean" },
	["OutboundChatVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_INPUT_VOLUME, type = "number" },
	["autoQuestWatch"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_QUEST_WATCH, type = "boolean" },
	["SpellTooltip_DisplayAvgValues"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_POINTS_AS_AVG, type = "boolean" },
	["bottomLeftActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR1, type = "boolean" },
	["showVKeyCastbarSpellName"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY_SPELL_NAME, type = "boolean" },
	["buffDurations"] = { prettyName = SHOW_BUFF_DURATION_TEXT, description = OPTION_TOOLTIP_SHOW_BUFF_DURATION, type = "boolean" },
	["showDispelDebuffs"] = { prettyName = SHOW_DISPELLABLE_DEBUFFS_TEXT, description = OPTION_TOOLTIP_SHOW_DISPELLABLE_DEBUFFS, type = "boolean" },
	["showCastableBuffs"] = { prettyName = SHOW_CASTABLE_BUFFS_TEXT, description = OPTION_TOOLTIP_SHOW_CASTABLE_BUFFS, type = "boolean" },
	["deselectOnClick"] = { prettyName = nil, description = OPTION_TOOLTIP_GAMEFIELD_DESELECT, type = "boolean" },
	["autoQuestProgress"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_QUEST_PROGRESS, type = "boolean" },
	["UberTooltips"] = { prettyName = USE_UBERTOOLTIPS, description = OPTION_TOOLTIP_USE_UBERTOOLTIPS, type = "boolean" },
	-- Sound
	["Sound_EnableAllSound"] = { prettyName = ENABLE_SOUND, description = OPTION_TOOLTIP_ENABLE_SOUND, type = "boolean" },
	["Sound_EnableDSPEffects"] = { prettyName = ENABLE_DSP_EFFECTS, description = OPTION_TOOLTIP_ENABLE_DSP_EFFECTS, type = "boolean" },
	["Sound_SFXVolume"] = { prettyName = SOUND_VOLUME, description = OPTION_TOOLTIP_SOUND_VOLUME, type = "number" },
	["Sound_ZoneMusicNoDelay"] = { prettyName = ENABLE_MUSIC_LOOPING, description = OPTION_TOOLTIP_ENABLE_MUSIC_LOOPING, type = "boolean" },
	["Sound_EnableDialog"] = { prettyName = ENABLE_DIALOG, description = OPTION_TOOLTIP_ENABLE_DIALOG, type = "boolean" },
	["Sound_EnableSoundWhenGameIsInBG"] = { prettyName = ENABLE_BGSOUND, description = OPTION_TOOLTIP_ENABLE_BGSOUND, type = "boolean" },
	["Sound_EnableEmoteSounds"] = { prettyName = ENABLE_EMOTE_SOUNDS, description = OPTION_TOOLTIP_ENABLE_EMOTE_SOUNDS, type = "boolean" },
	["Sound_EnableAmbience"] = { prettyName = ENABLE_AMBIENCE, description = OPTION_TOOLTIP_ENABLE_AMBIENCE, type = "boolean" },
	["Sound_DialogVolume"] = { prettyName = DIALOG_VOLUME, description = OPTION_TOOLTIP_DIALOG_VOLUME, type = "number" },
	["Sound_EnablePetBattleMusic"] = { prettyName = ENABLE_PET_BATTLE_MUSIC, description = OPTION_TOOLTIP_ENABLE_PET_BATTLE_MUSIC, type = "boolean" },
	["Sound_MusicVolume"] = { prettyName = MUSIC_VOLUME, description = OPTION_TOOLTIP_MUSIC_VOLUME, type = "number" },
	["Sound_EnableReverb"] = { prettyName = ENABLE_REVERB, description = OPTION_TOOLTIP_ENABLE_REVERB, type = "boolean" },
	["Sound_MasterVolume"] = { prettyName = MASTER_VOLUME, description = OPTION_TOOLTIP_MASTER_VOLUME, type = "number" },
	["Sound_EnableMusic"] = { prettyName = ENABLE_MUSIC, description = OPTION_TOOLTIP_ENABLE_MUSIC, type = "boolean" },
	["Sound_AmbienceVolume"] = { prettyName = AMBIENCE_VOLUME, description = OPTION_TOOLTIP_AMBIENCE_VOLUME, type = "number" },
	["Sound_EnableErrorSpeech"] = { prettyName = ENABLE_ERROR_SPEECH, description = OPTION_TOOLTIP_ENABLE_ERROR_SPEECH, type = "boolean" },
	["Sound_EnableSFX"] = { prettyName = ENABLE_SOUNDFX, description = OPTION_TOOLTIP_ENABLE_SOUNDFX, type = "boolean" },
	["Sound_ListenerAtCharacter"] = { prettyName = ENABLE_SOUND_AT_CHARACTER, description = OPTION_TOOLTIP_ENABLE_SOUND_AT_CHARACTER, type = "boolean" },
	["Sound_EnablePetSounds"] = { prettyName = ENABLE_PET_SOUNDS, description = OPTION_TOOLTIP_ENABLE_PET_SOUNDS, type = "boolean" },
	["Sound_EnablePositionalLowPassFilter"] = { prettyName = ENABLE_SOFTWARE_HRTF, description = OPTION_TOOLTIP_ENABLE_SOFTWARE_HRTF, type = "boolean" },

	["showTargetOfTarget"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_OF_TARGET, type = "boolean" },
	["guildMemberNotify"] = { prettyName = nil, description = OPTION_TOOLTIP_GUILDMEMBER_ALERT, type = "boolean" },
	["showTutorials"] = { prettyName = SHOW_TUTORIALS, description = OPTION_TOOLTIP_SHOW_TUTORIALS, type = "boolean" },
	["lossOfControl"] = { prettyName = nil, description = OPTION_TOOLTIP_LOSS_OF_CONTROL, type = "boolean" },
	["blockChannelInvites"] = { prettyName = nil, description = OPTION_TOOLTIP_BLOCK_CHAT_CHANNEL_INVITE, type = "boolean" },
	["showTargetCastbar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR, type = "boolean" },
	["enablePetBattleCombatText"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_PETBATTLE_COMBAT, type = "boolean" },
	["colorblindMode"] = { prettyName = nil, description = OPTION_TOOLTIP_USE_COLORBLIND_MODE, type = "boolean" },
	["useIPv6"] = { prettyName = USEIPV6, description = OPTION_TOOLTIP_USEIPV6, type = "boolean" },
	["interactOnLeftClick"] = { prettyName = INTERACT_ON_LEFT_CLICK_TEXT, description = OPTION_TOOLTIP_INTERACT_ON_LEFT_CLICK, type = "boolean" },
	["enableMovePad"] = { prettyName = MOVE_PAD, description = OPTION_TOOLTIP_MOVE_PAD, type = "boolean" },
	["colorblindSimulator"] = { prettyName = nil, description = OPTION_TOOLTIP_COLORBLIND_FILTER, type = "boolean" },

	["noBuffDebuffFilterOnTarget"] = { prettyName = "不要過濾目標的光環", description = "不要過濾所有目標身上的增益和減益效果", type = "boolean"},
	["showHonorAsExperience"] = { prettyName = nil, description = "將榮譽條顯示為一般的經驗條，顯示在聲望條的位置。", type = "boolean"},
	-- Tab-Targetting
	["TargetNearestUseNew"] = { prettyName = nil, description = "使用 7.2 版新的 '最接近目標' 功能", type = "boolean" },
	--["TargetPriorityAllowAnyOnScreen"] = { prettyName = nil, description = "If set, and no 100% correct target is available, allow selecting any valid in-range target (2 = also out-of-range)", type = "boolean" },
	["TargetPriorityCombatLock"] = { prettyName = nil, description = "1=Lock to in-combat targets when starting from an in-combat target. 2=Further restrict to in-combat with player.", type = "boolean" },
	["TargetPriorityCombatLockHighlight"] = { prettyName = nil, description = "1=Lock to in-combat targets when starting from an in-combat target. 2=Further restrict to in-combat with player. (while doing hold-to-target)", type = "boolean" },
	--["TargetPriorityHoldHighlightDelay"] = { prettyName = nil, description = "Delay in Milliseconds before priority target highlight starts when holding the button", type = "number" },
	--["TargetPriorityIncludeBehind"] = { prettyName = nil, description = "If set, include target's behind the player in priority target selection", type = "boolean" },
	["TargetPriorityPvp"] = { prettyName = nil, description = "When in pvp, give higher priority to players and important pvp targets (2 = all pvp targets, 3 = players only)", type = "boolean" },
	--["TargetPriorityPvpLock"] = { prettyName = nil, description = "Lock to important pvp targets when starting from a pvp target.", type = "boolean" },
	--["TargetPriorityPvpLockHighlight"] = { prettyName = nil, description = "Lock to players when starting from a player target in pvp. (while doing hold-to-target)", type = "boolean" },
	--["TargetPriorityValueBank"] = { prettyName = nil, description = "Selects the scoring values bank for calculating target priority order", type = "boolean" },
	["TargetPriorityCombatLockContextualRelaxation"] = { prettyName = nil, description = "1=Enables relaxation of combat lock based on context (eg. no in-combat target infront)", type = "number" },

	["unitClutter"] = { prettyName = nil, description = "啟用/停用 單位堆疊", type = "boolean"},
	["unitClutterInstancesOnly"] = { prettyName = nil, description = "是否使用單位堆疊 只在副本中 (0 or 1)", type = "boolean"},
	["unitClutterPlayerThreshold"] = { prettyName = nil, description = "在附近觸發單位堆疊的玩家數量", type = "boolean"},

	["comboPointLocation"] = { prettyName = nil, description = "連擊點數在UI中的位置。 1 = 目標, 2 = 自己", type = "number"},
	["doNotFlashLowHealthWarning"] = { prettyName = nil, description = "低生命力時不要在整個畫面上閃爍紅色。", type = "boolean"},
	["findYourselfAnywhere"] = { prettyName = nil, description = "總是保持顯著標示你的角色", type = "boolean"},
	["findYourselfAnywhereOnlyInCombat"] = { prettyName = nil, description = "只在戰鬥中顯著標示你的角色", type = "boolean"},
	["findYourselfInBG"] = { prettyName = nil, description = "在戰場時總是保持顯著標示你的角色", type = "boolean"},
	["findYourselfInBGOnlyInCombat"] = { prettyName = "在戰場時只在戰鬥中顯著標示你的角色", description = "", type = "boolean"},
	["findYourselfInRaid"] = { prettyName = nil, description = "在團隊時總是保持顯著標示你的角色", type = "boolean"},
	["findYourselfInRaidOnlyInCombat"] = { prettyName = nil, description = "在團隊時只在戰鬥中顯著標示你的角色", type = "boolean"},
	["findYourselfMode"] = { prettyName = nil, description = "顯示標示你的角色。 0 = 圓圈, 1 = 圓圈和外框", type = "boolean"},
	["flashErrorMessageRepeats"] = { prettyName = nil, description = "再次出現相同的訊息時，閃爍畫面中央的紅色錯誤文字。", type = "boolean"},
	-- Floating Combat Text
	["enableFloatingCombatText"] = { prettyName = "啟用浮動戰鬥文字", description = "是否要顯示浮動戰鬥文字", type = "boolean"},
	["floatingCombatTextAllSpellMechanics"] = { prettyName = nil, description = "", type = "boolean"},
	["floatingCombatTextAuras"] = { prettyName = COMBAT_TEXT_SHOW_AURAS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_AURAS , type = "boolean"},
	["floatingCombatTextCombatDamage"] = { prettyName = SHOW_DAMAGE_TEXT, description = OPTION_TOOLTIP_SHOW_DAMAGE, type = "boolean"},
	["floatingCombatTextCombatDamageAllAutos"] = { prettyName = nil, description = "顯示所有自動攻擊的數字，不要隱藏非玩家按下技能的數字。", type = "boolean"},
	["floatingCombatTextCombatDamageDirectionalOffset"] = { prettyName = nil, description = "多方向傷害數字出現時偏移的數量", type = "boolean"},
	["floatingCombatTextCombatDamageDirectionalScale"] = { prettyName = "FCT: 多方向顯示數字", description = "不同大小的傷害數字會往不同的方向顯示 (0 = 不要使用多方向顯示數字)", type = "boolean"},
	["floatingCombatTextCombatHealing"] = { prettyName = SHOW_COMBAT_HEALING, description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING, type = "boolean"},
	["floatingCombatTextCombatHealingAbsorbSelf"] = { prettyName = SHOW_COMBAT_HEALING_ABSORB_SELF.." (自己)", description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING_ABSORB_SELF, type = "boolean"},
	["floatingCombatTextCombatHealingAbsorbTarget"] = { prettyName = SHOW_COMBAT_HEALING_ABSORB_TARGET.." (目標)" , description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING_ABSORB_TARGET, type = "boolean"},
	["floatingCombatTextCombatLogPeriodicSpells"] = { prettyName = LOG_PERIODIC_EFFECTS, description = OPTION_TOOLTIP_LOG_PERIODIC_EFFECTS, type = "boolean" },
	["floatingCombatTextCombatState"] = { prettyName = COMBAT_TEXT_SHOW_COMBAT_STATE_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_COMBAT_STATE, type = "boolean" },
	["floatingCombatTextComboPoints"] = { prettyName = COMBAT_TEXT_SHOW_COMBO_POINTS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_COMBO_POINTS , type = "boolean" },
	["floatingCombatTextDamageReduction"] = { prettyName =COMBAT_TEXT_SHOW_RESISTANCES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_RESISTANCES, type = "boolean" },
	["floatingCombatTextDodgeParryMiss"] = { prettyName = COMBAT_TEXT_SHOW_DODGE_PARRY_MISS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_DODGE_PARRY_MISS, type = "boolean" },
	["floatingCombatTextEnergyGains"] = { prettyName = COMBAT_TEXT_SHOW_ENERGIZE_TEXT.." & "..COMBAT_TEXT_SHOW_COMBO_POINTS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_ENERGIZE, type = "boolean" },
	["floatingCombatTextFloatMode"] = { prettyName = COMBAT_TEXT_FLOAT_MODE_LABEL, description = OPTION_TOOLTIP_COMBAT_TEXT_MODE, type = "number" },
	["floatingCombatTextFriendlyHealers"] = { prettyName = COMBAT_TEXT_SHOW_FRIENDLY_NAMES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_FRIENDLY_NAMES, type = "boolean" },
	["floatingCombatTextHonorGains"] = { prettyName = COMBAT_TEXT_SHOW_HONOR_GAINED_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_HONOR_GAINED, type = "boolean" },
	["floatingCombatTextLowManaHealth"] = { prettyName = COMBAT_TEXT_SHOW_LOW_HEALTH_MANA_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_LOW_HEALTH_MANA, type = "boolean" },
	["floatingCombatTextPeriodicEnergyGains"] = { prettyName = COMBAT_TEXT_SHOW_PERIODIC_ENERGIZE_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_PERIODIC_ENERGIZE, type = "boolean" },
	["floatingCombatTextPetMeleeDamage"] = { prettyName = SHOW_PET_MELEE_DAMAGE, description = OPTION_TOOLTIP_SHOW_PET_MELEE_DAMAGE, type = "boolean" },
	["floatingCombatTextPetSpellDamage"] = { prettyName = SHOW_PET_SPELL_DAMAGE, description = "在遊戲畫面中顯示寵物法術技能傷害", type = "boolean" },
	["floatingCombatTextReactives"] = { prettyName = COMBAT_TEXT_SHOW_REACTIVES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_REACTIVES, type = "boolean" },
	["floatingCombatTextRepChanges"] = { prettyName = COMBAT_TEXT_SHOW_REPUTATION_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_REPUTATION, type = "boolean" },
	["floatingCombatTextSpellMechanics"] = { prettyName = SHOW_TARGET_EFFECTS, description = OPTION_TOOLTIP_SHOW_TARGET_EFFECTS, type = "boolean" },
	["floatingCombatTextSpellMechanicsOther"] = { prettyName = SHOW_OTHER_TARGET_EFFECTS, description = OPTION_TOOLTIP_SHOW_OTHER_TARGET_EFFECTS, type = "boolean" },
	-- Status Text
	["statusText"] = { prettyName = STATUS_TEXT, description = "是否要在狀態欄顯示生命力和法力數值", type = "boolean"},
	["statusTextDisplay"] = { prettyName = STATUS_TEXT, description = OPTION_TOOLTIP_STATUS_TEXT_DISPLAY, type = "boolean"},
	["playerStatusText"] = { prettyName = STATUS_TEXT_PLAYER, description = OPTION_TOOLTIP_STATUS_TEXT_PLAYER , type = "boolean"}, -- removed
	["petStatusText"] = { prettyName = STATUS_TEXT_PET, description = OPTION_TOOLTIP_STATUS_TEXT_PET, type = "boolean"}, -- removed
	["partyStatusText"] = { prettyName = STATUS_TEXT_PARTY, description = OPTION_TOOLTIP_STATUS_TEXT_PARTY, type = "boolean"}, -- removed
	["targetStatusText"] = { prettyName = STATUS_TEXT_TARGET, description = OPTION_TOOLTIP_STATUS_TEXT_TARGET, type = "boolean"}, -- removed
	["alternateResourceText"] = { prettyName = ALTERNATE_RESOURCE_TEXT, description = OPTION_TOOLTIP_ALTERNATE_RESOURCE, type = "boolean"}, -- removed
	["xpBarText"] = { prettyName = XP_BAR_TEXT, description = OPTION_TOOLTIP_XP_BAR, type = "boolean" },

	["violenceLevel"] = { prettyName = "暴力程度", description = "設定遊戲的暴力程度", type = "number" },
	["ffxGlow"] = { prettyName = "FFX 渲染", description = "全螢幕渲染特效", type = "boolean" },
	["ffxNether"] = { prettyName = "FFX Nether", description = "full screen nether / glow effect", type = "boolean" },
	["releaseUITextures"] = { prettyName = "釋放 UI 材質", description = "預設釋放隱藏的 UI 材質", type = "boolean"},
	["alwaysCompareItems"] = { prettyName = "總是對比物品", description = "永遠顯示物品對比提示", type = "boolean"},
	["showSpenderFeedback"] = { prettyName= "顯示消耗反饋", description = "當在資源條消耗怒氣/法力/等等，顯示/隱藏閃光。", type = "boolean" },
	-- Loss of Control UI
	["lossOfControlFull"] = { prettyName = "失去控制: 全部", description = "設置失控警報的類型。 (0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["lossOfControlSilence"] = { prettyName = "失去控制: 沉默", description = "設置失控警報的類型。(0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["lossOfControlInterrupt"] = { prettyName = "失去控制: 中斷", description = "設置失控警報的類型。(0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["lossOfControlDisarm"] = { prettyName = "失去控制: 繳械", description = "設置失控警報的類型。(0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["lossOfControlRoot"] = { prettyName = "失去控制: 無法行動", description = "設置失控警報的類型。(0 = 關閉, 1 = 只有警報, 2 = 顯示持續時間)", type = "number"},
	["synchronizeMacros"] = { prettyName = "同步巨集", description = "切換此伺服器的巨集同步 on/off", type = "boolean"},
	["synchronizeConfig"] = { prettyName = "同步設置", description = "切換此伺服器的設置同步 on/off", type = "boolean"},
	["cursorsizepreferred"] = { prettyName = "滑鼠指標大小", description = "0 = 32x32, 1 = 48x48, 2 = 64x64, -1 = autodetect", type = "number"},
	["ffxDeath"] = { prettyName = "FFX 死亡效果", description = "啟用全螢幕死亡特效", type = "boolean" },
	["WorldTextScale"] = { prettyName = "世界文字縮放", description = "遊戲世界中的傷害數字、經驗獲取、神兵獲取等縮放", type = "number" },


	-- 7.1.5 dump (1/16/17)
	["BrowserNavigateLog"] = { description = "啟用瀏覽器紀錄導覽請求 (需要 /重載)" },
	--["CACHE-WGOB-GameObjectsHotfixCount"] = {},
	--["CACHE-WGOB-GameObjectsRecordCount"] = {},
	--["CACHE-WQST-QuestObjectiveHotfixCount"] = {},
	--["CACHE-WQST-QuestObjectiveRecordCount"] = {},
	--["CACHE-WQST-QuestObjectiveXEffectHotfixCount"] = {},
	--["CACHE-WQST-QuestObjectiveXEffectRecordCount"] = {},
	--["CACHE-WQST-QuestV2HotfixCount"] = {},
	--["CACHE-WQST-QuestV2RecordCount"] = {},
	["ChatMusicVolume"] = {},
	["CombatHealingAbsorbSelf"] = {},
	["DepthBasedOpacity"] = {},
	["DesktopGamma"] = {},
	-- ["EJDungeonDifficulty"] = { description = "Stores the last dungeon difficulty viewed in the encounter journal" },
	-- ["EJLootClass"] = { description = "Stores the last class that loot was filtered by in the encounter journal" },
	-- ["EJLootSpec"] = { description = "Stores the last spec that loot was filtered by in the encounter journal" },
	-- ["EJRaidDifficulty"] = { description = "Stores the last raid difficulty viewed in the encounter journal" },
	["EmitterCombatrange"] = { description = "在戰鬥中停止肩膀/武器發射的範圍" },
	-- ["ErrorFilter"] = {},
	-- ["ErrorLevelMax"] = {},
	-- ["ErrorLevelMin"] = {},
	-- ["Errors"] = {},
	["FootstepSounds"] = { description = "撥放腳步聲" },
	["Gamma"] = {},
	["LodLiquid"] = { description = "液體渲染使用細節" },
	["M2ForceAdditiveParticleSort"] = { description = "強制所有顆粒排列好像它們是相加的" },
	["M2UseInstancing"] = { description = "使用硬體建議" },
	["M2UseLOD"] = { description = "使用模型細節" },
	["M2UseThreads"] = { description = "多線程模型動畫" },
	["MSAAAlphaTest"] = { description = "啟用MSAA在測試中幾何圖形" },
	["MSAAQuality"] = { description = "多重採樣AA質量" },
	["MaxObservedPetBattles"] = { description = "觀察寵物戰鬥的最大數量" },
	["NameplatePersonalHideDelayAlpha"] = { description = "在無可見度條件滿足後（在由NameplatePersonalHideDelaySeconds指定的時間段內），確定個人姓名版的透明度值。" },
	["NonEmitterCombatRange"] = { description = "在戰鬥之外停止肩膀/武器發射的範圍" },
	["ObjectSelectionCircle"] = {},
	["OutlineEngineMode"] = {},
	-- ["Outline"] = { description="Outline Mode" }, -- don't know what this does aside from make you flash when it's set
	["POIShiftComplete"] = {},
	-- ["PraiseTheSun"] = {},
	["PushToTalkButton"] = { description = "String representation of the Push-To-Talk button." },
	["RAIDDepthBasedOpacity"] = {},
	["RAIDLightMode"] = {},
	["RAIDOutlineEngineMode"] = {},
	["RAIDSSAO"] = {},
	["RAIDSSAOBlur"] = {},
	["RAIDWaterDetail"] = {},
	["RAIDcomponentTextureLevel"] = {},
	["RAIDenvironmentDetail"] = {},
	["RAIDfarclip"] = {},
	["RAIDgraphicsQuality"] = {},
	["RAIDgroundEffectDensity"] = {},
	["RAIDgroundEffectDist"] = {},
	["RAIDgroundEffectFade"] = { description = "團隊地面特效淡出" },
	["RAIDhorizonStart"] = { description = "團隊水平開始距離" },
	["RAIDlodObjectCullDist"] = {},
	["RAIDlodObjectCullSize"] = {},
	["RAIDlodObjectMinSize"] = {},
	["RAIDlodObjectFadeScale"] = {},
	["RAIDparticleDensity"] = {},
	["RAIDparticleMTDensity"] = {},
	["RAIDprojectedTextures"] = {},
	["RAIDreflectionMode"] = {},
	["RAIDrefraction"] = {},
	["RAIDrippleDetail"] = {},
	["RAIDsettingsEnabled"] = { description = "團隊圖形設置可用" },
	["RAIDsettingsInit"] = {},
	["RAIDshadowMode"] = {},
	["RAIDshadowSoft"] = {},
	["RAIDshadowTextureSize"] = {},
	["RAIDsunShafts"] = {},
	["RAIDterrainLodDist"] = {},
	["RAIDterrainMipLevel"] = {},
	["RAIDterrainTextureLod"] = {},
	["RAIDtextureFilteringMode"] = {},
	["RAIDweatherDensity"] = {},
	["RAIDwmoLodDist"] = {},
	["RAIDworldBaseMip"] = {},
	["RenderScale"] = { description = "渲染比例（用於超採樣或採樣不足）" },
	["ResampleQuality"] = { description = "重新取樣質量" },
	["SSAO"] = {},
	["SSAOBlur"] = {},
	["SSAODistance"] = { description = "SSAO 距離" },
	["SkyCloudLOD"] = {},
	["SoundPerf_VariationCap"] = { description = "限制聲音變數，以減少32位機器上的記憶體使用和磁盤抖動" },
	["SoundUseNewBusSystem"] = { description = "使用新的線程結構或回退到舊的" },
	["Sound_DSPBufferSize"] = { description = "聲音緩衝區大小, 預設 0" },
	["Sound_EnableArmorFoleySoundForOthers"] = {},
	["Sound_EnableArmorFoleySoundForSelf"] = {},
	["Sound_EnableMixMode2"] = {},
	["Sound_EnableMode2"] = {},
	["Sound_MaxCacheSizeInBytes"] = { description = "最大快取大小以位元計" },
	["Sound_MaxCacheableSizeInBytes"] = { description = "最大被快取的聲音大小，較大的文件將被傳輸" },
	["Sound_NumChannels"] = {},
	["Sound_OutputDriverIndex"] = {},
	["Sound_OutputDriverName"] = {},
	["Sound_OutputSampleRate"] = { description = "輸出採樣率" },
	["Sound_VoiceChatInputDriverIndex"] = {},
	["Sound_VoiceChatInputDriverName"] = {},
	["Sound_VoiceChatOutputDriverIndex"] = {},
	["Sound_VoiceChatOutputDriverName"] = {},
	["SplineOpt"] = { description = "toggles use of spline coll optimization" },
	["StartTalkingDelay"] = {},
	["StartTalkingTime"] = {},
	["StopTalkingDelay"] = {},
	["StopTalkingTime"] = {},
	["TargetPriorityValueBank"] = { description = "選擇用於計算目標優先級順序的有效定位值庫" },
	["VoiceChatMode"] = { description = "Push to talk(0) or voice activation(1)" },
	["VoiceChatSelfMute"] = { description = "Turn off your ability to talk." },
	["WorldTextCritScreenY"] = {},
	["WorldTextGravity"] = {},
	["WorldTextNonRandomZ"] = {},
	["WorldTextRampDuration"] = {},
	["WorldTextRampPow"] = {},
	["WorldTextRampPowCrit"] = {},
	["WorldTextRandomXY"] = {},
	["WorldTextRandomZMax"] = {},
	["WorldTextRandomZMin"] = {},
	["WorldTextScreenY"] = {},
	["WorldTextStartPosRandomness"] = {},
	-- ["accounttype"] = {},
	-- ["actionedAdventureJournalEntries"] = { description = "Which adventure journal entries flagged with ADVENTURE_JOURNAL_HIDE_AFTER_ACTION the user acted upon" },
	-- ["activeCUFProfile"] = { description = "The last active CUF Profile." },
	-- ["addFriendInfoShown"] = { description = "The info for Add Friend has been shown" },
	-- ["advJournalLastOpened"] = { description = "Last time the Adventure Journal opened" },
	-- ["agentUID"] = { description = "The UID provided by Battle.net to be passed to Agent" },
	["allowCompareWithToggle"] = {},
	["allowD3D9BackingStore"] = { description = "允許D3D9具有紋理支持以減少載入時間，同時增加記憶體不足崩潰的機會" },
	["animFrameSkipLOD"] = { description = "animations will skip frames at distance" },
	["asyncHandlerTimeout"] = { description = "引擎選項: Async read main thread timeout" },
	["asyncThreadSleep"] = { description = "引擎選項: Async read thread sleep" },
	["auctionDisplayOnCharacter"] = { description = "在穿著模型上顯示拍賣物品" },
	["audioLocale"] = { description = "設置遊戲音頻內容的區域" },
	["autoCompleteResortNamesOnRecency"] = { description = "Shows people you recently spoke with higher up on the AutoComplete list." },
	["autoCompleteUseContext"] = { description = "The system will, for example, only show people in your guild when you are typing /gpromote. Names will also never be removed." },
	["autoCompleteWhenEditingFromCenter"] = { description = "If you edit a name by inserting characters into the center, a smarter auto-complete will occur." },
	["autoDismount"] = { description = "如果需要的時候自動下坐騎" },
	-- ["autoFilledMultiCastSlots"] = { description = "Bitfield that saves whether multi-cast slots have been automatically filled." },
	-- ["autoQuestPopUps"] = { description = "Saves current pop-ups for quests that are automatically acquired or completed." },
	["autoStand"] = { description = "如果需要的時候自動站立" },
	["autoUnshift"] = { description = "如果需要的時候自動解除變身" },
	["autojoinBGVoice"] = { description = "在戰場聊天中自動加入語音會話" },
	["autojoinPartyVoice"] = { description = "在隊伍/團隊聊天中自動加入語音會話" },
	-- ["bloatTest"] = {},
	-- ["bloatnameplates"] = {},
	-- ["bloatthreat"] = {},
	["bodyQuota"] = { description = "Maximum number of componented bodies seen at once" },
	["breakUpLargeNumbers"] = { description = "切換是否在大數字中加入逗號" },
	["bspcache"] = { description = "BSP node caching" },
	["calendarShowBattlegrounds"] = { description = "戰場節日是否要出現在行事曆中" },
	["calendarShowDarkmoon"] = { description = "暗月節日是否要出現在行事曆中" },
	["calendarShowLockouts"] = { description = "團隊副本日程是否要出現在行事曆中" },
	["calendarShowResets"] = { description = "團隊副本重置是否要出現在行事曆中" },
	["calendarShowWeeklyHolidays"] = { description = "每周節日是否要出現在行事曆中" },
	["cameraCustomViewSmoothing"] = {},
	["cameraDistanceMax"] = {},
	["cameraDistanceMaxFactor"] = {},
	["cameraDistanceRateMult"] = {},
	["cameraDive"] = {},
	["cameraHeightIgnoreStandState"] = {},
	["cameraPitchSmoothMax"] = {},
	["cameraPitchSmoothMin"] = {},
	["cameraPivotDXMax"] = {},
	["cameraPivotDYMin"] = {},
	-- ["cameraSavedDistance"] = {},
	-- ["cameraSavedPetBattleDistance"] = {},
	-- ["cameraSavedPitch"] = {},
	-- ["cameraSavedVehicleDistance"] = {},
	-- ["cameraView"] = {},
	["cameraYawSmoothMax"] = {},
	["cameraYawSmoothMin"] = {},
	["cameraZDamp"] = {},
	["cameraZoomSpeed"] = {},
	-- ["characterFrameCollapsed"] = {},
	["chatStyle"] = { description = "聊天輸入框的樣式。有效值: \"classic\", \"im\"" },
	["checkAddonVersion"] = {},
	["cloakFixEnabled"] = {},
	-- ["closedInfoFrames"] = { description = "Bitfield for which help frames have been acknowledged by the user" },
	["colorChatNamesByClass"] = { description = "如果啟用，聊天中說話的玩家的名字將根據他的職業著色。" },
	["combatLogReducedRetentionTime"] = { description = "當我們記憶體不足時，保留戰鬥日誌條目的最長持續時間（秒）" },
	["combatLogRetentionTime"] = { description = "保留作戰日誌條目的最長持續時間（秒）" },
	["combatTextFloatMode"] = {},
	["componentCompress"] = { description = "角色組件紋理壓縮" },
	["componentEmissive"] = { description = "角色組件不點亮/發光" },
	["componentSpecular"] = { description = "在7.0.3禁用 - 角色組件鏡面高亮" },
	["componentTexCacheSize"] = { description = "角色組件紋理快取大小（以MB為單位）" },
	["componentTexLoadLimit"] = { description = "每幀的角色組件紋理加載限制" },
	["componentTextureLevel"] = {},
	["componentThread"] = { description = "多線程角色組件處理" },
	-- ["currencyCategoriesCollapsed"] = { description = "Internal CVar for tracking collapsed currency categories." },
	-- ["currencyTokensBackpack1"] = { description = "Currency token types shown on backpack." },
	-- ["currencyTokensBackpack2"] = { description = "Currency token types shown on backpack." },
	-- ["currencyTokensUnused1"] = { description = "Currency token types marked as unused." },
	-- ["currencyTokensUnused2"] = { description = "Currency token types marked as unused." },
	["daltonize"] = { description = "嘗試糾正色盲（將colorblindSimulator設置為色盲類型）" },
	-- ["dangerousShipyardMissionWarningAlreadyShown"] = { description = "Boolean indicating whether the shipyard's dangerous mission warning has been shown" },
	-- ["debugSoundPlayerSpellsOnlyOnPlayerBus"] = {},
	["detailDoodadInstancing"] = { description = "Detail doodad instancing" },
	["digSites"] = { description = "如果啟用，將使用考古挖掘系統。" },
	["disableAutoRealmSelect"] = { description = "登入時取消自動選擇伺服器" },
	["displayWorldPVPObjectives"] = { description = "是否顯示世界PvP目標" },
	-- ["displayedRAFFriendInfo"] = { description = "Stores whether we already told a recruited person about their new BattleTag friend" },
	["dontShowEquipmentSetsOnItems"] = { description = "不顯示哪個物品與換裝管理連結" },
	["doodadLodDist"] = { description = "Doodad level of detail distance" },
	["doodadUnloadDist"] = {},
	["enableBGDL"] = { description = "背景下載（在異步網路線程上）啟用" },
	-- ["enableCombatText"] = {},
	["enablePVPNotifyAFK"] = { description = "關閉AFK提醒系統的能力" },
	["enablePetBattleFloatingCombatText"] = { description = "是否在寵物戰鬥使用浮動戰鬥文字" },
	-- ["engineSurvey"] = {},
	["enterWorld"] = {},
	["entityLodDist"] = { description = "實體級別的細節距離" },
	["environmentDetail"] = {},
	["expandUpgradePanel"] = {},
	["farclip"] = {},
	["fctCombatState"] = {},
	-- ["fctFriendlyHealers"] = {},
	["ffxAntiAliasingMode"] = { description = "反鋸齒模式" },
	["ffxRectangle"] = { description = "使用矩形紋理在全螢幕效果" },
	-- ["flaggedTutorials"] = { description = "Internal cvar for saving completed tutorials in order" },
	["flightAngleLookAhead"] = { description = "允許在飛行時更多的動態姿態調整" },
	-- ["floatingCombatTextCombatDamageStyle"] = { description = "No longer used" },
	["forceEnglishNames"] = {},
	["forceLODCheck"] = { description = "If enabled, we will skip checking DBC for LOD count and every m2 will scan the folder for skin profiles" },
	-- ["friendInvitesCollapsed"] = { description = "Whether friend invites are hidden in the friends list" },
	["friendsSmallView"] = { description = "好友名單是否使用小型按鈕" },
	["friendsViewButtons"] = { description = "是否顯示好友名單檢視按鈕" },
	["fullDump"] = { description = "When you crash, generate a full memory dump" },
	["gameTip"] = {},
	["garrisonCompleteTalent"] = {},
	["garrisonCompleteTalentType"] = {},
	["graphicsDepthEffects"] = { description = "圖形設置的UI值" },
	["graphicsEnvironmentDetail"] = {},
	["graphicsLightingQuality"] = { description = "圖形設置的UI值" },
	["graphicsLiquidDetail"] = { description = "圖形設置的UI值" },
	["graphicsOutlineMode"] = { description = "圖形設置的UI值" },
	["graphicsParticleDensity"] = {},
	["graphicsProjectedTextures"] = { description = "圖形設置的UI值" },
	["graphicsQuality"] = {},
	["graphicsSSAO"] = { description = "圖形設置的UI值" },
	["graphicsShadowQuality"] = {},
	["graphicsSunshafts"] = { description = "圖形設置的UI值" },
	["graphicsTextureFiltering"] = {},
	["graphicsTextureResolution"] = {},
	["graphicsViewDistance"] = {},
	["groundEffectDensity"] = {},
	["groundEffectDist"] = {},
	["groundEffectFade"] = { description = "地面效果淡出" },
	-- ["guildNewsFilter"] = { description = "Stores the guild news filters" },
	["guildRewardsCategory"] = { description = "顯示公會獎勵類別" },
	["guildRewardsUsable"] = { description = "僅顯示可用的公會獎勵" },
	-- ["guildRosterView"] = { description = "The current guild roster display mode" },
	["guildShowOffline"] = { description = "在公會界面中顯示離線公會會員" },
	["gxAFRDevicesCount"] = { description = "強制設置AFR設備的數量" },
	["gxAdapter"] = { description = "強制運行指定的適配器索引（-1，讓客戶端選擇）" },
	-- ["gxApi"] = {},
	["gxAspect"] = { description = "constrain window aspect" },
	["gxCursor"] = { description = "切換硬體滑鼠指標" },
	["gxDepthResolveHandleCaching"] = { description = "Caching of the target handle for the depth resolve" },
	["gxFixLag"] = { description = "防止滑鼠指標延遲" },
	["gxFullscreenResolution"] = { description = "解析度" },
	["gxMaxFrameLatency"] = { description = "CPU可以在GPU前面的最大幀數" },
	["gxMaximize"] = {},
	["gxMonitor"] = { description = "顯示器" },
	["gxNewResolution"] = { description = "解析度設定" },
	["gxPreferWindowedFullscreen"] = { description = "提供何種全屏模式切換" },
	-- ["gxRefresh"] = {},
	["gxStereoConvergence"] = { description = "設置立體渲染融合深度" },
	["gxStereoEnabled"] = { description = "啟用立體渲染" },
	["gxStereoSeparation"] = { description = "設置立體渲染分離百分比" },
	["gxTextureCacheSize"] = { description = "GX Texture Cache Size" },
	["gxTripleBuffer"] = { description = "triple buffer" },
	["gxVSync"] = { description = "vsync on or off" },
	["gxWindow"] = {},
	["gxWindowedResolution"] = {},
	-- ["hardTrackedQuests"] = { description = "Internal cvar for saving hard (user manually selected) tracked quests in order" },
	-- ["hardTrackedWorldQuests"] = { description = "Internal cvar for saving hard tracked world quests" },
	["hbaoBias"] = { description = "HBAO Bias" },
	["hbaoBlurSharp"] = { description = "HBAO Blur Sharpness" },
	["hbaoNormals"] = { description = "Use Normals for HBAO" },
	["hbaoPowerExp"] = { description = "HBAO Power Exponent" },
	["hbaoRadius"] = { description = "HBAO Radius" },
	-- ["heirloomCollectedFilters"] = { description = "Bitfield for which collected filters are applied in the heirloom journal" },
	-- ["heirloomSourceFilters"] = { description = "Bitfield for which source filters are applied in the heirloom journal" },
	["hideAdventureJournalAlerts"] = { description = "Hide alerts shown on the Adventure Journal Microbutton" },
	["horizonStart"] = {},
	["hotReloadModels"] = { description = "Allow an active model to be reloaded when a new version is detected in the bin folder. If this is disabled, the model data will only be refreshed after all game objects using the model are deleted" },
	["hwDetect"] = {},
	["hwPCF"] = { description = "硬體PCF過濾" },
	["incompleteQuestPriorityThresholdDelta"] = {},
	["initialRealmListTimeout"] = { description = "在登入失敗之前等待初始伺服器列表需要多長時間（以秒為單位）" },
	["installLocale"] = {},
	--["installType"] = {},
	-- ["lastAddonVersion"] = {},
	-- ["lastCharacterIndex"] = {},
	-- ["lastGarrisonMissionTutorial"] = { description = "Stores the last garrison mission tutorial the player has accepted" },
	-- ["lastReadEULA"] = {},
	-- ["lastReadTOS"] = {},
	-- ["lastReadTerminationWithoutNotice"] = {},
	-- ["lastTalkedToGM"] = { description = "Stores the last GM someone was talking to in case they reload the UI while the GM chat window is open." },
	-- ["lastTransmogOutfitID"] = { description = "SetID of the last loaded transmog outfit" },
	-- ["lastVoidStorageTutorial"] = { description = "Stores the last void storage tutorial the player has accepted" },
	["launchAgent"] = { description = "將其設置為讓客戶端啟動代理" },
	-- ["lfGuildComment"] = { description = "Stores the player's Looking For Guild comment" },
	-- ["lfGuildSettings"] = { description = "Bit field of Looking For Guild player settings" },
	-- ["lfdCollapsedHeaders"] = { description = "Stores which LFD headers are collapsed." },
	-- ["lfdSelectedDungeons"] = { description = "Stores which LFD dungeons are selected." },
	["lfgAutoFill"] = { description = "是否在尋求組隊時自動添加隊伍成員" },
	["lfgAutoJoin"] = { description = "是否在尋求組隊時自動加入隊伍" },
	-- ["lfgListSearchLanguages"] = { description = "A simple bitfield for what languages we want to search in." },
	-- ["lfgSelectedRoles"] = { description = "Stores what roles the player is willing to take on." },
	["lightMode"] = {},
	["locale"] = { description = "設置遊戲區域設置" },
	["lockedWorldMap"] = { description = "Whether the world map is locked when sized down" },
	["lodObjectCullDist"] = {},
	["lodObjectCullSize"] = {},
	["lodObjectMinSize"] = {},
	["lodTerrainDiv"] = { description = "Terrain lod divisor" },
	["mapAnimDuration"] = { description = "Duration for the alpha animation" },
	["mapAnimMinAlpha"] = { description = "Alpha value to animate to when player moves with windowed world map open" },
	["mapAnimStartDelay"] = { description = "Start delay for the alpha animation" },
	["mapQuestDifficulty"] = {},
	-- ["maxAnimThreads"] = {},
	["maxFPS"] = { description = "設置FPS限制" },
	["maxFPSBk"] = { description = "設置背景FPS限制" },
	["maxLightCount"] = { description = "最大的光亮渲染" },
	["maxLightDist"] = { description = "Maximum distance to render lights" },
	["miniWorldMap"] = { description = "世界地圖是否切換成較小的尺寸" },
	["minimapAltitudeHintMode"] = { description = "更改小地圖高度差異顯示。 0 =無，1 =變暗，2 =箭頭" },
	["minimapInsideZoom"] = { description = "當前室內小地圖縮放級別" },
	["minimapPortalMax"] = { description = "Max Number of Portals to traverse for minimap" },
	-- ["minimapShapeshiftTracking"] = { description = "Stores shapeshift-specific tracking spells that were active last session." },
	["minimapShowArchBlobs"] = { description = "存儲是否在小地圖上顯示考古學斑點。" },
	["minimapShowQuestBlobs"] = { description = "存儲是否在小地圖上顯示任務斑點。" },
	-- ["minimapTrackedInfo"] = {},
	-- ["minimapTrackedInfov2"] = { description = "Stores the minimap tracking that was active last session." },
	["minimapZoom"] = { description = "當前戶外小地圖縮放級別" },
	["missingTransmogSourceInItemTooltips"] = { description = "Whether to show if you have collected the appearance of an item but not from that item itself" },
	-- ["mountJournalFilters"] = { description = "Bitfield for which collected filters are applied in the mount journal" },
	-- ["mountJournalSourceFilters"] = { description = "Bitfield for which source filters are applied in the mount journal" },
	["mouseInvertYaw"] = {},
	["mtParticles"] = { description = "multithread building of particle vertices" },
	["nameplateMotionSpeed"] = { description = "控制姓名版動畫到目標位置的速度[0.0-1.0]" },
	["nameplateShowEnemyMinions"] = {},
	["nameplateShowFriendlyMinions"] = {},
	["nearclip"] = { description = "Near clip plane distance" },
	-- ["orderHallMissionTutorial"] = { description = "Stores information about which order hall mission tutorials the player has seen" },
	["outdoorMinAltitudeDistance"] = { description = "Minimum altitude distance for outdoor objects when you are also outdoors before the altitude difference marker displays" },
	["outlineMouseOverFadeDuration"] = {},
	["outlineSelectionFadeDuration"] = {},
	["overrideArchive"] = { description = "Whether or not the client loads alternate data" },
	["particleDensity"] = {},
	["particleMTDensity"] = {},
	["partyBackgroundOpacity"] = { description = "隊伍背景的透明度" },
	["pathSmoothing"] = { description = "NPC will round corners on ground paths" },
	-- ["pendingInviteInfoShown"] = { description = "The info for pending invites has been shown" },
	-- ["petJournalFilters"] = { description = "Bitfield for which collected filters are applied in the pet journal" },
	-- ["petJournalSort"] = { description = "Sorting value for the pet journal" },
	-- ["petJournalSourceFilters"] = { description = "Bitfield for which source filters are applied in the pet journal" },
	-- ["petJournalTab"] = { description = "Stores the last tab the pet journal was opened to" },
	-- ["petJournalTypeFilters"] = { description = "Bitfield for which type filters are applied in the pet journal" },
	["physicsLevel"] = { description = "物理世界互動等級" },
	["playIntroMovie"] = {},
	--["playerStatLeftDropdown"] = { description = "The player stat selected in the left dropdown" },
	--["playerStatRightDropdown"] = { description = "The player stat selected in the right dropdown" },
	-- ["portal"] = { description = "Name of Battle.net portal to use" },
	["predictedHealth"] = { description = "是否在UI中使用預測的血量值" },
	["preloadLoadingDistObject"] = { description = "登入時的物體預載距離" },
	["preloadLoadingDistTerrain"] = { description = "登入時的地形預載距離" },
	["preloadPlayerModels"] = { description = "將所有當地種族模型預加載到記憶體中" },
	["preloadStreamingDistObject"] = { description = "Object preload distance when streaming" },
	["preloadStreamingDistTerrain"] = { description = "Terrain preload distance when streaming" },
	["primaryProfessionsFilter"] = { description = "If enabled, primary profession world quests icons will be shown on world maps" },
	["processAffinityMask"] = { description = "設置WoW可以執行的核心 - 更改需要重新啟動才能生效" },
	["projectedTextures"] = {},
	["pvpBlacklistMaps0"] = { description = "Blacklist PVP Map" },
	["pvpBlacklistMaps1"] = { description = "Blacklist PVP Map" },
	-- ["pvpSelectedRoles"] = { description = "Stores what roles the player will fulfill in a BG." },
	-- ["questLogCollapseFilter"] = {},
	-- ["questLogCollapseHeaderFilter"] = {},
	-- ["questLogOpen"] = { description = "Whether the quest log appears the side of the windowed map. " },
	["questPOI"] = { description = "如果啟用，將使用任務POI系統。" },
	["raidFramesDisplayAggroHighlight"] = { description = "是否在團隊框架上顯示仇恨亮點" },
	["raidFramesDisplayClassColor"] = { description = "使用職業顏色著色團隊框架" },
	["raidFramesDisplayOnlyDispellableDebuffs"] = { description = "是否只在團隊框架上顯示可驅散的debuff" },
	["raidFramesDisplayPowerBars"] = { description = "Whether to display mana, rage, etc. on Raid Frames" },
	["raidFramesHealthText"] = { description = "如何在團隊框架上顯示血量文字" },
	["raidFramesHeight"] = { description = "每個團隊框架的高度" },
	["raidFramesPosition"] = { description = "團隊框架應放置在何處" },
	["raidFramesWidth"] = { description = "每個團隊框架的寬度" },
	["raidGraphicsDepthEffects"] = {},
	["raidGraphicsEnvironmentDetail"] = {},
	["raidGraphicsGroundClutter"] = {},
	["raidGraphicsLightingQuality"] = {},
	["raidGraphicsLiquidDetail"] = {},
	["raidGraphicsOutlineMode"] = {},
	["raidGraphicsParticleDensity"] = {},
	["raidGraphicsProjectedTextures"] = {},
	["raidGraphicsSSAO"] = {},
	["raidGraphicsShadowQuality"] = {},
	["raidGraphicsSunshafts"] = {},
	["raidGraphicsTextureFiltering"] = {},
	["raidGraphicsTextureResolution"] = {},
	["raidGraphicsViewDistance"] = {},
	["raidOptionDisplayMainTankAndAssist"] = { description = "是否在團隊框架中顯示主坦與主助攻" },
	["raidOptionDisplayPets"] = { description = "是否在團隊框架中顯示寵物" },
	["raidOptionIsShown"] = { description = "是否顯示團隊框架" },
	["raidOptionKeepGroupsTogether"] = { description = "組合團隊框架的方式" },
	["raidOptionLocked"] = { description = "團隊框架是否鎖定" },
	["raidOptionShowBorders"] = { description = "在團隊框架外顯示外框。" },
	["raidOptionSortMode"] = { description = "排序團隊框架的方式" },
	["raidOrBattleCount"] = {},
	["rawMouseAccelerationEnable"] = { description = "啟用原始鼠標輸入的加速" },
	["rawMouseEnable"] = { description = "啟用原始鼠標輸入" },
	["rawMouseRate"] = { description = "原始鼠標更新率" },
	["rawMouseResolution"] = { description = "原始鼠標分辨率" },
	--["readContest"] = {},
	--["readEULA"] = {},
	--["readScanning"] = {},
	--["readTOS"] = {},
	--["readTerminationWithoutNotice"] = {},
	-- ["realmName"] = {},
	["reflectionDownscale"] = { description = "Reflection downscale" },
	["reflectionMode"] = {},
	["refraction"] = {},
	["repositionfrequency"] = {},
	-- ["reputationsCollapsed"] = { description = "List of reputation categories that have been collapsed in the Reputation tab" },
	["rippleDetail"] = {},
	["sceneOcclusionEnable"] = { description = "Scene software occlusion" },
	["screenshotFormat"] = {},
	["screenshotQuality"] = {},
	["scriptProfile"] = { description = "腳本分析是否啟用" },
	["scriptWarnings"] = { description = "UI是否顯示Lua警告" },
	["secondaryProfessionsFilter"] = { description = "如果啟用，第二專業世界任務圖標將顯示在世界地圖上" },
	-- ["seenAsiaCharacterUpgradePopup"] = { description = "Seen the free character upgrade popup (Asia)" },
	-- ["seenCharacterUpgradePopup"] = {},
	-- ["serverAlert"] = { description = "Get the glue-string tag for the URL" },
	-- ["serviceTypeFilter"] = { description = "Which trainer services to show" },
	["shadowCull"] = { description = "enable shadow frustum culling" },
	["shadowInstancing"] = { description = "enable instancing when rendering shadowmaps" },
	["shadowMode"] = {},
	["shadowScissor"] = { description = "enable scissoring when rendering shadowmaps" },
	["shadowSoft"] = {},
	["shadowTextureSize"] = {},
	-- ["shipyardMissionTutorialAreaBuff"] = { description = "Stores whether the player has accepted the first area buff mission tutorial" },
	-- ["shipyardMissionTutorialBlockade"] = { description = "Stores whether the player has accepted the first blockade mission tutorial" },
	-- ["shipyardMissionTutorialFirst"] = { description = "Stores whether the player has accepted the first mission tutorial" },
	["showAllEnemyDebuffs"] = {},
	["showArtifactXPBar"] = { description = "Show the artifact xp as priority over reputation" },
	["showBattlefieldMinimap"] = { description = "是否顯示戰場小地圖" },
	["showBuilderFeedback"] = { description = "Show animation when building power for builder/spender bar" },
	["showErrors"] = {},
	["showKeyring"] = {},
	["showNPETutorials"] = { description = "display NPE tutorials" },
	["showNewbieTips"] = {},
	["showQuestObjectivesOnMap"] = { description = "在主地圖上顯示任務POI。" },
	["showQuestTrackingTooltips"] = { description = "在單位和對象工具提示中顯示任務追蹤訊息" },
	["showSpectatorTeamCircles"] = { description = "Determines if the team color circles are visible while spectating or commentating a wargame" },
	["showTamers"] = { description = "如果啟用，寵物戰鬥圖標將顯示在世界地圖上" },
	["showTimestamps"] = { description = "聊天中的時間戳格式或“無”" },
	-- ["showTokenFrame"] = { description = "The token UI has been shown" },
	-- ["showTokenFrameHonor"] = { description = "The token UI has shown Honor" },
	-- ["showToolsUI"] = {},
	["showfootprintparticles"] = { description = "toggles rendering of footprint particles" },
	["simd"] = { description = "Enable SIMD features (e.g. SSE)" },
	["skipStartGear"] = { description = "Whether we should show starter gear on character create" },
	["smoothUnitPhasing"] = { description = "The client will try to smoothly switch between the same on model different phases." },
	["smoothUnitPhasingActorPurgatoryTimeMs"] = { description = "Time to keep client-actor displays in purgatory before letting go of them, if they were despawned" },
	["smoothUnitPhasingAliveTimeoutMs"] = { description = "Time to wait for an alive unit to get it's despawn message" },
	["smoothUnitPhasingDestroyedPurgatoryTimeMs"] = { description = "Time to keep unit displays in purgatory before letting go of them, if they were destroyed" },
	["smoothUnitPhasingDistThreshold"] = { description = "Distance threshold to active smooth unit phasing." },
	["smoothUnitPhasingEnableAlive"] = { description = "Use units that have not despawn yet if they match, in hopes the despawn message will come later." },
	["smoothUnitPhasingUnseenPurgatoryTimeMs"] = { description = "Time to keep unit displays in purgatory before letting go of them, if they were just unseen." },
	["smoothUnitPhasingVehicleExtraTimeoutMs"] = { description = "Extra time to wait before releasing a vehicle, after it has smooth phased. This allows it's passengers to smooth phase as well." },
	["spellBookSort"] = {},
	["spellClutter"] = { description = "Enables/Disables spell clutter" },
	["spellClutterDefaultTargetScalar"] = { description = "Starting target scalar value (min 0.1)" },
	["spellClutterHostileScalar"] = { description = "Scalar we apply to the hostile creature spells (min 0.001)" },
	["spellClutterMinSpellCount"] = { description = "Min spells on a target before we apply clutter logic (min 0)" },
	["spellClutterPartySizeScalar"] = { description = "Scales the targetScalar by how different the party size is from this (min 1)" },
	["spellClutterPlayerScalarMultiplier"] = { description = "Increases number of effects on \"interesting\" targets multiplicatively (min 0.1)" },
	["spellClutterRangeConstant"] = { description = "How many yards before the priority is doubled (min 1.0)" },
	["splashScreenBoost"] = { description = "Show boost splash screen id " },
	["splashScreenNormal"] = { description = "Show normal splash screen id" },
	-- ["statCategoriesCollapsed"] = {},
	-- ["statCategoriesCollapsed_2"] = {},
	-- ["statCategoryOrder"] = {},
	-- ["statCategoryOrder_2"] = {},
	["streamBeams"] = { description = "Use vertex streaming for beams (Gfx Driver Workaround). 0=Auto Detect, 1=Never Stream, 2=Always Stream" },
	["streamStatusMessage"] = { description = "Whether to display status messages while streaming content" },
	["streamingCameraLookAheadTime"] = { description = "Look ahead time for streaming." },
	["streamingCameraMaxRadius"] = { description = "Max radius of the streaming camera." },
	["streamingCameraRadius"] = { description = "Base radius of the streaming camera." },
	["sunShafts"] = {},
	["superTrackerDist"] = {},
	["synchronizeBindings"] = {},
	["synchronizeChatFrames"] = {},
	["synchronizeSettings"] = { description = "Whether client settings should be stored on the server" },
	["taintLog"] = {},
	-- ["talentFrameShown"] = { description = "The talent UI has been shown" },
	["talentPointsSpent"] = { description = "The player has spent a talent point" },
	["targetOfTargetMode"] = { description = "The conditions under which target of target should be shown" },
	["terrainAlphaBitDepth"] = { description = "Terrain alpha map bit depth" },
	["terrainHoles"] = { description = "Terrain holes affect occlusion" },
	["terrainLodDist"] = {},
	["terrainMipLevel"] = {},
	["terrainTextureLod"] = {},
	["test_cameraDynamicPitch"] = { description = "ActionCam" },
	["test_cameraDynamicPitchBaseFovPad"] = { description = "ActionCam" },
	["test_cameraDynamicPitchBaseFovPadDownScale"] = { description = "ActionCam" },
	["test_cameraDynamicPitchBaseFovPadFlying"] = { description = "ActionCam" },
	["test_cameraDynamicPitchSmartPivotCutoffDist"] = { description = "ActionCam" },
	["test_cameraHeadMovementDeadZone"] = { description = "ActionCam" },
	["test_cameraHeadMovementFirstPersonDampRate"] = { description = "ActionCam" },
	["test_cameraHeadMovementMovingDampRate"] = { description = "ActionCam" },
	["test_cameraHeadMovementMovingStrength"] = { description = "ActionCam" },
	["test_cameraHeadMovementRangeScale"] = { description = "ActionCam" },
	["test_cameraHeadMovementStandingDampRate"] = { description = "ActionCam" },
	["test_cameraHeadMovementStandingStrength"] = { description = "ActionCam" },
	["test_cameraHeadMovementStrength"] = { description = "ActionCam" },
	["test_cameraLockedTargetFocusing"] = { description = "ActionCam" },
	["test_cameraOverShoulder"] = { description = "ActionCam" },
	["test_cameraTargetFocusEnemyEnable"] = { description = "ActionCam" },
	["test_cameraTargetFocusEnemyStrengthPitch"] = { description = "ActionCam" },
	["test_cameraTargetFocusEnemyStrengthYaw"] = { description = "ActionCam" },
	["test_cameraTargetFocusInteractEnable"] = { description = "ActionCam" },
	["test_cameraTargetFocusInteractStrengthPitch"] = { description = "ActionCam" },
	["test_cameraTargetFocusInteractStrengthYaw"] = { description = "ActionCam" },
	["textLocale"] = { description = "Set the game locale for text" },
	["textureFilteringMode"] = {},
	["threatWarning"] = { description = "Whether or not to show threat warning UI (0 = off, 1 = in dungeons, 2 = in party/raid, 3 = always)" },
	["threatWorldText"] = { description = "是否在戰鬥中顯示威脅浮標" },
	["timeMgrAlarmEnabled"] = { description = "Toggles whether or not the time manager's alarm will go off" },
	["timeMgrAlarmMessage"] = { description = "The time manager's alarm message" },
	["timeMgrAlarmTime"] = { description = "The time manager's alarm time in minutes" },
	["timeMgrUseLocalTime"] = { description = "Toggles the use of either the realm time or your system time" },
	["timeMgrUseMilitaryTime"] = { description = "Toggles the display of either 12 or 24 hour time" },
	["timingMethod"] = { description = "Desired method for game timing" },
	-- ["timingTestError"] = { description = "Error reported by the timing validation system" }, -- read-only
	-- ["toyBoxCollectedFilters"] = { description = "Bitfield for which collected filters are applied in the toybox" },
	-- ["toyBoxSourceFilters"] = { description = "Bitfield for which source filters are applied in the toybox" },
	-- ["trackedAchievements"] = { description = "Internal cvar for saving tracked achievements in order" },
	-- ["trackedQuests"] = { description = "Internal cvar for saving automatically tracked quests in order" },
	-- ["trackedWorldQuests"] = { description = "Internal cvar for saving tracked world quests" },
	-- ["trackerFilter"] = {},
	-- ["trackerSorting"] = {},
	["transmogCurrentSpecOnly"] = { description = "Stores whether transmogs apply to current spec instead of all specs" },
	-- ["transmogrifyShowCollected"] = { description = "Whether to show collected transmogs in the at the transmogrifier" }, -- read-only
	-- ["transmogrifyShowUncollected"] = { description = "Whether to show uncollected transmogs in the at the transmogrifier" }, -- read-only
	-- ["transmogrifySourceFilters"] = { description = "Bitfield for which source filters are applied in the wardrobe at the transmogrifier" },
	["twitterCharactersPerMedia"] = { description = "Number of characters needed when attaching media to a Twitter post" },
	-- ["twitterGetConfigTime"] = { description = "Last time that we got Twitter configuration data successfully" },
	["twitterShortUrlLength"] = { description = "Number of characters that non-https URLS get shortened to" },
	["twitterShortUrlLengthHttps"] = { description = "Number of characters that https URLS get shortened to" },
	["uiScale"] = {},
	["uiScaleMultiplier"] = { description = "A multiplier for the default UI scale. -1=determine based on system/monitor DPI, 0.5-2.0=multiplier to use when calculating UI scale. Only applied when useUIScale is 0." },
	["unitHighlights"] = { description = "Whether the highlight circle around units should be displayed" },
	["useCompactPartyFrames"] = { description = "Use the new raid frames for parties" },
	["useUiScale"] = {},
	["videoOptionsVersion"] = {},
	-- ["wardrobeShowCollected"] = { description = "Whether to show collected transmogs in the wardrobe" }, -- read-only
	-- ["wardrobeShowUncollected"] = { description = "Whether to show uncollected transmogs in the wardrobe" }, -- read-only
	-- ["wardrobeSourceFilters"] = { description = "Bitfield for which source filters are applied in the wardrobe in the collection journal" },
	["warp"] = { description = "圖形設置的UI值" },
	["warpScreenSize"] = { description = "Physical monitor size" },
	["warpViewDistance"] = { description = "Physical distance from the viewer to the monitor" },
	["warpViewTilt"] = { description = "Angle of the side monitors IN RADIANS" },
	["watchFrameBaseAlpha"] = { description = "Objectives frame opacity." },
	-- ["watchFrameState"] = { description = "Stores Objectives frame locked and collapsed states" },
	["waterDetail"] = {},
	["weatherDensity"] = {},
	["webChallengeURLTimeout"] = { description = "How long to wait for the web challenge URL (in seconds). 0 means wait forever." },
	["whisperMode"] = { description = "The action new whispers take by default: \"popout\", \"inline\", \"popout_and_inline\"" },
	["windowResizeLock"] = { description = "prevent resizing in windowed mode" },
	["wmoDoodadDist"] = { description = "Wmo doodad load distance" },
	["wmoLodDist"] = {},
	["worldBaseMip"] = {},
	["worldLoadSort"] = { description = "Sort objects by distance when loading" },
	["worldMapOpacity"] = { description = "Opacity for the world map when sized down" },
	["worldMaxMipLevel"] = { description = "World maximum texture mip level" },
	["worldPoolUsage"] = { description = "Usage static/dynamic/stream" },
	["worldPreloadHighResTextures"] = { description = "Require high res textures to be loaded in streaming non critical radius when preloading" },
	["worldPreloadNonCritical"] = { description = "Require objects to be loaded in streaming non critical radius when preloading" },
	["worldPreloadSort"] = { description = "Sort objects by distance when preloading" },
	["worldQuestFilterArtifactPower"] = { description = "如果啟用，具有神兵之力獎勵的世界任務將顯示在地圖上" },
	["worldQuestFilterEquipment"] = { description = "如果啟用，具有裝備獎勵的世界任務將顯示在地圖上" },
	["worldQuestFilterGold"] = { description = "如果啟用，金幣獎勵的世界任務將顯示在地圖上" },
	["worldQuestFilterOrderResources"] = { description = "如果啟用，具有職業大廳資源獎勵的世界任務將顯示在地圖上" },
	["worldQuestFilterProfessionMaterials"] = { description = "如果啟用，具有專業技能獎勵的世界任務將顯示在地圖上" },
	["CastTimingEnhancements"] = { prettyName = nil, description = "Hold chain precasts, and predict anim timed casts", type = "boolean" },
	["autoAcceptQuickJoinRequests"] = { prettyName = "自動接受快速加入請求", description = "", type = "boolean" },
	
	["AimingStrafeLeftUsesMoveBackwards"] = { description = "Uses backwards move anim when aiming a ranged weapon and strafing to the left" },
	["DebugTorsoTwist"] = { description = "Debug visualization for Torso Twist: 1 = Player, 2 = Target, 3 = All" },
	
	["lodObjectFadeScale"] = {},
}

local CategoryNames = { -- not sure how meaningful these really are (/Blizzard_Console/Blizzard_Console_AutoComplete.lua Enum.ConsoleCategory)
	[0] = "Debug",
	[1] = "Graphics",
	[2] = "Console",
	[3] = "Combat",
	[4] = "Game",
	[5] = "Default",
	[6] = "Net",
	[7] = "Sound",
	[8] = "GM",
	[9] = "None",
}

--[[
	C_Console.GetAllCommands() returns a list of tables in this format:
		category: number from 0 to 9 representing a category above
		command: cvar name
		commandType: 0 seems to represent a cvar, 1 is a script command (like quit)
		help: cvar description text
--]]

for _, info in pairs(C_Console.GetAllCommands()) do
	if not addon.hiddenOptions[info.command]
	  and info.commandType == 0 -- cvar, rather than script
	  and info.category ~= 0 -- ignore debug category
	  and not strfind(info.command:lower(), 'debug') -- a number of commands with "debug" in their name are inexplicibly not in the "debug" category
	  and info.category ~= 8 -- ignore GM category
	then
		local value = GetCVar(info.command)
		local optionTable = {
			-- prettyName = info.command, -- the api doesn't provide pretty names, so the only way to keep these would be to create a table for them
			description = info.help,		
		}
		addon.hiddenOptions[info.command] = optionTable
	end
end


-- Allow case-insensitive lookup of cvars in our table (relatively slow, so match the case when possible)
local NoCase = {
	__index = function(t, mk) -- get
		if mk and mk.lower then
			local mk = mk:lower()
			for k,v in pairs(t) do
				if k:lower() == mk then
					return v
				end
			end
		end
	end,
	__newindex = function(t, mk, mv) -- set
		if mk and mk.lower then
			local mk = mk:lower()
			for k,v in pairs(t) do
				if k:lower() == mk then
					t[k] = mv
					return
				end
			end
		end
	end,
}
setmetatable(addon.hiddenOptions, NoCase)
