local f = CreateFrame("Frame")
f:RegisterEvent("PLAYER_ENTERING_WORLD")
f:SetScript("OnEvent", function()
m_icon(PVEFrame, "lfg", -8, 9, "MEDIUM")
RaidFinderQueueFrameScrollFrameScrollBackground:Hide()
LFGListApplicationViewerScrollFrameScrollBarBG:Hide()
LFGListSearchPanelScrollFrameScrollBarBG:Hide()
RaidFinderFrameRoleBackground:Hide()
RaidBrowserFramePortrait:SetTexCoord(0.85, 0.15, 0.15, 0.85)
LFDQueueFrameRoleButtonTankIncentiveIconBorder:Hide()
LFDQueueFrameRoleButtonTankIncentiveIconTexture:SetTexCoord(0.85, 0.15, 0.15, 0.85)
LFDQueueFrameRoleButtonHealerIncentiveIconBorder:Hide()
LFDQueueFrameRoleButtonHealerIncentiveIconTexture:SetTexCoord(0.85, 0.15, 0.15, 0.85)
LFDQueueFrameRoleButtonDPSIncentiveIconBorder:Hide()
LFDQueueFrameRoleButtonDPSIncentiveIconTexture:SetTexCoord(0.85, 0.15, 0.15, 0.85)
RaidFinderQueueFrameRoleButtonTankIncentiveIconBorder:Hide()
RaidFinderQueueFrameRoleButtonTankIncentiveIconTexture:SetTexCoord(0.85, 0.15, 0.15, 0.85)
RaidFinderQueueFrameRoleButtonHealerIncentiveIconBorder:Hide()
RaidFinderQueueFrameRoleButtonHealerIncentiveIconTexture:SetTexCoord(0.85, 0.15, 0.15, 0.85)
RaidFinderQueueFrameRoleButtonDPSIncentiveIconBorder:Hide()
RaidFinderQueueFrameRoleButtonDPSIncentiveIconTexture:SetTexCoord(0.85, 0.15, 0.15, 0.85)
	
for i=1,4 do
	_G["GroupFinderFrameGroupButton"..i.."Ring"]:Hide()
	_G["GroupFinderFrameGroupButton"..i.."Icon"]:SetTexCoord(0.85, 0.15, 0.15, 0.85)
	_G["GroupFinderFrameGroupButton"..i.."Icon"]:SetWidth(46)
	_G["GroupFinderFrameGroupButton"..i.."Icon"]:SetHeight(46)
end
	
m_border(GroupFinderFrameGroupButton1,50,50,"LEFT",10,0,14,"MEDIUM")
m_fontify(GroupFinderFrameGroupButton1Name,"white")
m_border(GroupFinderFrameGroupButton2,50,50,"LEFT",10,0,14,"MEDIUM")
m_fontify(GroupFinderFrameGroupButton2Name,"white")
m_border(GroupFinderFrameGroupButton3,50,50,"LEFT",10,0,14,"MEDIUM")
m_fontify(GroupFinderFrameGroupButton3Name,"white")
m_border(GroupFinderFrameGroupButton4,50,50,"LEFT",10,0,14,"MEDIUM")
m_fontify(GroupFinderFrameGroupButton4Name,"white")
m_border(RaidFinderQueueFrameRoleButtonTankIncentiveIcon,19,19,"LEFT",0,3,4,"MEDIUM")
m_border(RaidFinderQueueFrameRoleButtonHealerIncentiveIcon,19,19,"LEFT",0,3,4,"MEDIUM")
m_border(RaidFinderQueueFrameRoleButtonDPSIncentiveIcon,19,19,"LEFT",0,3,4,"MEDIUM")
m_border(LFDQueueFrameRoleButtonTankIncentiveIcon,19,19,"LEFT",0,3,4,"MEDIUM")
m_border(LFDQueueFrameRoleButtonHealerIncentiveIcon,19,19,"LEFT",0,3,4,"MEDIUM")
m_border(LFDQueueFrameRoleButtonDPSIncentiveIcon,19,19,"LEFT",0,3,4,"MEDIUM")
m_border(LFGListFrame.CategorySelection,336,344,"CENTER",-4,-16,14,"MEDIUM")
m_border(LFGListFrame.EntryCreation,336,344,"CENTER",-4,-16,14,"MEDIUM")
m_border(LFGListFrame.ApplicationViewer,316,254,"CENTER",-13,-62,14,"MEDIUM")

LFGListFrame.SearchPanel:HookScript("OnShow",function()
m_border(LFGListSearchPanelScrollFrame,316,LFGListSearchPanelScrollFrame:GetHeight()+8,"CENTER",1.5,0,14,"MEDIUM")
end)
PremadeGroupsPvETutorialAlertBg:SetGradientAlpha("HORIZONTAL", 1, 1, 1, 1, 1, 1, 1, 1)
PremadeGroupsPvETutorialAlertBg:SetColorTexture(0.078,0.078,0.078,1)
m_border(PremadeGroupsPvETutorialAlert,226,156,"CENTER",0.5,0,14,"DIALOG")		
m_fontify(PremadeGroupsPvETutorialAlert.Text,"white")	
m_fontify(LFGListSearchPanelScrollFrame.NoResultsFound,"same")
local function miirgui_WorldStateScoreFrame_Update()
	WorldStateScoreWinnerFrameLeft:SetTexture("Interface\\FrameGeneral\\UI-Background-Rock.blp")
	WorldStateScoreWinnerFrameLeft:SetVertexColor(1,1,1,1)
	WorldStateScoreWinnerFrameRight:SetTexture("Interface\\FrameGeneral\\UI-Background-Rock.blp")
	WorldStateScoreWinnerFrameRight:SetVertexColor(1,1,1,1)
	QuestMapFrame.DetailsFrame.SealMaterialBG:Hide()
end
	
hooksecurefunc("WorldStateScoreFrame_Update",miirgui_WorldStateScoreFrame_Update)	
end)