-- MiliUI: Ayije_CDM 預設值
-- 首次安裝時自動套用，已有設定則不覆蓋

MiliUI_AyijeCDM_Profile = {
    ["trinketsIconWidth"] = 40,
    ["resourcesBar1TagFontSize"] = 16,
    ["hideBlizzardCastBar"] = true,
    ["utilityWrap"] = false,
    ["cooldownColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["resourcesBarSpacing"] = 1,
    ["containerLocked"] = true,
    ["resourcesBackgroundColor"] = { ["a"] = 0.5, ["r"] = 0.2, ["g"] = 0.2, ["b"] = 0.2 },
    ["racialsUsePartyFrame"] = false,
    ["castBarHeight"] = 20,
    ["glowPixelYOffset"] = 0,
    ["resourcesManaPercentage"] = false,
    ["castBarAnchorToResources"] = true,
    ["buffBarTexture"] = "TukTex",
    ["glowUseCustomColor"] = false,
    ["racialsIconWidth"] = 40,
    ["racialsPartyFrameSide"] = "LEFT",
    ["trinketsEssentialRow"] = 1,
    ["trinketsAnchorPoint"] = "TOPLEFT",
    ["buffBarIconGap"] = 1,
    ["glowType"] = "pixel",
    ["trinketsIconHeight"] = 36,
    ["countOffsetXMain"] = 0,
    ["resourcesBar1TagOffsetX"] = 0,
    ["resourcesSoulFragmentsColor"] = { ["a"] = 1, ["r"] = 0, ["g"] = 0.8, ["b"] = 0 },
    ["fadingBuffs"] = true,
    ["fadingDefensives"] = true,
    ["defensivesAnchorPoint"] = "TOPRIGHT",
    ["spacing"] = 1,
    ["maxRowUtil"] = 8,
    ["buffTertiaryHorizontal"] = false,
    ["buffBarApplicationsFontSize"] = 12,
    ["glowAutocastXOffset"] = 0,
    ["textFont"] = "提示訊息",
    ["hideCooldownBling"] = true,
    ["buffBarShowDuration"] = true,
    ["glowPixelThickness"] = 2,
    ["buffCooldownFontSize"] = 16,
    ["resourcesEnabled"] = true,
    ["buffBarHeight"] = 20,
    ["glowPixelLines"] = 8,
    ["countPositionMain"] = "TOP",
    ["castBarTimerOffsetY"] = 6,
    ["racialsPartyFrameOffsetX"] = -1,
    ["sizeEssRow2"] = { ["w"] = 46, ["h"] = 40 },
    ["chargeFontSize"] = 12,
    ["resourcesStaggerLightColor"] = { ["a"] = 1, ["r"] = 0.52, ["g"] = 0.9, ["b"] = 0.52 },
    ["resourcesBar2Height"] = 16,
    ["racialsChargeFontSize"] = 12,
    ["resourcesBarWidth"] = 0,
    ["buffBarNameColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["chargeColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["countPositionTert"] = "LEFT",
    ["buffSecondaryHorizontal"] = false,
    ["resourcesRageColor"] = { ["a"] = 1, ["r"] = 0.78, ["g"] = 0.26, ["b"] = 0.26 },
    ["resourcesStaggerModerateColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 0.85, ["b"] = 0.36 },
    ["buffBarDurationFontSize"] = 16,
    ["resourcesEnergyColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 0.34 },
    ["castBarFontSize"] = 12,
    ["resourcesUnifiedBorder"] = false,
    ["resourcesRunesReadyColor"] = { ["a"] = 1, ["r"] = 0.5, ["g"] = 0.8, ["b"] = 1 },
    ["castBarEmpowerStage2Color"] = { ["a"] = 1, ["r"] = 0.26, ["g"] = 0.9, ["b"] = 0.55 },
    ["buffBarShowApplications"] = true,
    ["trinketsOffsetX"] = 0,
    ["cooldownFontSize"] = 16,
    ["castBarIconGap"] = 1,
    ["buffBarIconPosition"] = "LEFT",
    ["resourcesHolyPowerColor"] = { ["a"] = 1, ["r"] = 0.95, ["g"] = 0.9, ["b"] = 0.6 },
    ["utilityYOffset"] = 0,
    ["assistColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["assistFontSize"] = 10,
    ["racialsChargePosition"] = "BOTTOM",
    ["defensivesHideFromViewers"] = true,
    ["castBarChannelColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 0.31, ["b"] = 0.26 },
    ["castBarEmpowerStage1Color"] = { ["a"] = 1, ["r"] = 0.26, ["g"] = 0.65, ["b"] = 1 },
    ["racialsPartyFrameOffsetY"] = 20,
    ["resourcesManaColor"] = { ["a"] = 1, ["r"] = 0, ["g"] = 0.56, ["b"] = 1 },
    ["sizeBuff"] = { ["w"] = 40, ["h"] = 36 },
    ["resourcesLunarPowerColor"] = { ["a"] = 1, ["r"] = 0.3, ["g"] = 0.52, ["b"] = 0.9 },
    ["castBarOffsetY"] = -166,
    ["glowProcDuration"] = 1,
    ["racialsCooldownFontSize"] = 16,
    ["glowAutocastParticles"] = 4,
    ["utilityXOffset"] = 0,
    ["buffBarGrowDirection"] = "DOWN",
    ["resourcesFocusColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 0.5, ["b"] = 0.25 },
    ["buffSecondaryOffsetX"] = -120,
    ["glowProcXOffset"] = 0,
    ["borderSize"] = 1,
    ["borderFile"] = "1 Pixel",
    ["defensivesIconHeight"] = 36,
    ["resourcesOffsetY"] = -200,
    ["racialsAnchorPoint"] = "TOPRIGHT",
    ["castBarEmpowerWindUpColor"] = { ["a"] = 1, ["r"] = 0.45, ["g"] = 0.45, ["b"] = 0.55 },
    ["buffBarSpacing"] = 1,
    ["castBarIconPosition"] = "LEFT",
    ["castBarEmpowerStage3Color"] = { ["a"] = 1, ["r"] = 1, ["g"] = 0.8, ["b"] = 0 },
    ["castBarShowSpellName"] = true,
    ["assistEnabled"] = true,
    ["chargeOffsetX"] = 0,
    ["fadingOpacity"] = 30,
    ["rotationAssistGlowRatio"] = 0.33,
    ["sizeEssRow1"] = { ["w"] = 46, ["h"] = 40 },
    ["resourcesMaelstromColor"] = { ["a"] = 1, ["r"] = 0, ["g"] = 0.5, ["b"] = 1 },
    ["castBarOffsetX"] = 0,
    ["buffBarNameFontSize"] = 16,
    ["castBarEnabled"] = true,
    ["resourcesBar2TagAnchor"] = "CENTER",
    ["resourcesSoulShardsColor"] = { ["a"] = 1, ["r"] = 0.58, ["g"] = 0.51, ["b"] = 0.79 },
    ["racialsChargeOffsetY"] = 0,
    ["buffBarBackgroundColor"] = { ["a"] = 0.8, ["r"] = 0.1, ["g"] = 0.1, ["b"] = 0.1 },
    ["glowPixelFrequency"] = 0.2,
    ["chargePosition"] = "BOTTOMRIGHT",
    ["castBarWidth"] = 0,
    ["resourcesBarTexture"] = "Solid",
    ["textFontOutline"] = "OUTLINE",
    ["trinketsOffsetY"] = 0,
    ["buffBarDurationColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["defensivesOffsetX"] = 0,
    ["defensivesChargePosition"] = "TOP",
    ["buffBarApplicationsOffsetY"] = 0,
    ["defensivesChargeFontSize"] = 12,
    ["buffBarDualMode"] = false,
    ["borderColor"] = { ["a"] = 1, ["r"] = 0, ["g"] = 0, ["b"] = 0 },
    ["racialsChargeColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["fadingTriggerNoTarget"] = true,
    ["fadingTriggerOOC"] = false,
    ["fadingTriggerMounted"] = false,
    ["hideDebuffBorder"] = true,
    ["fadingEnabled"] = true,
    ["glowColor"] = { ["a"] = 1, ["r"] = 0.95, ["g"] = 0.95, ["b"] = 0.32 },
    ["trinketsEnabled"] = true,
    ["buffContainerLocked"] = true,
    ["assistOffsetY"] = 0,
    ["editModePositions"] = {
        ["BuffIconCooldownViewer"] = { ["Default"] = { ["y"] = -149, ["x"] = 0, ["point"] = "CENTER" } },
        ["EssentialCooldownViewer"] = { ["Default"] = { ["y"] = -202, ["x"] = 0, ["point"] = "CENTER" } },
        ["BuffBarCooldownViewer"] = { ["Default"] = { ["y"] = 300, ["x"] = 0, ["point"] = "BOTTOM" } },
    },
    ["racialsOffsetY"] = 38,
    ["resourcesRunesRechargingColor"] = { ["a"] = 1, ["r"] = 0.3, ["g"] = 0.3, ["b"] = 0.3 },
    ["glowAutocastYOffset"] = 0,
    ["castBarCastColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 0.7, ["b"] = 0 },
    ["castBarUseClassColor"] = true,
    ["defensivesCooldownFontSize"] = 16,
    ["glowProcYOffset"] = 0,
    ["utilityUnlock"] = false,
    ["defensivesChargeOffsetY"] = 1,
    ["fadingTrinkets"] = true,
    ["castBarTimerOffsetX"] = -2,
    ["buffBarNameOffsetX"] = 2,
    ["borderOffsetY"] = 0,
    ["utilityVertical"] = false,
    ["buffTertiaryOffsetX"] = 120,
    ["castBarShowSpark"] = true,
    ["castBarNameOffsetY"] = 6,
    ["castBarTexture"] = "TukTex",
    ["assistOffsetX"] = 0,
    ["resourcesSoulShardsRechargingColor"] = { ["a"] = 1, ["r"] = 0.35, ["g"] = 0.3, ["b"] = 0.5 },
    ["castBarUninterruptibleColor"] = { ["a"] = 1, ["r"] = 0.7, ["g"] = 0.7, ["b"] = 0.7 },
    ["resourcesEssenceRechargingColor"] = { ["a"] = 1, ["r"] = 0.08, ["g"] = 0.28, ["b"] = 0.25 },
    ["sizeUtility"] = { ["w"] = 26, ["h"] = 24 },
    ["buffBarApplicationsOffsetX"] = 0,
    ["buffBarNameOffsetY"] = 0,
    ["castBarEmpowerStage4Color"] = { ["a"] = 1, ["r"] = 1, ["g"] = 0.35, ["b"] = 0 },
    ["racialsEnabled"] = true,
    ["buffSecondaryOffsetY"] = 1,
    ["rotationAssistEnabled"] = false,
    ["resourcesStaggerHeavyColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 0.42, ["b"] = 0.42 },
    ["assistPosition"] = "TOPRIGHT",
    ["buffBarDurationOffsetY"] = 0,
    ["resourcesBar1TagAnchor"] = "CENTER",
    ["resourcesBar2TagFontSize"] = 16,
    ["sizeBuffTertiary"] = { ["w"] = 40, ["h"] = 36 },
    ["castBarUseAtlasTextures"] = false,
    ["trinketsShowPassive"] = false,
    ["glowPixelLength"] = 0,
    ["racialsIconHeight"] = 36,
    ["countOffsetXSec"] = 4,
    ["resourcesInsanityColor"] = { ["a"] = 1, ["r"] = 0.4, ["g"] = 0, ["b"] = 0.8 },
    ["resourcesChiColor"] = { ["a"] = 1, ["r"] = 0.71, ["g"] = 1, ["b"] = 0.92 },
    ["glowPixelXOffset"] = 0,
    ["resourcesEssenceColor"] = { ["a"] = 1, ["r"] = 0.16, ["g"] = 0.57, ["b"] = 0.49 },
    ["buffBarApplicationsPosition"] = "CENTER",
    ["resourcesRunicPowerColor"] = { ["a"] = 1, ["r"] = 0, ["g"] = 0.82, ["b"] = 1 },
    ["buffBarWidth"] = 0,
    ["resourcesBar1TagOffsetY"] = 0,
    ["buffBarApplicationsColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["fadingRacials"] = true,
    ["buffTertiaryOffsetY"] = 1,
    ["defensivesOffsetY"] = 0,
    ["resourcesOffsetX"] = 0,
    ["borderFile"] = "1 Pixel",
    ["castBarNameOffsetX"] = 2,
    ["glowAutocastScale"] = 1,
    ["resourcesBar2TagOffsetY"] = 0,
    ["defensivesEnabled"] = true,
    ["resourcesBar2TagOffsetX"] = 0,
    ["buffBarDurationOffsetX"] = -2,
    ["fadingUtility"] = true,
    ["maxRowEss"] = 8,
    ["buffBarContainerLocked"] = true,
    ["fadingResources"] = true,
    ["countOffsetYTert"] = 0,
    ["resourcesArcaneChargesColor"] = { ["a"] = 1, ["r"] = 0.1, ["g"] = 0.1, ["b"] = 0.98 },
    ["sizeBuffSecondary"] = { ["w"] = 40, ["h"] = 36 },
    ["trinketsEssentialPosition"] = "end",
    ["castBarContainerLocked"] = true,
    ["castBarShowIcon"] = true,
    ["castBarShowTimer"] = true,
    ["countOffsetYMain"] = 0,
    ["countFontSize"] = 12,
    ["countPositionSec"] = "RIGHT",
    ["zoomIcons"] = true,
    ["glowButtonFrequency"] = 0,
    ["countColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["defensivesIconWidth"] = 40,
    ["hidePandemicIndicator"] = true,
    ["glowAutocastFrequency"] = 0.2,
    ["defensivesChargeOffsetX"] = 0,
    ["resourcesFuryColor"] = { ["a"] = 1, ["r"] = 0.79, ["g"] = 0.26, ["b"] = 0.99 },
    ["resourcesBar2TagColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["fadingDefensives"] = true,
    ["resourcesComboPointsColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 0.96, ["b"] = 0.41 },
    ["countOffsetXTert"] = -4,
    ["castBarBackgroundColor"] = { ["a"] = 0.8, ["r"] = 0.15, ["g"] = 0.15, ["b"] = 0.15 },
    ["castBarBackgroundTexture"] = "TukTex",
    ["resourcesBarBackgroundTexture"] = "Solid",
    ["chargeOffsetY"] = 0,
    ["countOffsetYSec"] = 0,
    ["fadingEssential"] = true,
    ["racialsChargeOffsetX"] = 0,
    ["borderOffsetX"] = 0,
    ["castBarResourcesSpacing"] = 2,
    ["resourcesMoveBuffsDown"] = false,
    ["racialsOffsetX"] = 0,
    ["trinketsMode"] = "defensives",
    ["trinketsCooldownFontSize"] = 16,
    ["buffBarColor"] = { ["a"] = 1, ["r"] = 0.4, ["g"] = 0.6, ["b"] = 0.9 },
    ["fadingBuffBars"] = true,
    ["resourcesBarHeight"] = 16,
    ["resourcesBar1TagColor"] = { ["a"] = 1, ["r"] = 1, ["g"] = 1, ["b"] = 1 },
    ["buffBarShowName"] = true,
}

-- 首次安裝注入：Ayije_CDMDB 不存在時建立預設設定檔
-- 注意：OptionalDeps 使 MiliUI 先載入，此時 Ayije_CDMDB 永遠為 nil。
-- 若玩家已有 SavedVariables，WoW 在載入 Ayije_CDM 時會覆蓋此值，所以不影響既有設定。
if not Ayije_CDMDB then
    Ayije_CDMDB = {
        ["global"] = {},
        ["profileKeys"] = {},
        ["specProfiles"] = {},
        ["profiles"] = {
            ["Default"] = MiliUI_AyijeCDM_Profile,
        },
    }
end