MiliUI_Luxthos_SenseiDB = {
    ["_Settings"] = {
        ["HealthColors"] = {
            ["HEALTH"] = {
                ["a"] = 1,
                ["r"] = 0.2823529541492462,
                ["g"] = 0.8509804606437683,
                ["b"] = 0.3529411852359772,
            },
        },
        ["PowerColors"] = {
            {
                ["a"] = 1,
                ["r"] = 0.8352941870689392,
                ["g"] = 0.168627455830574,
                ["b"] = 0.03529411926865578,
            },
            {
                ["a"] = 1,
                ["b"] = 0.250980406999588,
                ["g"] = 0.501960813999176,
                ["r"] = 1,
            },
            {
                ["a"] = 1,
                ["r"] = 0.9647059440612793,
                ["g"] = 0.8000000715255737,
                ["b"] = 0.07058823853731155,
            },
            nil,
            {
                ["r"] = 0.3176470696926117,
                ["g"] = 0.8274510502815247,
                ["b"] = 0.3019607961177826,
            },
            {
                ["a"] = 1,
                ["b"] = 0.9254902601242065,
                ["g"] = 0.7372549176216125,
                ["r"] = 0.2980392277240753,
            },
            {
                ["a"] = 1,
                ["r"] = 0.7254902124404907,
                ["g"] = 0.3254902064800263,
                ["b"] = 0.9254902601242065,
            },
            {
                ["a"] = 1,
                ["r"] = 0.7725490927696228,
                ["g"] = 0.3372549116611481,
                ["b"] = 0.9098039865493774,
            },
            {
                ["a"] = 1,
                ["r"] = 1,
                ["g"] = 0.7411764860153198,
                ["b"] = 0.2039215862751007,
            },
            nil,
            {
                ["a"] = 1,
                ["r"] = 0.2862745225429535,
                ["g"] = 0.6745098233222961,
                ["b"] = 0.8784314393997192,
            },
            nil,
            {
                ["a"] = 1,
                ["r"] = 0.6470588445663452,
                ["g"] = 0.2901960909366608,
                ["b"] = 1,
            },
            nil,
            nil,
            {
                ["a"] = 1,
                ["b"] = 0.9803922176361084,
                ["g"] = 0.2352941334247589,
                ["r"] = 0.3411764800548554,
            },
            {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 0.2235294282436371,
                ["r"] = 0.7843137979507446,
            },
            nil,
            nil,
            {
                ["a"] = 1,
                ["b"] = 0.1960784494876862,
                ["g"] = 0.1882353127002716,
                ["r"] = 0.6901960968971252,
            },
            {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 0.6117647290229797,
                ["r"] = 0,
            },
            {
                ["a"] = 1,
                ["b"] = 0.3960784673690796,
                ["g"] = 0.9058824181556702,
                ["r"] = 0.4627451300621033,
            },
            ["SOUL_FRAGMENTS"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 0.2705882489681244,
                ["r"] = 0.4627451300621033,
            },
            [0] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 0.6235294342041016,
                ["r"] = 0.1843137294054031,
            },
        },
        ["NewFeaturesShown"] = {
            ["SCRB_POWER_COLORS"] = true,
        },
    },
    ["SecondaryResourceBarDB"] = {
        ["米利"] = {
            ["backgroundStyle"] = "SCRB Semi-transparent",
            ["fontSize"] = 15,
            ["point"] = "TOP",
            ["scale"] = 1,
            ["showManaAsPercent"] = false,
            ["smoothProgress"] = true,
            ["hideBlizzardSecondaryResourceUi"] = true,
            ["barVisible"] = "Always Visible",
            ["showFragmentedPowerBarText"] = false,
            ["fontOutline"] = "OUTLINE",
            ["hideManaOnRole"] = {
                ["DAMAGER"] = true,
            },
            ["hideManaOnDps"] = true,
            ["tickThickness"] = 1,
            ["showTicks"] = true,
            ["fillDirection"] = "Left to Right",
            ["textFormat"] = "Percent%",
            ["useResourceAtlas"] = false,
            ["foregroundStyle"] = "Solid",
            ["widthMode"] = "Sync With Essential Cooldowns",
            ["maskAndBorderStyle"] = "1 Pixel",
            ["x"] = 0,
            ["width"] = 200,
            ["y"] = 1,
            ["font"] = "Fonts\\FRIZQT__.TTF",
            ["showText"] = false,
            ["relativeFrame"] = "Primary Resource Bar",
            ["height"] = 20,
            ["textAlign"] = "CENTER",
            ["positionMode"] = "Use Primary Resource Bar Position If Hidden",
            ["relativePoint"] = "BOTTOM",
        },
        ["現代模式"] = {
            ["backgroundStyle"] = "SCRB Semi-transparent",
            ["showManaAsPercent"] = false,
            ["barVisible"] = "Always Visible",
            ["borderColor"] = {
                ["a"] = 1,
                ["b"] = 0,
                ["g"] = 0,
                ["r"] = 0,
            },
            ["hideManaOnRole"] = {
            },
            ["backgroundColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["foregroundStyle"] = "SCRB FG Fade Left",
            ["maskAndBorderStyle"] = "Thin",
            ["y"] = -40,
            ["x"] = 0,
            ["showText"] = true,
            ["relativeFrame"] = "UIParent",
            ["height"] = 15,
            ["barStrata"] = "MEDIUM",
            ["useStatusBarColorForBackgroundColor"] = false,
            ["showTicks"] = true,
            ["fontSize"] = 12,
            ["point"] = "CENTER",
            ["fasterUpdates"] = true,
            ["scale"] = 1,
            ["minWidth"] = 0,
            ["smoothProgress"] = true,
            ["tickColor"] = {
                ["a"] = 1,
                ["r"] = 0,
                ["g"] = 0,
                ["b"] = 0,
            },
            ["hideBlizzardSecondaryResourceUi"] = false,
            ["showFragmentedPowerBarText"] = false,
            ["relativePoint"] = "CENTER",
            ["enableOverlayToggle"] = true,
            ["settingsMaxHeight"] = 1431.6,
            ["fillDirection"] = "Left to Right",
            ["fragmentedPowerBarTextColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["textPrecision"] = "12",
            ["textFormat"] = "Current",
            ["tickThickness"] = 1,
            ["font"] = "Fonts\\bLEI00D.ttf",
            ["width"] = 200,
            ["fragmentedPowerBarTextPrecision"] = "12.3",
            ["fontOutline"] = "OUTLINE",
            ["widthMode"] = "Manual",
            ["positionMode"] = "Self",
            ["useResourceAtlas"] = false,
            ["textAlign"] = "CENTER",
            ["hideWhileMountedOrVehicule"] = false,
            ["textColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
        },
    },
    ["tertiaryResourceBarDB"] = {
        ["米利"] = {
            ["backgroundStyle"] = "SCRB Semi-transparent",
            ["fontSize"] = 14,
            ["point"] = "CENTER",
            ["fasterUpdates"] = true,
            ["scale"] = 1,
            ["minWidth"] = 0,
            ["smoothProgress"] = true,
            ["textColor"] = {
                ["a"] = 1,
                ["r"] = 1,
                ["g"] = 1,
                ["b"] = 1,
            },
            ["hideWhileMountedOrVehicule"] = false,
            ["barVisible"] = "Always Visible",
            ["showFragmentedPowerBarText"] = false,
            ["fontOutline"] = "OUTLINE",
            ["widthMode"] = "Sync With Essential Cooldowns",
            ["barStrata"] = "MEDIUM",
            ["backgroundColor"] = {
                ["a"] = 1,
                ["r"] = 1,
                ["g"] = 1,
                ["b"] = 1,
            },
            ["useResourceAtlas"] = false,
            ["fillDirection"] = "Left to Right",
            ["foregroundStyle"] = "Solid",
            ["textFormat"] = "Percent",
            ["textPrecision"] = "12",
            ["x"] = 0,
            ["maskAndBorderStyle"] = "1 Pixel",
            ["enableOverlayToggle"] = true,
            ["width"] = 200,
            ["y"] = -208,
            ["font"] = "Fonts\\FRIZQT__.TTF",
            ["showText"] = true,
            ["fragmentedPowerBarTextPrecision"] = "12.3",
            ["height"] = 20,
            ["textAlign"] = "CENTER",
            ["borderColor"] = {
                ["a"] = 1,
                ["r"] = 0,
                ["g"] = 0,
                ["b"] = 0,
            },
            ["fragmentedPowerBarTextColor"] = {
                ["a"] = 1,
                ["r"] = 1,
                ["g"] = 1,
                ["b"] = 1,
            },
        },
        ["現代模式"] = {
            ["fragmentedPowerBarTextPrecision"] = "12.3",
            ["barVisible"] = "Always Visible",
            ["fontOutline"] = "OUTLINE",
            ["backgroundColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["foregroundStyle"] = "SCRB FG Fade Left",
            ["maskAndBorderStyle"] = "Thin",
            ["y"] = -80,
            ["x"] = 0,
            ["showText"] = true,
            ["relativeFrame"] = "UIParent",
            ["height"] = 15,
            ["barStrata"] = "MEDIUM",
            ["useStatusBarColorForBackgroundColor"] = false,
            ["fontSize"] = 12,
            ["point"] = "CENTER",
            ["fasterUpdates"] = true,
            ["widthMode"] = "Manual",
            ["minWidth"] = 0,
            ["smoothProgress"] = true,
            ["hideWhileMountedOrVehicule"] = false,
            ["showFragmentedPowerBarText"] = false,
            ["relativePoint"] = "CENTER",
            ["enableOverlayToggle"] = true,
            ["settingsMaxHeight"] = 1431.6,
            ["fillDirection"] = "Left to Right",
            ["textPrecision"] = "12",
            ["fragmentedPowerBarTextColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["width"] = 200,
            ["textFormat"] = "Current",
            ["borderColor"] = {
                ["a"] = 1,
                ["b"] = 0,
                ["g"] = 0,
                ["r"] = 0,
            },
            ["font"] = "Fonts\\bLEI00D.ttf",
            ["backgroundStyle"] = "SCRB Semi-transparent",
            ["scale"] = 1,
            ["textAlign"] = "CENTER",
            ["useResourceAtlas"] = false,
            ["textColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
        },
    },
    ["PrimaryResourceBarDB"] = {
        ["米利"] = {
            ["backgroundStyle"] = "SCRB Semi-transparent",
            ["fontSize"] = 14,
            ["point"] = "TOP",
            ["widthMode"] = "Sync With Essential Cooldowns",
            ["showManaAsPercent"] = true,
            ["smoothProgress"] = true,
            ["barVisible"] = "Always Visible",
            ["showFragmentedPowerBarText"] = false,
            ["relativePoint"] = "BOTTOM",
            ["hideManaOnRole"] = {
                ["DAMAGER"] = true,
            },
            ["fillDirection"] = "Left to Right",
            ["fontOutline"] = "OUTLINE",
            ["scale"] = 1,
            ["maskAndBorderStyle"] = "1 Pixel",
            ["useResourceAtlas"] = false,
            ["width"] = 200,
            ["y"] = 1,
            ["x"] = 0,
            ["showText"] = true,
            ["relativeFrame"] = "Essential Cooldowns",
            ["height"] = 20,
            ["textAlign"] = "CENTER",
            ["font"] = "Fonts\\FRIZQT__.TTF",
            ["foregroundStyle"] = "Solid",
        },
        ["現代模式"] = {
            ["backgroundStyle"] = "SCRB Semi-transparent",
            ["showManaAsPercent"] = false,
            ["barVisible"] = "Always Visible",
            ["borderColor"] = {
                ["a"] = 1,
                ["b"] = 0,
                ["g"] = 0,
                ["r"] = 0,
            },
            ["hideManaOnRole"] = {
            },
            ["backgroundColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["foregroundStyle"] = "SCRB FG Fade Left",
            ["maskAndBorderStyle"] = "Thin",
            ["y"] = 0,
            ["x"] = 0,
            ["showText"] = true,
            ["relativeFrame"] = "UIParent",
            ["height"] = 15,
            ["barStrata"] = "MEDIUM",
            ["useStatusBarColorForBackgroundColor"] = false,
            ["showTicks"] = true,
            ["fontSize"] = 12,
            ["point"] = "CENTER",
            ["fasterUpdates"] = true,
            ["scale"] = 1,
            ["minWidth"] = 0,
            ["smoothProgress"] = true,
            ["tickColor"] = {
                ["a"] = 1,
                ["r"] = 0,
                ["g"] = 0,
                ["b"] = 0,
            },
            ["hideWhileMountedOrVehicule"] = false,
            ["showFragmentedPowerBarText"] = false,
            ["relativePoint"] = "CENTER",
            ["enableOverlayToggle"] = true,
            ["settingsMaxHeight"] = 1431.6,
            ["fillDirection"] = "Left to Right",
            ["textPrecision"] = "12",
            ["fragmentedPowerBarTextColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["textFormat"] = "Current",
            ["width"] = 200,
            ["useResourceAtlas"] = false,
            ["font"] = "Fonts\\bLEI00D.ttf",
            ["fragmentedPowerBarTextPrecision"] = "12.3",
            ["fontOutline"] = "OUTLINE",
            ["widthMode"] = "Manual",
            ["textAlign"] = "CENTER",
            ["tickThickness"] = 1,
            ["textColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
        },
    },
    ["healthBarDB"] = {
        ["米利"] = {
            ["backgroundStyle"] = "SCRB Semi-transparent",
            ["fontSize"] = 14,
            ["point"] = "TOP",
            ["widthMode"] = "Sync With Essential Cooldowns",
            ["smoothProgress"] = true,
            ["barVisible"] = "Hidden",
            ["showFragmentedPowerBarText"] = false,
            ["relativePoint"] = "BOTTOM",
            ["backgroundColor"] = {
                ["a"] = 1,
                ["r"] = 1,
                ["g"] = 1,
                ["b"] = 1,
            },
            ["fontOutline"] = "OUTLINE",
            ["fillDirection"] = "Left to Right",
            ["foregroundStyle"] = "Solid",
            ["scale"] = 1,
            ["font"] = "Fonts\\FRIZQT__.TTF",
            ["maskAndBorderStyle"] = "1 Pixel",
            ["hideBlizzardPlayerContainerUi"] = false,
            ["width"] = 200,
            ["y"] = 1,
            ["x"] = 0,
            ["showText"] = false,
            ["relativeFrame"] = "Secondary Resource Bar",
            ["height"] = 10,
            ["textAlign"] = "CENTER",
            ["useClassColor"] = false,
            ["textFormat"] = "Percent%",
        },
        ["現代模式"] = {
            ["backgroundStyle"] = "SCRB Semi-transparent",
            ["barVisible"] = "Hidden",
            ["borderColor"] = {
                ["a"] = 1,
                ["b"] = 0,
                ["g"] = 0,
                ["r"] = 0,
            },
            ["backgroundColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["textFormat"] = "Current",
            ["maskAndBorderStyle"] = "Thin",
            ["y"] = 40,
            ["x"] = 0,
            ["showText"] = true,
            ["relativeFrame"] = "UIParent",
            ["height"] = 15,
            ["barStrata"] = "MEDIUM",
            ["useStatusBarColorForBackgroundColor"] = false,
            ["fontSize"] = 12,
            ["point"] = "CENTER",
            ["fasterUpdates"] = true,
            ["widthMode"] = "Manual",
            ["minWidth"] = 0,
            ["smoothProgress"] = true,
            ["hideHealthOnRole"] = {
            },
            ["showFragmentedPowerBarText"] = false,
            ["relativePoint"] = "CENTER",
            ["enableOverlayToggle"] = true,
            ["settingsMaxHeight"] = 1431.6,
            ["fillDirection"] = "Left to Right",
            ["textPrecision"] = "12",
            ["fragmentedPowerBarTextColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["foregroundStyle"] = "SCRB FG Fade Left",
            ["hideBlizzardPlayerContainerUi"] = false,
            ["width"] = 200,
            ["hideWhileMountedOrVehicule"] = false,
            ["font"] = "Fonts\\bLEI00D.ttf",
            ["fragmentedPowerBarTextPrecision"] = "12.3",
            ["fontOutline"] = "OUTLINE",
            ["scale"] = 1,
            ["textAlign"] = "CENTER",
            ["useClassColor"] = true,
            ["textColor"] = {
                ["a"] = 1,
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
        },
    },
}
