MiliUI_Luxthos_SenseiDB = {
    ["_Settings"] = {
            ["HealthColors"] = {
                ["HEALTH"] = {
                    ["a"] = 1,
                    ["b"] = 0.35294118523598,
                    ["g"] = 0.85098046064377,
                    ["r"] = 0.28235295414925,
                },
            },
            ["PowerColors"] = {
                {
                    ["a"] = 1,
                    ["b"] = 0.035294119268656,
                    ["g"] = 0.16862745583057,
                    ["r"] = 0.83529418706894,
                },
                {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 0.50196081399918,
                    ["b"] = 0.25098040699959,
                },
                {
                    ["a"] = 1,
                    ["b"] = 0.070588238537312,
                    ["g"] = 0.80000007152557,
                    ["r"] = 0.96470594406128,
                },
                nil,
                {
                    ["b"] = 0.30196079611778,
                    ["g"] = 0.82745105028152,
                    ["r"] = 0.31764706969261,
                },
                {
                    ["a"] = 1,
                    ["r"] = 0.29803922772408,
                    ["g"] = 0.73725491762161,
                    ["b"] = 0.92549026012421,
                },
                {
                    ["a"] = 1,
                    ["b"] = 0.92549026012421,
                    ["g"] = 0.32549020648003,
                    ["r"] = 0.72549021244049,
                },
                {
                    ["a"] = 1,
                    ["b"] = 0.90980398654938,
                    ["g"] = 0.33725491166115,
                    ["r"] = 0.77254909276962,
                },
                {
                    ["a"] = 1,
                    ["b"] = 0.2039215862751,
                    ["g"] = 0.74117648601532,
                    ["r"] = 1,
                },
                nil,
                {
                    ["a"] = 1,
                    ["b"] = 0.87843143939972,
                    ["g"] = 0.6745098233223,
                    ["r"] = 0.28627452254295,
                },
                nil,
                {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 0.29019609093666,
                    ["r"] = 0.64705884456635,
                },
                nil,
                nil,
                {
                    ["a"] = 1,
                    ["r"] = 0.34117648005486,
                    ["g"] = 0.23529413342476,
                    ["b"] = 0.98039221763611,
                },
                {
                    ["a"] = 1,
                    ["r"] = 0.78431379795074,
                    ["g"] = 0.22352942824364,
                    ["b"] = 1,
                },
                nil,
                nil,
                {
                    ["a"] = 1,
                    ["r"] = 0.69019609689713,
                    ["g"] = 0.18823531270027,
                    ["b"] = 0.19607844948769,
                },
                {
                    ["a"] = 1,
                    ["r"] = 0,
                    ["g"] = 0.61176472902298,
                    ["b"] = 1,
                },
                {
                    ["a"] = 1,
                    ["r"] = 0.4627451300621,
                    ["g"] = 0.90588241815567,
                    ["b"] = 0.39607846736908,
                },
                ["WHIRLWIND"] = {
                    ["a"] = 1,
                    ["b"] = 0.96470594406128,
                    ["g"] = 0.75294125080109,
                    ["r"] = 0,
                },
                [0] = {
                    ["a"] = 1,
                    ["r"] = 0.1843137294054,
                    ["g"] = 0.6235294342041,
                    ["b"] = 1,
                },
                ["SOUL_FRAGMENTS"] = {
                    ["a"] = 1,
                    ["r"] = 0.4627451300621,
                    ["g"] = 0.27058824896812,
                    ["b"] = 1,
                },
            },
            ["NewFeaturesShown"] = {
                ["SCRB_POWER_COLORS"] = true,
            },
    },
    ["PrimaryResourceBarDB"] = {
        ["MiliUI"] = {
                ["showTicks"] = false,
                ["fontSize"] = 14,
                ["point"] = "TOP",
                ["scale"] = 1,
                ["showManaAsPercent"] = true,
                ["smoothProgress"] = true,
                ["barVisible"] = "Always Visible",
                ["showFragmentedPowerBarText"] = false,
                ["fontOutline"] = "OUTLINE",
                ["hideManaOnRole"] = {
                    ["DAMAGER"] = true,
                },
                ["foregroundStyle"] = "Solid",
                ["backgroundStyle"] = "SCRB Semi-transparent",
                ["fillDirection"] = "Left to Right",
                ["relativePoint"] = "BOTTOM",
                ["maskAndBorderStyle"] = "1 Pixel",
                ["x"] = 0,
                ["width"] = 200,
                ["y"] = 1,
                ["font"] = "Fonts\\FRIZQT__.TTF",
                ["showText"] = true,
                ["relativeFrame"] = "Essential Cooldowns",
                ["height"] = 20,
                ["textAlign"] = "CENTER",
                ["widthMode"] = "Sync With Essential Cooldowns",
                ["useResourceAtlas"] = false,
        },
    },
    ["SecondaryResourceBarDB"] = {
        ["MiliUI"] = {
                ["showTicks"] = true,
                ["fontSize"] = 15,
                ["point"] = "TOP",
                ["widthMode"] = "Sync With Essential Cooldowns",
                ["showManaAsPercent"] = false,
                ["smoothProgress"] = true,
                ["hideBlizzardSecondaryResourceUi"] = true,
                ["barVisible"] = "Always Visible",
                ["showFragmentedPowerBarText"] = false,
                ["fontOutline"] = "OUTLINE",
                ["hideManaOnRole"] = {
                    ["DAMAGER"] = true,
                },
                ["backgroundStyle"] = "SCRB Semi-transparent",
                ["tickThickness"] = 1,
                ["fillDirection"] = "Left to Right",
                ["hideManaOnDps"] = true,
                ["textFormat"] = "Percent%",
                ["scale"] = 1,
                ["useResourceAtlas"] = false,
                ["x"] = 0,
                ["maskAndBorderStyle"] = "1 Pixel",
                ["relativePoint"] = "BOTTOM",
                ["width"] = 200,
                ["y"] = 1,
                ["font"] = "Fonts\\FRIZQT__.TTF",
                ["showText"] = false,
                ["relativeFrame"] = "Primary Resource Bar",
                ["height"] = 20,
                ["textAlign"] = "CENTER",
                ["positionMode"] = "Use Primary Resource Bar Position If Hidden",
                ["foregroundStyle"] = "Solid",
        },
    },
    ["tertiaryResourceBarDB"] = {
        ["MiliUI"] = {
                ["fragmentedPowerBarTextPrecision"] = "12.3",
                ["fontSize"] = 14,
                ["point"] = "CENTER",
                ["fasterUpdates"] = true,
                ["widthMode"] = "Sync With Essential Cooldowns",
                ["minWidth"] = 0,
                ["smoothProgress"] = true,
                ["useResourceAtlas"] = false,
                ["hideWhileMountedOrVehicule"] = false,
                ["barVisible"] = "Always Visible",
                ["showFragmentedPowerBarText"] = false,
                ["fontOutline"] = "OUTLINE",
                ["fillDirection"] = "Left to Right",
                ["textColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["enableOverlayToggle"] = true,
                ["barStrata"] = "MEDIUM",
                ["scale"] = 1,
                ["textFormat"] = "Percent",
                ["foregroundStyle"] = "Solid",
                ["textPrecision"] = "12",
                ["x"] = 0,
                ["maskAndBorderStyle"] = "1 Pixel",
                ["borderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["width"] = 200,
                ["y"] = -208,
                ["font"] = "Fonts\\FRIZQT__.TTF",
                ["showText"] = true,
                ["backgroundStyle"] = "SCRB Semi-transparent",
                ["height"] = 20,
                ["textAlign"] = "CENTER",
                ["backgroundColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["fragmentedPowerBarTextColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
        },
    },
    ["healthBarDB"] = {
        ["MiliUI"] = {
                ["backgroundStyle"] = "SCRB Semi-transparent",
                ["fontSize"] = 14,
                ["point"] = "TOP",
                ["widthMode"] = "Sync With Essential Cooldowns",
                ["smoothProgress"] = true,
                ["barVisible"] = "Hidden",
                ["showFragmentedPowerBarText"] = false,
                ["fontOutline"] = "OUTLINE",
                ["backgroundColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["foregroundStyle"] = "Solid",
                ["textFormat"] = "Percent%",
                ["fillDirection"] = "Left to Right",
                ["scale"] = 1,
                ["x"] = 0,
                ["maskAndBorderStyle"] = "1 Pixel",
                ["hideBlizzardPlayerContainerUi"] = false,
                ["width"] = 200,
                ["y"] = 1,
                ["font"] = "Fonts\\FRIZQT__.TTF",
                ["showText"] = false,
                ["relativeFrame"] = "Secondary Resource Bar",
                ["height"] = 10,
                ["textAlign"] = "CENTER",
                ["useClassColor"] = false,
                ["relativePoint"] = "BOTTOM",
        },
    },
}
