local frame = CreateFrame("FRAME")
frame:RegisterEvent("ADDON_LOADED")
function frame:OnEvent(event, arg1)
	if event == "ADDON_LOADED" and arg1 == "Blizzard_PVPUI" then
		HonorFrame.BonusFrame.WorldBattlesTexture:Hide()
		WarGamesFrame.HorizontalBar:Hide()
		local wargamesscroll = select(2,WarGamesFrameInfoScrollFrameScrollBar:GetRegions())
		wargamesscroll:Hide()
		local wargamesscroll2 = select(1,WarGamesFrame:GetRegions())
		wargamesscroll2:Hide()
		local ring1 = select(2,PVPQueueFrameCategoryButton1:GetRegions())
		ring1:Hide()
		local icon1 = select(3,PVPQueueFrameCategoryButton1:GetRegions())
		icon1:SetTexCoord(0.85, 0.15, 0.15, 0.85)
		icon1:SetWidth(46)
		icon1:SetHeight(46)
		local ring2 = select(2,PVPQueueFrameCategoryButton2:GetRegions())
		ring2:Hide()
		local icon2 = select(3,PVPQueueFrameCategoryButton2:GetRegions())
		icon2:SetTexCoord(0.85, 0.15, 0.15, 0.85)
		icon2:SetWidth(46)
		icon2:SetHeight(46)
		local ring3 = select(2,PVPQueueFrameCategoryButton3:GetRegions())
		ring3:Hide()
		local icon3 = select(3,PVPQueueFrameCategoryButton3:GetRegions())
		icon3:SetTexCoord(0.85, 0.15, 0.15, 0.85)
		icon3:SetWidth(46)
		icon3:SetHeight(46)
		local ring4 = select(2,PVPQueueFrameCategoryButton4:GetRegions())
		ring4:Hide()
		local icon4 = select(3,PVPQueueFrameCategoryButton4:GetRegions())
		icon4:SetTexCoord(0.85, 0.15, 0.15, 0.85)
		icon4:SetWidth(46)
		icon4:SetHeight(46)
		PVPReadyDialogBackground:Hide()
		ConquestFrame.RoleInset.Background:Hide()
		HonorFrame.BonusFrame.Arena1Button.Reward.Border:Hide()
		HonorFrame.BonusFrame.Arena1Button.Reward.Icon:SetTexCoord(0.85, 0.15, 0.15, 0.85)		
		HonorFrame.RoleInset.Background:Hide()
		HonorFrame.BonusFrame.RandomBGButton.Reward.Border:Hide()
		HonorFrame.BonusFrame.RandomBGButton.Reward.Icon:SetTexCoord(0.85, 0.15, 0.15, 0.85)	
		m_border(PVPQueueFrameCategoryButton1,50,50,"LEFT",10,0,14,"MEDIUM")
		m_fontify(PVPQueueFrameCategoryButton1.Name,"white")
		m_border(PVPQueueFrameCategoryButton2,50,50,"LEFT",10,0,14,"MEDIUM")
		m_fontify(PVPQueueFrameCategoryButton2.Name,"white")
		m_border(PVPQueueFrameCategoryButton3,50,50,"LEFT",10,0,14,"MEDIUM")
		m_fontify(PVPQueueFrameCategoryButton3.Name,"white")
		m_border(PVPQueueFrameCategoryButton4,50,50,"LEFT",10,0,14,"MEDIUM")
		m_fontify(PVPQueueFrameCategoryButton4.Name,"white")
		m_border(HonorFrame,332,240,"CENTER",0,-62,12,"HIGH")
		m_border(HonorFrame.RoleInset,332,64,"CENTER",0,0,14,"HIGH")
		m_border(HonorFrame.BonusFrame.RandomBGButton,38,38,"RIGHT",-11,0,12,"HIGH")
		m_border(HonorFrame.BonusFrame.Arena1Button,38,38,"RIGHT",-11,0,12,"HIGH")
		m_border(ConquestFrame.RoleInset,332,64,"CENTER",0,0,14,"HIGH")	
		m_border(ConquestFrame,331,266,"CENTER",-0.5,-44,12,"HIGH")
		m_border(WarGamesFrame,334,382,"CENTER",1.5,9,14,"HIGH")
		m_fontify(WarGamesFrameDescription,"white")
		
		PremadeGroupsPvPTutorialAlertBg:SetGradientAlpha("HORIZONTAL", 1, 1, 1, 1, 1, 1, 1, 1)
		PremadeGroupsPvPTutorialAlertBg:SetColorTexture(0.078,0.078,0.078,1)
		m_border(PremadeGroupsPvPTutorialAlert,226,156,"CENTER",0.5,0,14,"DIALOG")		
		m_fontify(PremadeGroupsPvPTutorialAlert.Text,"white")
		
	end
end

frame:SetScript("OnEvent", frame.OnEvent);