local folder,ns = ...
local opt = KuiNameplatesCoreConfig
-- strings
opt.page_names = {
    general     = '一般',
	healthbars  = '血量條',
	castbars    = '施法條',
    text        = '文字',
    framesizes  = '框架尺寸',
    auras       = '光環',
    classpowers = '職業能量',
    threat      = '威脅',
}
opt.tooltips = {
    bar_texture = '狀態條使用的材質(由LibSharedMedia提供)',
    bar_animation = '使用在血量/能量條的動態樣式',

    combat_hostile = '進入戰鬥後在敵對框架上採取的動作。 將在離開戰鬥後倒轉',
    combat_friendly = '進入戰鬥後在友方框架上採取的動作。將在離開戰鬥後倒轉',

    state_icons = '在首領與精英單位上顯示個圖標 (當等級文字顯示時隱藏)',

    nameonly = '隱藏友方或不可攻擊單位的血量條',
    nameonly_no_font_style = '當在獨顯名稱模式時隱藏文字描邊 (藉由將字體樣式設置為零)',
    nameonly_damaged_friends = '使用獨顯名稱模式，即使友方框架受到損傷。 他們的名字將會依照血量百分比來著色',
    nameonly_enemies = '使用獨顯名稱模式在不可攻擊敵人 (不包含在寒冰屏障影響下的敵對玩家)',
	nameonly_target = '也使用獨顯名稱模式在你的目標',
    nameonly_all_enemies = '使用獨顯名稱模式在所有敵對單位',
	
	target_arrows = '在你當前目標周圍顯示箭頭。這會繼承目標的光暈顏色',
	frame_glow_size = '使用在目標高亮與威脅指示的框架光暈尺寸',
	
    fade_alpha = '淡出框架的透明度',
    fade_speed = '框架淡出動化的速度，當 1 是最慢的 0 是馬上',
    fade_all = '預設狀態下淡出所有框架',
    fade_avoid_nameonly = '當在獨顯名稱模式時不要淡出框架',
    fade_avoid_raidicon = '當已標記團隊圖標時不要淡出框架',
	fade_friendly_npc = '預設淡出友方NPC血條(包含獨顯名稱模式)',
    fade_neutral_enemy = '預設淡出可攻擊的中立單位血條 (包含獨顯名稱模式)',
    fade_untracked = '預設淡出不可追蹤血條(包含獨顯名稱模式)。是否可以被追蹤可以透過在Esc > 介面 > 名稱中的"NPC名稱"選單來設置改變',

    colour_self_class = '自我血條使用自己的職業顏色',
    colour_self = '自我個人血條的血條顏色',
	
	execute_enabled = '重新著色血條當單位在斬殺階段時',
    execute_auto = '自動偵測你的天賦恰當的斬殺血量',
    execute_colour = '斬殺階段使用的顏色',
    execute_percent = '手動設置斬殺階段血量',
	
    hide_names = '不管單位是不是"不重要的"都可以在預設的介面選項"名稱"之下變更設置。注意這不影響獨顯名稱模式',
    font_face = '所有血條字串所使用的字型 (由LibSharedMedia提供)',
    font_size_normal = '標準字型尺寸 (名稱等等)',
    font_size_small = '小型字型尺寸(商店、法術名稱等等)',
    text_vertical_offset = '套用在所有字串的垂直偏移值。作為某些字體呈現在魔獸世界中奇特的垂直位置。注意該值預設是結束在.5這有助於當框架移動時減少垂直抖動',
    name_vertical_offset = '名稱文字的垂直偏移值',
    bot_vertical_offset = '等級與血量字串的垂直偏移值',

    health_text_friend_max = '使用在友方玩家滿血時的血量文字格式',
    health_text_friend_dmg = '使用在友方玩家損血時的血量文字格式',
    health_text_hostile_max = '使用在敵對玩家滿血時的血量文字格式',
    health_text_hostile_dmg = '使用在敵對玩家損血時的血量文字格式',
	
    frame_width = '標準血條寬度',
    frame_height = '標準血條高度',
    frame_width_minus = '低血量小怪血條寬度',
    frame_height_minus = '低血量小怪血條高度，以及無名字框架 (例如 "不重要" 單位)',
	powerbar_height = '能量條的高度。不會超過框架高度',

    auras_on_personal = '如果啟用顯示你角色血條的光環',
	auras_whitelist = '使用KuiSpellList來過濾法術。你可以使用在Curse上的額外KuiSpellListConfig插件來自訂此清單。',
    auras_pulsate = '當快要過期時閃耀圖標',
    auras_centre = '水平置中對齊框架上的圖標，而非從左側',
    auras_time_threshold = '當光環的剩餘時間少於這個數值時顯示倒數文字。設定為 -1 會永遠顯示此計時',
    auras_minimum_length = '不顯示初始長度少於此值的光環',
    auras_maximum_length = '不顯示初始長度大於此值的光環。設定 -1 為忽略',
    auras_icon_normal_size = '一般尺寸框架的圖標大小',
    auras_icon_minus_size = '小框架的圖標大小',
    auras_icon_squareness = '光環圖標的比例尺，當為1代表是正方形',

    castbar_enable = '啟用施法條元素',
    castbar_showpersonal = '如果啟用顯示施法條在你角色的血條上',
    castbar_showall = '顯示施法條在所有血條上，而不是只有當前目標',
    castbar_showfriend = '友方血條顯示施法條(注意當獨顯名稱模式啟用時施法條不會在框架上顯示)',
    castbar_showenemy = '敵對血條顯示施法條',
    castbar_unin_colour = '當施法無法被中斷時著色施法條',

    tank_mode = '當在坦克專精時重新著色你正在坦住單位的血條顏色',
    tankmode_force_enable = '總是使用坦克模式，不管你當前是否是坦克專精',
    threat_brackets = '在血條外顯示三角符號指示威脅狀態 (不需要坦克模式就可以使用)',
    tankmode_tank_colour = '當安全坦住時的血條顏色',
    tankmode_trans_colour = '當獲得或失去仇恨時的血條顏色',
    tankmode_other_colour = '當其他坦克接力坦住時的血條顏色。需要其他坦克在你的團隊中並且職責要設定為坦克',

    classpowers_enable = '顯示你職業的特殊資源，像是連擊點、聖能等等。',
    classpowers_on_target = '顯示在目標的框架上，而不是個人的血條。',
    classpowers_size = '職業能量圖標尺寸',
}
opt.titles = {
     profile = '設定檔',
    new_profile = '新設定檔...',
    new_profile_label = '鍵入設定檔名稱',
    delete_profile_label = '刪除設定檔 |cffffffff%s|r?',
    reset_profile_label = '重置設定檔 |cffffffff%s|r?',
    rename_profile_label = '鍵入新的名稱在 |cffffffff%s',
	version = '%s by %s @ Curse. 版本 %s',

    bar_texture = '血條材質',
    bar_animation = '血條動畫',

    combat_hostile = '戰鬥動作: 敵對',
    combat_friendly = '戰鬥動作: 友方',

    nameonly_sep = '獨顯名稱模式',
    nameonly = '使用獨顯名稱模式',
    nameonly_no_font_style = '無文字描邊',
    nameonly_damaged_friends = '在損傷的友方',
    nameonly_enemies = '在不可攻擊的敵人',
	nameonly_target = '使用在目標',
    nameonly_all_enemies = '使用在敵對',

    glow_as_shadow = '顯示框架陰影',
    state_icons = '顯示狀態圖標',
    target_glow = '顯示目標光暈',
    target_glow_colour = '目標光暈顏色',
	target_arrows = '顯示目標箭頭',
	frame_glow_size = '框架光暈尺寸',
    target_arrows_size = '目標箭頭尺寸',

    fade_rules_sep = '框架淡出',
    fade_alpha = '淡出透明度',
    fade_speed = '淡出動畫速度',
    fade_all = '預設淡出',
	fade_friendly_npc = '淡出友方NPC',
    fade_neutral_enemy = '淡出中立單位',
    fade_untracked = '淡出不可追蹤單位',
    fade_avoid_nameonly = '避開獨顯名稱',
    fade_avoid_raidicon = '避開團隊圖標',

    reaction_colour_sep = '血量條顏色',
    colour_hated = '仇恨',
    colour_neutral = '中立',
    colour_friendly = '友好',
    colour_tapped = '無拾取',
    colour_player = '玩家',
    colour_self_class = '自我職業著色',
    colour_self = '自己',
	colour_enemy_class = '敵對玩家職業著色',
	colour_enemy_player = '敵對玩家',
	colour_enemy_pet = '敵對寵物',
	
	execute_sep = '斬殺階段',
    execute_enabled = '啟用斬殺階段',
    execute_auto = '自動偵測斬殺血量',
    execute_colour = '斬殺著色',
    execute_percent = '斬殺血量',
	
    font_face = '字型選擇',
    font_style = '字型樣式',
    font_size_normal = '一般字體尺寸',
    font_size_small = '小字體尺寸',
    hide_names = '隱藏不重要單位名稱',
	name_text = '顯示名稱文字',
    level_text = '顯示等級文字',
    health_text = '顯示血量文字',
    text_vertical_offset = '文字 垂直偏移',
    name_vertical_offset = '名稱 垂直偏移',
    bot_vertical_offset = '等級/血量 垂直偏移',

	health_text_sep = '血量文字',
    health_text_friend_max = '滿血友方',
    health_text_friend_dmg = '損血友方',
    health_text_hostile_max = '滿血敵對',
    health_text_hostile_dmg = '損血敵對',
	
    frame_width = '框架寬度',
    frame_height = '框架高度',
    frame_width_minus = '小怪框架寬度',
    frame_height_minus = '小怪框架高度',
	powerbar_height = '能量條高度',
    castbar_height = '施法條高度',

    auras_enabled = '顯示光環',
	auras_on_personal = '顯示在自身框架',
    auras_whitelist = '使用白名單',
    auras_pulsate = '閃耀圖標',
	auras_centre = '圖標置中對齊',
	auras_sort = '排序方法',
    auras_filtering_sep = '過濾',
    auras_time_threshold = '計時器閥值',
    auras_minimum_length = '最小有效長度',
    auras_maximum_length = '最大有效長度',
    auras_icons_sep = '圖標',
    auras_icon_normal_size = '圖標尺寸(一般)',
    auras_icon_minus_size = '圖標尺寸(小怪)',
    auras_icon_squareness = '方形圖標',

    castbar_enable = '啟用',
    castbar_colour = '施法條顏色',
    castbar_unin_colour = '不可中斷顏色',
    castbar_showpersonal = '顯示自己的施法條',
    castbar_icon = '顯示法術圖標',
    castbar_name = '顯示法術名稱',
    castbar_showall = '顯示施法條在所有血條',
    castbar_showfriend = '顯示友方施法條',
    castbar_showenemy = '顯示敵對施法條',

    tank_mode = '啟用坦克模式',
    tankmode_force_enable = '強制坦克模式',
    threat_brackets = '顯示威脅括號',
    tankmode_colour_sep = '血條顏色',
    tankmode_tank_colour = '坦住',
    tankmode_trans_colour = '轉移',
    tankmode_other_colour = '換坦',

    classpowers_enable = '顯示職業資源',
    classpowers_on_target = '顯示在目標',
    classpowers_size = '圖標尺寸',
}
