local tinsert = table.insert

local inserted = false

function DBMCPOverwatch()
	if inserted then return end
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 安娜",					value 	= "Ana",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Ana\\",				max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 播音員",				value 	= "Overwatch",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Announcer\\",		max = 10})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 艾西",					value 	= "Ashe",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Ashe\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 巴帝斯特",				value 	= "Baptiste",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Baptiste\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 壁壘機兵",				value 	= "Bastion",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Bastion\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 壁壘機兵 (新)",		value 	= "Bastionnew",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Bastion_New\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 碧姬",					value 	= "Brigitte",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Brigitte\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: D.Va",					value 	= "DVa",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\DVa\\",				max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: D.Va (韓語)",			value 	= "DVakr",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\DVa\\kr\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 毀滅拳王",				value 	= "Doomfist",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Doomfist\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 迴音",					value 	= "Echo",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Echo\\",			max = 3})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 源氏",					value 	= "Genji",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Genji\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 源氏 (日語)",			value 	= "Genjijp",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Genji\\jp\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 半藏",					value 	= "Hanzo",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Hanzo\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 半藏 (日語)",			value 	= "Hanzojp",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Hanzo\\jp\\",		max = 3})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 炸彈鼠",				value 	= "Junkrat",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Junkrat\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 路西歐",				value 	= "Lucio",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Lucio\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 麥卡利",				value 	= "Mccree",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mccree\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 小美",					value 	= "Mei",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mei\\",				max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 小美 (華語)",			value 	= "Meicn",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mei\\cn\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 莫伊拉",				value 	= "Moira",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Moira\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 歐瑞莎",				value 	= "Orisa",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Orisa\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 慈悲",					value 	= "Mercy",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mercy\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 法拉",					value 	= "Pharah",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Pharah\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 死神",					value 	= "Reaper",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Reaper\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 萊因哈特",				value 	= "Reinhardt",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Reinhardt\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 攔路豬",				value 	= "Roadhog",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Roadhog\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 席格馬",				value 	= "Sigma",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Sigma\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 士兵",					value 	= "Soldier",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Soldier\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 辛梅塔",				value 	= "Symmetra",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Symmetra\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 駭影",					value 	= "Sombra",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Sombra\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 托比昂",				value 	= "Torbjorn",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Torbjorn\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 閃光",					value 	= "Tracer",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Tracer\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 奪命女",				value 	= "Widowmaker",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Widowmaker\\",		max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 溫斯頓",				value 	= "Winston",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Winston\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 火爆鋼球",				value 	= "Wrecking Ball",		path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Wrecking Ball\\",	max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 札莉雅",				value 	= "Zarya",				path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Zarya\\",			max = 5})
	tinsert(DBM.Counts, {	text	= "鬥陣特攻: 禪亞塔",				value 	= "Zenyatta",			path = "Interface\\AddOns\\DBM-CountPack-Overwatch\\Zenyatta\\",		max = 5})
	inserted = true
end
