-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this file,
-- You can obtain one at http://mozilla.org/MPL/2.0/.

-------------------------------------------------------------------------------
-- English localization (Default)
-------------------------------------------------------------------------------

-- Bindings
BINDING_HEADER_FLOTOTEMEARTH = "Floraline's Earth/Trap Bar";
BINDING_NAME_FLOTOTEMEARTHBUTTON1 = "Earth/Trap Button 1";
BINDING_NAME_FLOTOTEMEARTHBUTTON2 = "Earth/Trap Button 2";
BINDING_NAME_FLOTOTEMEARTHBUTTON3 = "Earth/Trap Button 3";
BINDING_NAME_FLOTOTEMEARTHBUTTON4 = "Earth/Trap Button 4";
BINDING_NAME_FLOTOTEMEARTHBUTTON5 = "Earth/Trap Button 5";
BINDING_NAME_FLOTOTEMEARTHBUTTON6 = "Earth/Trap Button 6";
BINDING_NAME_FLOTOTEMEARTHBUTTON7 = "Earth/Trap Button 7";
BINDING_NAME_FLOTOTEMEARTHBUTTON8 = "Earth/Trap Button 8";
BINDING_NAME_FLOTOTEMEARTHBUTTON9 = "Earth/Trap Button 9";
BINDING_NAME_FLOTOTEMEARTHBUTTON10 = "Earth/Trap Button 10";

BINDING_HEADER_FLOTOTEMFIRE = "Floraline's Fire Bar";
BINDING_NAME_FLOTOTEMFIREBUTTON1 = "Fire Button 1";
BINDING_NAME_FLOTOTEMFIREBUTTON2 = "Fire Button 2";
BINDING_NAME_FLOTOTEMFIREBUTTON3 = "Fire Button 3";
BINDING_NAME_FLOTOTEMFIREBUTTON4 = "Fire Button 4";
BINDING_NAME_FLOTOTEMFIREBUTTON5 = "Fire Button 5";
BINDING_NAME_FLOTOTEMFIREBUTTON6 = "Fire Button 6";
BINDING_NAME_FLOTOTEMFIREBUTTON7 = "Fire Button 7";
BINDING_NAME_FLOTOTEMFIREBUTTON8 = "Fire Button 8";
BINDING_NAME_FLOTOTEMFIREBUTTON9 = "Fire Button 9";
BINDING_NAME_FLOTOTEMFIREBUTTON10 = "Fire Button 10";
BINDING_HEADER_FLOTOTEMWATER = "Floraline's Water Bar";
BINDING_NAME_FLOTOTEMWATERBUTTON1 = "Water Button 1";
BINDING_NAME_FLOTOTEMWATERBUTTON2 = "Water Button 2";
BINDING_NAME_FLOTOTEMWATERBUTTON3 = "Water Button 3";
BINDING_NAME_FLOTOTEMWATERBUTTON4 = "Water Button 4";
BINDING_NAME_FLOTOTEMWATERBUTTON5 = "Water Button 5";
BINDING_NAME_FLOTOTEMWATERBUTTON6 = "Water Button 6";
BINDING_NAME_FLOTOTEMWATERBUTTON7 = "Water Button 7";
BINDING_NAME_FLOTOTEMWATERBUTTON8 = "Water Button 8";
BINDING_NAME_FLOTOTEMWATERBUTTON9 = "Water Button 9";
BINDING_NAME_FLOTOTEMWATERBUTTON10 = "Water Button 10";
BINDING_HEADER_FLOTOTEMAIR = "Floraline's Air Bar";
BINDING_NAME_FLOTOTEMAIRBUTTON1 = "Air Button 1";
BINDING_NAME_FLOTOTEMAIRBUTTON2 = "Air Button 2";
BINDING_NAME_FLOTOTEMAIRBUTTON3 = "Air Button 3";
BINDING_NAME_FLOTOTEMAIRBUTTON4 = "Air Button 4";
BINDING_NAME_FLOTOTEMAIRBUTTON5 = "Air Button 5";
BINDING_NAME_FLOTOTEMAIRBUTTON6 = "Air Button 6";
BINDING_NAME_FLOTOTEMAIRBUTTON7 = "Air Button 7";
BINDING_NAME_FLOTOTEMAIRBUTTON8 = "Air Button 8";
BINDING_NAME_FLOTOTEMAIRBUTTON9 = "Air Button 9";
BINDING_NAME_FLOTOTEMAIRBUTTON10 = "Air Button 10";

-- Layouts
FLO_TOTEM_1ROW = "1 Row";
FLO_TOTEM_2ROWS = "2 Rows - Downwards";
FLO_TOTEM_4ROWS = "4 Rows - Downwards";
FLO_TOTEM_2ROWS_REVERSE = "2 Rows - Upwards";
FLO_TOTEM_4ROWS_REVERSE = "4 Rows - Upwards";

-- Tooltips
FLO_TOTEM_ADD_CALL_TOOLTIP = "<Left-Click to Add this Totem to %s>";
FLO_TOTEM_REMOVE_CALL_TOOLTIP = "<Alt-Click to Remove this Totem from %s>";

-------------------------------------------------------------------------------
-- French localization
-------------------------------------------------------------------------------

if (GetLocale() == "frFR") then

-- Bindings
BINDING_HEADER_FLOTOTEMEARTH = "Barre de la terre / des pièges de Floraline";
BINDING_NAME_FLOTOTEMEARTHBUTTON1 = "Bouton de la terre / de piège 1";
BINDING_NAME_FLOTOTEMEARTHBUTTON2 = "Bouton de la terre / de piège 2";
BINDING_NAME_FLOTOTEMEARTHBUTTON3 = "Bouton de la terre / de piège 3";
BINDING_NAME_FLOTOTEMEARTHBUTTON4 = "Bouton de la terre / de piège 4";
BINDING_NAME_FLOTOTEMEARTHBUTTON5 = "Bouton de la terre / de piège 5";
BINDING_NAME_FLOTOTEMEARTHBUTTON6 = "Bouton de la terre / de piège 6";
BINDING_NAME_FLOTOTEMEARTHBUTTON7 = "Bouton de la terre / de piège 7";
BINDING_NAME_FLOTOTEMEARTHBUTTON8 = "Bouton de la terre / de piège 8";
BINDING_NAME_FLOTOTEMEARTHBUTTON9 = "Bouton de la terre / de piège 9";
BINDING_NAME_FLOTOTEMEARTHBUTTON10 = "Bouton de la terre / de piège 10";

BINDING_HEADER_FLOTOTEMFIRE = "Barre du feu de Floraline";
BINDING_NAME_FLOTOTEMFIREBUTTON1 = "Bouton du feu 1";
BINDING_NAME_FLOTOTEMFIREBUTTON2 = "Bouton du feu 2";
BINDING_NAME_FLOTOTEMFIREBUTTON3 = "Bouton du feu 3";
BINDING_NAME_FLOTOTEMFIREBUTTON4 = "Bouton du feu 4";
BINDING_NAME_FLOTOTEMFIREBUTTON5 = "Bouton du feu 5";
BINDING_NAME_FLOTOTEMFIREBUTTON6 = "Bouton du feu 6";
BINDING_NAME_FLOTOTEMFIREBUTTON7 = "Bouton du feu 7";
BINDING_NAME_FLOTOTEMFIREBUTTON8 = "Bouton du feu 8";
BINDING_NAME_FLOTOTEMFIREBUTTON9 = "Bouton du feu 9";
BINDING_NAME_FLOTOTEMFIREBUTTON10 = "Bouton du feu 10";
BINDING_HEADER_FLOTOTEMWATER = "Barre de l'eau de Floraline";
BINDING_NAME_FLOTOTEMWATERBUTTON1 = "Bouton de l'eau 1";
BINDING_NAME_FLOTOTEMWATERBUTTON2 = "Bouton de l'eau 2";
BINDING_NAME_FLOTOTEMWATERBUTTON3 = "Bouton de l'eau 3";
BINDING_NAME_FLOTOTEMWATERBUTTON4 = "Bouton de l'eau 4";
BINDING_NAME_FLOTOTEMWATERBUTTON5 = "Bouton de l'eau 5";
BINDING_NAME_FLOTOTEMWATERBUTTON6 = "Bouton de l'eau 6";
BINDING_NAME_FLOTOTEMWATERBUTTON7 = "Bouton de l'eau 7";
BINDING_NAME_FLOTOTEMWATERBUTTON8 = "Bouton de l'eau 8";
BINDING_NAME_FLOTOTEMWATERBUTTON9 = "Bouton de l'eau 9";
BINDING_NAME_FLOTOTEMWATERBUTTON10 = "Bouton de l'eau 10";
BINDING_HEADER_FLOTOTEMAIR = "Barre de l'air de Floraline";
BINDING_NAME_FLOTOTEMAIRBUTTON1 = "Bouton de l'air 1";
BINDING_NAME_FLOTOTEMAIRBUTTON2 = "Bouton de l'air 2";
BINDING_NAME_FLOTOTEMAIRBUTTON3 = "Bouton de l'air 3";
BINDING_NAME_FLOTOTEMAIRBUTTON4 = "Bouton de l'air 4";
BINDING_NAME_FLOTOTEMAIRBUTTON5 = "Bouton de l'air 5";
BINDING_NAME_FLOTOTEMAIRBUTTON6 = "Bouton de l'air 6";
BINDING_NAME_FLOTOTEMAIRBUTTON7 = "Bouton de l'air 7";
BINDING_NAME_FLOTOTEMAIRBUTTON8 = "Bouton de l'air 8";
BINDING_NAME_FLOTOTEMAIRBUTTON9 = "Bouton de l'air 9";
BINDING_NAME_FLOTOTEMAIRBUTTON10 = "Bouton de l'air 10";

-- Layouts
FLO_TOTEM_1ROW = "1 ligne";
FLO_TOTEM_2ROWS = "2 lignes - vers le bas";
FLO_TOTEM_4ROWS = "4 lignes - vers le bas";
FLO_TOTEM_2ROWS_REVERSE = "2 lignes - vers le haut";
FLO_TOTEM_4ROWS_REVERSE = "4 lignes - vers le haut";

-- Tooltips
FLO_TOTEM_ADD_CALL_TOOLTIP = "<Clic gauche pour ajouter ce totem à l'%s>";
FLO_TOTEM_REMOVE_CALL_TOOLTIP = "<Alt + Clic gauche pour enlever ce totem de l'%s>";

end

-------------------------------------------------------------------------------
-- German localization
-------------------------------------------------------------------------------

if (GetLocale() == "deDE") then

-- Bindings
BINDING_HEADER_FLOTOTEMEARTH = "Floralines Erdleiste/Fallenleiste";
BINDING_NAME_FLOTOTEMEARTHBUTTON1 = "Erdbutton/Fallesbutton 1";
BINDING_NAME_FLOTOTEMEARTHBUTTON2 = "Erdbutton/Fallesbutton 2";
BINDING_NAME_FLOTOTEMEARTHBUTTON3 = "Erdbutton/Fallesbutton 3";
BINDING_NAME_FLOTOTEMEARTHBUTTON4 = "Erdbutton/Fallesbutton 4";
BINDING_NAME_FLOTOTEMEARTHBUTTON5 = "Erdbutton/Fallesbutton 5";
BINDING_NAME_FLOTOTEMEARTHBUTTON6 = "Erdbutton/Fallesbutton 6";
BINDING_NAME_FLOTOTEMEARTHBUTTON7 = "Erdbutton/Fallesbutton 7";
BINDING_NAME_FLOTOTEMEARTHBUTTON8 = "Erdbutton/Fallesbutton 8";
BINDING_NAME_FLOTOTEMEARTHBUTTON9 = "Erdbutton/Fallesbutton 9";
BINDING_NAME_FLOTOTEMEARTHBUTTON10 = "Erdbutton/Fallesbutton 10";

BINDING_HEADER_FLOTOTEMFIRE = "Floralines Feuerleiste";
BINDING_NAME_FLOTOTEMFIREBUTTON1 = "Feuerbutton 1";
BINDING_NAME_FLOTOTEMFIREBUTTON2 = "Feuerbutton 2";
BINDING_NAME_FLOTOTEMFIREBUTTON3 = "Feuerbutton 3";
BINDING_NAME_FLOTOTEMFIREBUTTON4 = "Feuerbutton 4";
BINDING_NAME_FLOTOTEMFIREBUTTON5 = "Feuerbutton 5";
BINDING_NAME_FLOTOTEMFIREBUTTON6 = "Feuerbutton 6";
BINDING_NAME_FLOTOTEMFIREBUTTON7 = "Feuerbutton 7";
BINDING_NAME_FLOTOTEMFIREBUTTON8 = "Feuerbutton 8";
BINDING_NAME_FLOTOTEMFIREBUTTON9 = "Feuerbutton 9";
BINDING_NAME_FLOTOTEMFIREBUTTON10 = "Feuerbutton 10";
BINDING_HEADER_FLOTOTEMWATER = "Floralines Wasserleiste";
BINDING_NAME_FLOTOTEMWATERBUTTON1 = "Wasserbutton 1";
BINDING_NAME_FLOTOTEMWATERBUTTON2 = "Wasserbutton 2";
BINDING_NAME_FLOTOTEMWATERBUTTON3 = "Wasserbutton 3";
BINDING_NAME_FLOTOTEMWATERBUTTON4 = "Wasserbutton 4";
BINDING_NAME_FLOTOTEMWATERBUTTON5 = "Wasserbutton 5";
BINDING_NAME_FLOTOTEMWATERBUTTON6 = "Wasserbutton 6";
BINDING_NAME_FLOTOTEMWATERBUTTON7 = "Wasserbutton 7";
BINDING_NAME_FLOTOTEMWATERBUTTON8 = "Wasserbutton 8";
BINDING_NAME_FLOTOTEMWATERBUTTON9 = "Wasserbutton 9";
BINDING_NAME_FLOTOTEMWATERBUTTON10 = "Wasserbutton 10";
BINDING_HEADER_FLOTOTEMAIR = "Floralines Luftleiste";
BINDING_NAME_FLOTOTEMAIRBUTTON1 = "Luftbutton 1";
BINDING_NAME_FLOTOTEMAIRBUTTON2 = "Luftbutton 2";
BINDING_NAME_FLOTOTEMAIRBUTTON3 = "Luftbutton 3";
BINDING_NAME_FLOTOTEMAIRBUTTON4 = "Luftbutton 4";
BINDING_NAME_FLOTOTEMAIRBUTTON5 = "Luftbutton 5";
BINDING_NAME_FLOTOTEMAIRBUTTON6 = "Luftbutton 6";
BINDING_NAME_FLOTOTEMAIRBUTTON7 = "Luftbutton 7";
BINDING_NAME_FLOTOTEMAIRBUTTON8 = "Luftbutton 8";
BINDING_NAME_FLOTOTEMAIRBUTTON9 = "Luftbutton 9";
BINDING_NAME_FLOTOTEMAIRBUTTON10 = "Luftbutton 10";

-- Layouts
FLO_TOTEM_1ROW = "1 Reihe";
FLO_TOTEM_2ROWS = "2 Reihen - abwärts";
FLO_TOTEM_4ROWS = "4 Reihen - abwärts";
FLO_TOTEM_2ROWS_REVERSE = "2 Reihen - aufwärts";
FLO_TOTEM_4ROWS_REVERSE = "4 Reihen - aufwärts";

end

-------------------------------------------------------------------------------
-- Spanish localization
-------------------------------------------------------------------------------

if (GetLocale() == "esES") then

-- Bindings
BINDING_HEADER_FLOTOTEMEARTH = "Barra de la tierra / de las trampas de Floraline";
BINDING_NAME_FLOTOTEMEARTHBUTTON1 = "Botón de la tierra / de trampa 1";
BINDING_NAME_FLOTOTEMEARTHBUTTON2 = "Botón de la tierra / de trampa 2";
BINDING_NAME_FLOTOTEMEARTHBUTTON3 = "Botón de la tierra / de trampa 3";
BINDING_NAME_FLOTOTEMEARTHBUTTON4 = "Botón de la tierra / de trampa 4";
BINDING_NAME_FLOTOTEMEARTHBUTTON5 = "Botón de la tierra / de trampa 5";
BINDING_NAME_FLOTOTEMEARTHBUTTON6 = "Botón de la tierra / de trampa 6";
BINDING_NAME_FLOTOTEMEARTHBUTTON7 = "Botón de la tierra / de trampa 7";
BINDING_NAME_FLOTOTEMEARTHBUTTON8 = "Botón de la tierra / de trampa 8";
BINDING_NAME_FLOTOTEMEARTHBUTTON9 = "Botón de la tierra / de trampa 9";
BINDING_NAME_FLOTOTEMEARTHBUTTON10 = "Botón de la tierra / de trampa 10";
BINDING_HEADER_FLOTOTEMFIRE = "Barra del fuego de Floraline";
BINDING_NAME_FLOTOTEMFIREBUTTON1 = "Botón del fuego 1";
BINDING_NAME_FLOTOTEMFIREBUTTON2 = "Botón del fuego 2";
BINDING_NAME_FLOTOTEMFIREBUTTON3 = "Botón del fuego 3";
BINDING_NAME_FLOTOTEMFIREBUTTON4 = "Botón del fuego 4";
BINDING_NAME_FLOTOTEMFIREBUTTON5 = "Botón del fuego 5";
BINDING_NAME_FLOTOTEMFIREBUTTON6 = "Botón del fuego 6";
BINDING_NAME_FLOTOTEMFIREBUTTON7 = "Botón del fuego 7";
BINDING_NAME_FLOTOTEMFIREBUTTON8 = "Botón del fuego 8";
BINDING_NAME_FLOTOTEMFIREBUTTON9 = "Botón del fuego 9";
BINDING_NAME_FLOTOTEMFIREBUTTON10 = "Botón del fuego 10";
BINDING_HEADER_FLOTOTEMWATER = "Barra del agua de Floraline";
BINDING_NAME_FLOTOTEMWATERBUTTON1 = "Botón del agua 1";
BINDING_NAME_FLOTOTEMWATERBUTTON2 = "Botón del agua 2";
BINDING_NAME_FLOTOTEMWATERBUTTON3 = "Botón del agua 3";
BINDING_NAME_FLOTOTEMWATERBUTTON4 = "Botón del agua 4";
BINDING_NAME_FLOTOTEMWATERBUTTON5 = "Botón del agua 5";
BINDING_NAME_FLOTOTEMWATERBUTTON6 = "Botón del agua 6";
BINDING_NAME_FLOTOTEMWATERBUTTON7 = "Botón del agua 7";
BINDING_NAME_FLOTOTEMWATERBUTTON8 = "Botón del agua 8";
BINDING_NAME_FLOTOTEMWATERBUTTON9 = "Botón del agua 9";
BINDING_NAME_FLOTOTEMWATERBUTTON10 = "Botón del agua 10";
BINDING_HEADER_FLOTOTEMAIR = "Barra del aire de Floraline";
BINDING_NAME_FLOTOTEMAIRBUTTON1 = "Botón del aire 1";
BINDING_NAME_FLOTOTEMAIRBUTTON2 = "Botón del aire 2";
BINDING_NAME_FLOTOTEMAIRBUTTON3 = "Botón del aire 3";
BINDING_NAME_FLOTOTEMAIRBUTTON4 = "Botón del aire 4";
BINDING_NAME_FLOTOTEMAIRBUTTON5 = "Botón del aire 5";
BINDING_NAME_FLOTOTEMAIRBUTTON6 = "Botón del aire 6";
BINDING_NAME_FLOTOTEMAIRBUTTON7 = "Botón del aire 7";
BINDING_NAME_FLOTOTEMAIRBUTTON8 = "Botón del aire 8";
BINDING_NAME_FLOTOTEMAIRBUTTON9 = "Botón del aire 9";
BINDING_NAME_FLOTOTEMAIRBUTTON10 = "Botón del aire 10";

-- Layouts
FLO_TOTEM_1ROW = "1 fila";
FLO_TOTEM_2ROWS = "2 filas - hacia abajo";
FLO_TOTEM_4ROWS = "4 filas - hacia abajo";
FLO_TOTEM_2ROWS_REVERSE = "2 filas - hacia arriba";
FLO_TOTEM_4ROWS_REVERSE = "4 filas - hacia arriba";

end

-------------------------------------------------------------------------------
-- Russian localization
-------------------------------------------------------------------------------

if (GetLocale() == "ruRU") then

-- Bindings
BINDING_HEADER_FLOTOTEMEARTH = "Панели Земли/Ловушек - Floraline";
BINDING_NAME_FLOTOTEMEARTHBUTTON1 = "Земли/Ловушки: кнопка 1";
BINDING_NAME_FLOTOTEMEARTHBUTTON2 = "Земли/Ловушки: кнопка 2";
BINDING_NAME_FLOTOTEMEARTHBUTTON3 = "Земли/Ловушки: кнопка 3";
BINDING_NAME_FLOTOTEMEARTHBUTTON4 = "Земли/Ловушки: кнопка 4";
BINDING_NAME_FLOTOTEMEARTHBUTTON5 = "Земли/Ловушки: кнопка 5";
BINDING_NAME_FLOTOTEMEARTHBUTTON6 = "Земли/Ловушки: кнопка 6";
BINDING_NAME_FLOTOTEMEARTHBUTTON7 = "Земли/Ловушки: кнопка 7";
BINDING_NAME_FLOTOTEMEARTHBUTTON8 = "Земли/Ловушки: кнопка 8";
BINDING_NAME_FLOTOTEMEARTHBUTTON9 = "Земли/Ловушки: кнопка 9";
BINDING_NAME_FLOTOTEMEARTHBUTTON10 = "Земли/Ловушки: кнопка 10";
BINDING_HEADER_FLOTOTEMFIRE = "Панели огня - Floraline";
BINDING_NAME_FLOTOTEMFIREBUTTON1 = "Огоня: кнопка 1";
BINDING_NAME_FLOTOTEMFIREBUTTON2 = "Огоня: кнопка 2";
BINDING_NAME_FLOTOTEMFIREBUTTON3 = "Огоня: кнопка 3";
BINDING_NAME_FLOTOTEMFIREBUTTON4 = "Огоня: кнопка 4";
BINDING_NAME_FLOTOTEMFIREBUTTON5 = "Огоня: кнопка 5";
BINDING_NAME_FLOTOTEMFIREBUTTON6 = "Огоня: кнопка 6";
BINDING_NAME_FLOTOTEMFIREBUTTON7 = "Огоня: кнопка 7";
BINDING_NAME_FLOTOTEMFIREBUTTON8 = "Огоня: кнопка 8";
BINDING_NAME_FLOTOTEMFIREBUTTON9 = "Огоня: кнопка 9";
BINDING_NAME_FLOTOTEMFIREBUTTON10 = "Огоня: кнопка 10";
BINDING_HEADER_FLOTOTEMWATER = "Панели воды - Floraline";
BINDING_NAME_FLOTOTEMWATERBUTTON1 = "Воды: кнопка 1";
BINDING_NAME_FLOTOTEMWATERBUTTON2 = "Воды: кнопка 2";
BINDING_NAME_FLOTOTEMWATERBUTTON3 = "Воды: кнопка 3";
BINDING_NAME_FLOTOTEMWATERBUTTON4 = "Воды: кнопка 4";
BINDING_NAME_FLOTOTEMWATERBUTTON5 = "Воды: кнопка 5";
BINDING_NAME_FLOTOTEMWATERBUTTON6 = "Воды: кнопка 6";
BINDING_NAME_FLOTOTEMWATERBUTTON7 = "Воды: кнопка 7";
BINDING_NAME_FLOTOTEMWATERBUTTON8 = "Воды: кнопка 8";
BINDING_NAME_FLOTOTEMWATERBUTTON9 = "Воды: кнопка 9";
BINDING_NAME_FLOTOTEMWATERBUTTON10 = "Воды: кнопка 10";
BINDING_HEADER_FLOTOTEMAIR = "Панели воздуха - Floraline";
BINDING_NAME_FLOTOTEMAIRBUTTON1 = "Воздуха: кнопка 1";
BINDING_NAME_FLOTOTEMAIRBUTTON2 = "Воздуха: кнопка 2";
BINDING_NAME_FLOTOTEMAIRBUTTON3 = "Воздуха: кнопка 3";
BINDING_NAME_FLOTOTEMAIRBUTTON4 = "Воздуха: кнопка 4";
BINDING_NAME_FLOTOTEMAIRBUTTON5 = "Воздуха: кнопка 5";
BINDING_NAME_FLOTOTEMAIRBUTTON6 = "Воздуха: кнопка 6";
BINDING_NAME_FLOTOTEMAIRBUTTON7 = "Воздуха: кнопка 7";
BINDING_NAME_FLOTOTEMAIRBUTTON8 = "Воздуха: кнопка 8";
BINDING_NAME_FLOTOTEMAIRBUTTON9 = "Воздуха: кнопка 9";
BINDING_NAME_FLOTOTEMAIRBUTTON10 = "Воздуха: кнопка 10";

-- Layouts
FLO_TOTEM_1ROW = "1 ряд";
FLO_TOTEM_2ROWS = "2 ряда - вниз";
FLO_TOTEM_4ROWS = "4 ряда - вниз";
FLO_TOTEM_2ROWS_REVERSE = "2 ряда - вверх";
FLO_TOTEM_4ROWS_REVERSE = "4 ряда - вверх";

end

-------------------------------------------------------------------------------
-- Simplified Chinese localization
-------------------------------------------------------------------------------

if (GetLocale() == "zhCN") then

	-- Bindings
	BINDING_HEADER_FLOTOTEMEARTH = "Floraline的 地系图腾/陷阱 动作条";
	BINDING_NAME_FLOTOTEMEARTHBUTTON1 = "地系/陷阱 按钮 1";
	BINDING_NAME_FLOTOTEMEARTHBUTTON2 = "地系/陷阱 按钮 2";
	BINDING_NAME_FLOTOTEMEARTHBUTTON3 = "地系/陷阱 按钮 3";
	BINDING_NAME_FLOTOTEMEARTHBUTTON4 = "地系/陷阱 按钮 4";
	BINDING_NAME_FLOTOTEMEARTHBUTTON5 = "地系/陷阱 按钮 5";
	BINDING_NAME_FLOTOTEMEARTHBUTTON6 = "地系/陷阱 按钮 6";
	BINDING_NAME_FLOTOTEMEARTHBUTTON7 = "地系/陷阱 按钮 7";
	BINDING_NAME_FLOTOTEMEARTHBUTTON8 = "地系/陷阱 按钮 8";
	BINDING_NAME_FLOTOTEMEARTHBUTTON9 = "地系/陷阱 按钮 9";
	BINDING_NAME_FLOTOTEMEARTHBUTTON10 = "地系/陷阱 按钮 10";
	BINDING_HEADER_FLOTOTEMFIRE = "Floraline的 火系图腾 动作条";
	BINDING_NAME_FLOTOTEMFIREBUTTON1 = "火系 按钮 1";
	BINDING_NAME_FLOTOTEMFIREBUTTON2 = "火系 按钮 2";
	BINDING_NAME_FLOTOTEMFIREBUTTON3 = "火系 按钮 3";
	BINDING_NAME_FLOTOTEMFIREBUTTON4 = "火系 按钮 4";
	BINDING_NAME_FLOTOTEMFIREBUTTON5 = "火系 按钮 5";
	BINDING_NAME_FLOTOTEMFIREBUTTON6 = "火系 按钮 6";
	BINDING_NAME_FLOTOTEMFIREBUTTON7 = "火系 按钮 7";
	BINDING_NAME_FLOTOTEMFIREBUTTON8 = "火系 按钮 8";
	BINDING_NAME_FLOTOTEMFIREBUTTON9 = "火系 按钮 9";
	BINDING_NAME_FLOTOTEMFIREBUTTON10 = "火系 按钮 10";
	BINDING_HEADER_FLOTOTEMWATER = "Floraline的 水系图腾 动作条";
	BINDING_NAME_FLOTOTEMWATERBUTTON1 = "水系 按钮 1";
	BINDING_NAME_FLOTOTEMWATERBUTTON2 = "水系 按钮 2";
	BINDING_NAME_FLOTOTEMWATERBUTTON3 = "水系 按钮 3";
	BINDING_NAME_FLOTOTEMWATERBUTTON4 = "水系 按钮 4";
	BINDING_NAME_FLOTOTEMWATERBUTTON5 = "水系 按钮 5";
	BINDING_NAME_FLOTOTEMWATERBUTTON6 = "水系 按钮 6";
	BINDING_NAME_FLOTOTEMWATERBUTTON7 = "水系 按钮 7";
	BINDING_NAME_FLOTOTEMWATERBUTTON8 = "水系 按钮 8";
	BINDING_NAME_FLOTOTEMWATERBUTTON9 = "水系 按钮 9";
	BINDING_NAME_FLOTOTEMWATERBUTTON10 = "水系 按钮 10";
	BINDING_HEADER_FLOTOTEMAIR = "Floraline的 气系图腾 动作条";
	BINDING_NAME_FLOTOTEMAIRBUTTON1 = "气系 按钮 1";
	BINDING_NAME_FLOTOTEMAIRBUTTON2 = "气系 按钮 2";
	BINDING_NAME_FLOTOTEMAIRBUTTON3 = "气系 按钮 3";
	BINDING_NAME_FLOTOTEMAIRBUTTON4 = "气系 按钮 4";
	BINDING_NAME_FLOTOTEMAIRBUTTON5 = "气系 按钮 5";
	BINDING_NAME_FLOTOTEMAIRBUTTON6 = "气系 按钮 6";
	BINDING_NAME_FLOTOTEMAIRBUTTON7 = "气系 按钮 7";
	BINDING_NAME_FLOTOTEMAIRBUTTON8 = "气系 按钮 8";
	BINDING_NAME_FLOTOTEMAIRBUTTON9 = "气系 按钮 9";
	BINDING_NAME_FLOTOTEMAIRBUTTON10 = "气系 按钮 10";

	-- Layouts
	FLO_TOTEM_1ROW = "1 行";
	FLO_TOTEM_2ROWS = "2 行 - 向下";
	FLO_TOTEM_4ROWS = "4 行 - 向下";
	FLO_TOTEM_2ROWS_REVERSE = "2 行 - 向上";
	FLO_TOTEM_4ROWS_REVERSE = "4 行 - 向上";
end

-------------------------------------------------------------------------------
-- Traditional Chinese localization
-------------------------------------------------------------------------------

if (GetLocale() == "zhTW") then

-- Bindings
BINDING_HEADER_FLOTOTEMEARTH = "Floraline的 地系圖騰/陷阱 動作條";
BINDING_NAME_FLOTOTEMEARTHBUTTON1 = "地系/陷阱 按钮 1";
BINDING_NAME_FLOTOTEMEARTHBUTTON2 = "地系/陷阱 按钮 2";
BINDING_NAME_FLOTOTEMEARTHBUTTON3 = "地系/陷阱 按钮 3";
BINDING_NAME_FLOTOTEMEARTHBUTTON4 = "地系/陷阱 按钮 4";
BINDING_NAME_FLOTOTEMEARTHBUTTON5 = "地系/陷阱 按钮 5";
BINDING_NAME_FLOTOTEMEARTHBUTTON6 = "地系/陷阱 按钮 6";
BINDING_NAME_FLOTOTEMEARTHBUTTON7 = "地系/陷阱 按钮 7";
BINDING_NAME_FLOTOTEMEARTHBUTTON8 = "地系/陷阱 按钮 8";
BINDING_NAME_FLOTOTEMEARTHBUTTON9 = "地系/陷阱 按钮 9";
BINDING_NAME_FLOTOTEMEARTHBUTTON10 = "地系/陷阱 按钮 10";
BINDING_HEADER_FLOTOTEMFIRE = "Floraline的 火系圖騰 動作條";
BINDING_NAME_FLOTOTEMFIREBUTTON1 = "火系 按钮 1";
BINDING_NAME_FLOTOTEMFIREBUTTON2 = "火系 按钮 2";
BINDING_NAME_FLOTOTEMFIREBUTTON3 = "火系 按钮 3";
BINDING_NAME_FLOTOTEMFIREBUTTON4 = "火系 按钮 4";
BINDING_NAME_FLOTOTEMFIREBUTTON5 = "火系 按钮 5";
BINDING_NAME_FLOTOTEMFIREBUTTON6 = "火系 按钮 6";
BINDING_NAME_FLOTOTEMFIREBUTTON7 = "火系 按钮 7";
BINDING_NAME_FLOTOTEMFIREBUTTON8 = "火系 按钮 8";
BINDING_NAME_FLOTOTEMFIREBUTTON9 = "火系 按钮 9";
BINDING_NAME_FLOTOTEMFIREBUTTON10 = "火系 按钮 10";
BINDING_HEADER_FLOTOTEMWATER = "Floraline的 水系圖騰 動作條";
BINDING_NAME_FLOTOTEMWATERBUTTON1 = "水系 按钮 1";
BINDING_NAME_FLOTOTEMWATERBUTTON2 = "水系 按钮 2";
BINDING_NAME_FLOTOTEMWATERBUTTON3 = "水系 按钮 3";
BINDING_NAME_FLOTOTEMWATERBUTTON4 = "水系 按钮 4";
BINDING_NAME_FLOTOTEMWATERBUTTON5 = "水系 按钮 5";
BINDING_NAME_FLOTOTEMWATERBUTTON6 = "水系 按钮 6";
BINDING_NAME_FLOTOTEMWATERBUTTON7 = "水系 按钮 7";
BINDING_NAME_FLOTOTEMWATERBUTTON8 = "水系 按钮 8";
BINDING_NAME_FLOTOTEMWATERBUTTON9 = "水系 按钮 9";
BINDING_NAME_FLOTOTEMWATERBUTTON10 = "水系 按钮 10";
BINDING_HEADER_FLOTOTEMAIR = "Floraline的 風系圖騰 動作條";
BINDING_NAME_FLOTOTEMAIRBUTTON1 = "風系 按钮 1";
BINDING_NAME_FLOTOTEMAIRBUTTON2 = "風系 按钮 2";
BINDING_NAME_FLOTOTEMAIRBUTTON3 = "風系 按钮 3";
BINDING_NAME_FLOTOTEMAIRBUTTON4 = "風系 按钮 4";
BINDING_NAME_FLOTOTEMAIRBUTTON5 = "風系 按钮 5";
BINDING_NAME_FLOTOTEMAIRBUTTON6 = "風系 按钮 6";
BINDING_NAME_FLOTOTEMAIRBUTTON7 = "風系 按钮 7";
BINDING_NAME_FLOTOTEMAIRBUTTON8 = "風系 按钮 8";
BINDING_NAME_FLOTOTEMAIRBUTTON9 = "風系 按钮 9";
BINDING_NAME_FLOTOTEMAIRBUTTON10 = "風系 按钮 10";

-- Layouts
FLO_TOTEM_1ROW = "1 行";
FLO_TOTEM_2ROWS = "2 行 - 向下";
FLO_TOTEM_4ROWS = "4 行 - 向下";
FLO_TOTEM_2ROWS_REVERSE = "2 行 - 向上";
FLO_TOTEM_4ROWS_REVERSE = "4 行 - 向上";
end

