--[[--------------------------------------------------------------------
	PhanxBuffs
	Replacement player buff, debuff, and temporary enchant frames.
	Copyright (c) 2010-2016 Phanx <addons@phanx.net>. All rights reserved.
	https://github.com/Phanx/PhanxBuffs
	https://mods.curse.com/addons/wow/phanxbuffs
	http://www.wowinterface.com/downloads/info16874-PhanxBuffs.html
----------------------------------------------------------------------]]

local ADDON_NAME, ns = ...
local L = {}
ns.L = L

setmetatable(L, { __index = function(t, k)
	local v = tostring(k)
	t[k] = v
	return v
end })

L["%d minutes remaining"] = SPELL_TIME_REMAINING_MIN -- "%d |4minute:minutes; remaining"
L["%d seconds remaining"] = SPELL_TIME_REMAINING_SEC -- "%d |4second:seconds; remaining"

-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED. SEE:
-- https://wow.curseforge.com/addons/phanxbuffs/localization/

------------------------------------------------------------------------
-- English
------------------------------------------------------------------------

local CURRENT_LOCALE = GetLocale()
if CURRENT_LOCALE == "enUS" then return end

------------------------------------------------------------------------
-- Simplified Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhCN" then

L["Adjust the maximum remaining duration, in seconds, to show the timer text for a buff or debuff."] = "调整显示buff或debuff剩余时间的最大值(秒)."
L["Adjust the number of buff icons to show on each row."] = "调整每行buff图标的个数."
L["Adjust the number of debuff icons to show on each row."] = "调整每行debuff图标的个数."
L["Adjust the size of each buff icon."] = "调整每个buff图标的大小."
L["Adjust the size of each debuff icon."] = "调整每个debuff图标的大小."
L["Adjust the size of the stack count and timer text."] = "调整层数与持续时间文字的大小."
L["Adjust the space between buff icons."] = "调整每个buff图标之间的距离."
L["Adjust the space between debuff icons."] = "调整每个debuff图标之间的距离."
L["Basic replacement for player buff, debuff, and temporary enchant frames."] = "为玩家buff,debuff以及临时附魔框体提供简单的替换"
L["Bottom"] = "底部"
L["buff"] = "增益"
L["Buff Anchor"] = "Buff 增长锚点"
L["Buff Columns"] = "Buff 栏"
L["Buff Size"] = "Buff 大小"
L["Buff Sources"] = "Buff 来源"
L["Buff Spacing"] = "Buff 间距"
L["Cancel unprotected buffs on the first click, instead of the second. Only works out of combat, and protected buffs like shapeshift forms and weapon buffs will still require two clicks."] = "通过首次点击而非第二次取消未受保护的buff,只在非战斗状态下生效,并且类似变形和武器buff之类的受保护buff依然需要两次点击."
L["Cast by %s"] = "来自 %s"
L["Choose whether the buff icons grow from left to right, or right to left."] = "选择buff图标的增长方向是 从左到右 还是 从右到左."
L["Choose whether the buff icons grow from top to bottom, or bottom to top."] = "选择buff图标的增长方向是 从上到下 还是 从下到上."
L["Choose whether the debuff icons grow from left to right, or right to left."] = "选择debuff图标的增长方向是 从左到右 还是 从右到左."
L["Choose whether the debuff icons grow from top to bottom, or bottom to top."] = "选择debuff图标的增长方向是 从上到下 还是 从下到上."
L["%d |4buff:buffs; |4is:are; being ignored:"] = "%d个 |4buff:buffs; 已被忽略:"
L["%d |4debuff:debuffs; |4is:are; being ignored:"] = "%d |4debuff:debuffs; |4已被忽略:"
L["debuff"] = "减益"
L["Debuff Anchor"] = "Debuff 增长锚点"
L["Debuff Columns"] = "Debuff 栏"
L["Debuff Size"] = "Debuff 大小"
L["Debuff Spacing"] = "Debuff 间距"
L["Left"] = "左侧"
L["lock"] = "锁定"
L["Lock Frames"] = "锁定框体"
L["Lock the buff and debuff frames in place, hiding the backdrop and preventing them from being moved."] = "锁定buff与debuff框体,隐藏背景并防止它们被移动."
L["Max Timer Duration"] = "最大持续时间"
L["No buffs are being ignored."] = "没有忽略的buff"
L["No debuffs are being ignored."] = "没有忽略的debuff"
L["No longer ignoring buff: %s"] = "不再忽略buff: %s"
L["No longer ignoring debuff: %s"] = "不再忽略debuff: %s"
L["None"] = "无"
L["Now ignoring buff: %s"] = "从现在起忽略buff: %s"
L["Now ignoring debuff: %s"] = "从现在起忽略debuff: %s"
L["One-Click Cancel"] = "单击取消"
L["Right"] = "右侧"
L["Set the outline weight for the stack count and timer text."] = "调整层数与持续时间文字的轮廓."
L["Set the typeface for the stack count and timer text."] = "选择层数与持续时间文字的字体."
L["Show the name of the party or raid member who cast a buff on you in its tooltip."] = "在鼠标提示中显示对你施放此buff的小队/团队成员姓名"
L["Text Outline"] = "轮廓"
L["Text Size"] = "字体大小"
L["Thick"] = "粗轮廓"
L["Thin"] = "轮廓"
L["Top"] = "顶部"
L["Typeface"] = "字体"
L["unlock"] = "解锁"
L["Use this panel to adjust some basic settings for buff, debuff, and weapon buff icons."] = "在当前面板进行增益、减益、武器临时附魔图标的基本设置."

return end

------------------------------------------------------------------------
-- Traditional Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhTW" then

L["Adjust the maximum remaining duration, in seconds, to show the timer text for a buff or debuff."] = "剩餘時間為多少秒時才要顯示增益或減益效果的計時數字，以秒為單位。"
L["Adjust the number of buff icons to show on each row."] = "調整每一個橫列要顯示多少個增益效果圖示。"
L["Adjust the number of debuff icons to show on each row."] = "調整每一個橫列要顯示多少個減益效果圖示。"
L["Adjust the size of each buff icon."] = "調整增益效果圖示的大小。"
L["Adjust the size of each debuff icon."] = "調整減益效果圖示的大小。"
L["Adjust the size of the stack count and timer text."] = "調整堆疊層數和計時文字的大小。"
L["Adjust the space between buff icons."] = "調整增益效果圖示之間的距離。"
L["Adjust the space between debuff icons."] = "調整減益效果圖示之間的距離。"
L["Basic replacement for player buff, debuff, and temporary enchant frames."] = "取代玩家增益、減益效果，和暫時性增強效果原本的框架。"
L["Bottom"] = "底部"
L["buff"] = "增益效果"
L["Buff Anchor"] = "增益效果對齊"
L["Buff Columns"] = "增益效果行數"
L["Buff Size"] = "增益效果圖示大小"
L["Buff Sources"] = "增益效果施法者名字"
L["Buff Spacing"] = "增益效果圖示間距"
L["Cancel unprotected buffs on the first click, instead of the second. Only works out of combat, and protected buffs like shapeshift forms and weapon buffs will still require two clicks."] = "點一下來取消未受保護的增益效果，而不是點兩下，只在非戰鬥中有效。受保護的增益效果，例如改變形態和武器特效仍然需要點兩下。"
L["Cast by %s"] = "施法者: %s"
L["Choose whether the buff icons grow from left to right, or right to left."] = "選擇增益圖示增加時，要從左到右延伸，還是從右到左。"
L["Choose whether the buff icons grow from top to bottom, or bottom to top."] = "選擇增益圖示增加時，要從上到下延伸，還是從下到上。"
L["Choose whether the debuff icons grow from left to right, or right to left."] = "選擇減益圖示增加時，要從左到右延伸，還是從右到左。"
L["Choose whether the debuff icons grow from top to bottom, or bottom to top."] = "選擇減益圖示增加時，要從上到下延伸，還是從下到上。"
L["%d |4buff:buffs; |4is:are; being ignored:"] = "%d 個增益效果被忽略:"
L["%d |4debuff:debuffs; |4is:are; being ignored:"] = "%d 個減益效果被忽略:"
L["debuff"] = "減益效果"
L["Debuff Anchor"] = "減益效果對齊"
L["Debuff Columns"] = "減益效果行數"
L["Debuff Size"] = "減益效果圖示大小"
L["Debuff Spacing"] = "減益效果圖示間距"
L["Left"] = "左"
L["lock"] = "鎖定"
L["Lock Frames"] = "鎖定框架位置"
L["Lock the buff and debuff frames in place, hiding the backdrop and preventing them from being moved."] = "將增益和減益效果圖示的框架鎖定在目前的位置，隱藏位置展示方塊並且防止被移動。"
L["Max Timer Duration"] = "最大剩餘時間"
L["No buffs are being ignored."] = "沒有被忽略的增益效果。"
L["No debuffs are being ignored."] = "沒有被忽略的減益效果。"
L["No longer ignoring buff: %s"] = "不要忽略的增益效果: %s"
L["No longer ignoring debuff: %s"] = "不要忽略的減益效果: %s"
L["None"] = "無"
L["Now ignoring buff: %s"] = "現在忽略的增益效果: %s"
L["Now ignoring debuff: %s"] = "現在忽略的減益效果: %s"
L["One-Click Cancel"] = "點一下取消效果"
L["Right"] = "右"
L["Set the outline weight for the stack count and timer text."] = "設定堆疊層數和計時數字文字的外框粗細。"
L["Set the typeface for the stack count and timer text."] = "設定堆疊層數和計時數字文字的字型。"
L["Show the name of the party or raid member who cast a buff on you in its tooltip."] = "在滑鼠提示中顯示對你施放增益效果的隊伍或團隊成員名字。"
L["Text Outline"] = "文字外框"
L["Text Size"] = "文字大小"
L["Thick"] = "粗"
L["Thin"] = "細"
L["Top"] = "頂部"
L["Typeface"] = "字型"
L["unlock"] = "解鎖"
L["Use this panel to adjust some basic settings for buff, debuff, and weapon buff icons."] = "這裡可以調整增益、減益效果和武器特效圖示的基本設定。"
L["Click to lock or unlock the frames."] = "點擊來鎖定或解鎖框架。"
L["Right-click for options."] = "右鍵點擊開啟選項。"
L["Show Buff Sources"] = "顯示增益來源"

return end
