local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_CovenantSanctum", "esES", false, true)

if not L then return end
-- Spanish localization by Irakua ( https://www.curseforge.com/members/irakua )
if L then
L["Blizzard"] = true
L["Both"] = "Ambos"
L["config_easy_waypoints"] = "Puntos de ruta fáciles"
L["config_easy_waypoints_desc"] = "Activa la creación de puntos de ruta simplificada. Permite establecer un punto de ruta haciendo clic con el botón derecho y acceder a más opciones con CTRL + clic derecho."
L["config_icon_alpha"] = "Opacidad"
L["config_icon_alpha_desc"] = "La transparencia alfa de los iconos"
L["config_icon_scale"] = "Escala"
L["config_icon_scale_desc"] = "La escala de los iconos"
L["config_innkeeper"] = "Tabernero"
L["config_innkeeper_desc"] = "Muestra las ubicaciones de los taberneros."
L["config_mail"] = "Correo"
L["config_mail_desc"] = "Muestra las ubicaciones de los correos."
L["config_others"] = "Otros"
L["config_others_desc"] = "Mostrar todos los otros Puntos de interés."
L["config_plugin_desc"] = "Muestra las ubicaciones de PNJ y PDI en tu santuario de curia en el mapa del mundo y el minimapa."
L["config_plugin_name"] = "Covenant Sanctum"
L["config_portal"] = "Portal"
L["config_portal_desc"] = "Muestra las ubicaciones de los portales"
L["config_reforge"] = "Mejora de Armas"
L["config_reforge_desc"] = "Muestra las ubicaciones de las mejoras de armas."
L["config_renown"] = "Guardián del Renombre"
L["config_renown_desc"] = "Mostrar la ubicación de los guardianes del renombre."
L["config_restore_nodes"] = "Restaurar nodos ocultos"
L["config_restore_nodes_desc"] = "Restaurar todos los nodos que se han ocultado por el menú contextual."
L["config_restore_nodes_print"] = "Todos los nodos ocultos han sido restaurados"
L["config_stablemaster"] = "Maestro de establos"
L["config_stablemaster_desc"] = "Mostrar la ubicación de los maestros de establos."
L["config_tab_general"] = "General"
L["config_travelguide_note"] = "|cFFFF0000*Ya activo a través de HandyNotes: TravelGuide.|r"
L["config_vendor"] = "Vendedor"
L["config_vendor_desc"] = "Mostrar la ubicación de los vendedores."
L["config_waypoint_dropdown"] = "Elige"
L["config_waypoint_dropdown_desc"] = "Elije cómo se debe crear el punto de ruta."
L["config_weaponsmith"] = "Armero"
L["config_weaponsmith_desc"] = "Mostrar la ubicación de los armeros."
L["config_what_to_display"] = "¿Qué mostrar?"
L["config_what_to_display_desc"] = "Esta configuración controla qué tipo de iconos se mostrarán."
L["handler_context_menu_add_tomtom"] = "Agregar a TomTom"
L["handler_context_menu_addon_name"] = "HandyNotes: Covenant Sanctum"
L["handler_context_menu_hide_node"] = "Ocultar este nodo"
L["handler_tooltip_requires"] = "Requiere"
L["handler_tooltip_sanctum_feature"] = "una Mejora de Santuario"
L["handler_tooltip_TNTIER"] = "Nivel %s de la red de transporte."
L["Mailbox"] = "Correo"
L["Portal to Oribos"] = "Portal a Oribos"
L["TomTom"] = true
end