local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_CovenantSanctum", "ruRU", false, true)

if not L then return end
-- Russian localization by dadec666 ( https://www.curseforge.com/members/dadec666 )
if L then
L["Blizzard"] = true
L["Both"] = "Оба"
L["config_easy_waypoints"] = "Легкие путевые точки"
L["config_easy_waypoints_desc"] = "Активирует упрощенное создание путевой точки. Позволяет установить маршрутную точку, щелкнув правой кнопкой мыши, и получить доступ к дополнительным параметрам, нажав CTRL + щелчок правой кнопкой мыши."
L["config_icon_alpha"] = "Прозрачность иконок"
L["config_icon_alpha_desc"] = "Изменяет прозрачность иконок"
L["config_icon_scale"] = "Размер иконок"
L["config_icon_scale_desc"] = "Изменяет размер иконок"
L["config_innkeeper"] = "Хозяин таверны"
L["config_innkeeper_desc"] = "Покажите местонахождение хозяина таверны."
L["config_mail"] = "Почтовый ящик"
L["config_mail_desc"] = "Показать расположение почтовых ящиков."
L["config_others"] = "Другие"
L["config_others_desc"] = "Показать все остальные POI."
L["config_plugin_desc"] = "Отображает местоположения NPC и POI в Обители ковенанта на карте мира и миникарте."
L["config_plugin_name"] = "Covenant Sanctum"
L["config_portal"] = "Портал"
L["config_portal_desc"] = "Показать расположение портала."
L["config_reforge"] = "Усиление Брони"
L["config_reforge_desc"] = "Покажите расположение усилителя брони."
L["config_renown"] = "Хранитель известности"
L["config_renown_desc"] = "Показать местонахождение хранителя известности."
L["config_restore_nodes"] = "Восстановить скрытые узлы"
L["config_restore_nodes_desc"] = "Восстановить все узлы, которые были скрыты через контекстное меню."
L["config_restore_nodes_print"] = "Все скрытые узлы были восстановлены"
L["config_stablemaster"] = "Смотритель стойл"
L["config_stablemaster_desc"] = "Показать местонахождение смотрителя стойл."
L["config_tab_general"] = "Общий"
L["config_travelguide_note"] = "| cFFFF0000 * Уже активен через HandyNotes: TravelGuide. | r"
L["config_vendor"] = "Торговец"
L["config_vendor_desc"] = "Показать местоположение торговца."
L["config_waypoint_dropdown"] = "Выбор"
L["config_waypoint_dropdown_desc"] = "Выберите способ создания путевой точки."
L["config_weaponsmith"] = "Оружейник"
L["config_weaponsmith_desc"] = "Показать местонахождение оружейника."
L["config_what_to_display"] = "Что отображать?"
L["config_what_to_display_desc"] = "Эти настройки определяют, какой тип значков будет отображаться."
L["handler_context_menu_add_tomtom"] = "Добавить в TomTom"
L["handler_context_menu_addon_name"] = "HandyNotes: Oribos"
L["handler_context_menu_hide_node"] = "Скрыть этот узел"
L["handler_tooltip_requires"] = "Требуется"
L["handler_tooltip_sanctum_feature"] = "Улучшение святилища"
L["handler_tooltip_TNTIER"] = "Уровень %s сети путешествий."
L["Mailbox"] = "Почтовый ящик"
L["Portal to Oribos"] = "Портал в Орибос"
L["TomTom"] = true
end